### ISSUE TITLE
[BUG] Resuming previous session should start downloads immediately

### ISSUE THREAD

**Issue by art435** [iyear/tdl#100]
**Describe the bug**
When resuming the previous session, the downloads don't start right away. The program is pausing for a time. The more files were downloaded previously, the more time is pausing. I think it searches again all the files in the source chat and compare them to files already downloaded to check for duplicates. Should start quickly from where it stopped last time.

**To Reproduce**
Find a chat with many files. Export the json. Start a new session. Download a large amount of files. Close the program. Start a new session.

**Expected behavior**
The program should start the downloads promptly.

**Version:**
0.7.0

**Additional context**
If I export again the json from the last file downloaded, the program starts the downloads rapidly.

**Comment by iyear** [comment]
How much time do you currently need to spend? and the corresponding number of downloads.

I probably know the problem, I will optimize the speed in the next version.

**Comment by iyear** [comment]
I will try to fix this issue in the next minor release. Thanks for the feedback.

**Comment by iyear** [comment]
The new version has been released, feel free to try it or reopen the issue.
