### ISSUE TITLE
[Feat] Restart the program if connection is closed

### ISSUE THREAD

**Issue by art435** [iyear/tdl#101]
Sometimes the connection is closed and program stops. In the logs I see this message `"error": "duplicate or too low message id, message rejected, Close called `
This was probably caused by network issues or by Telegram instability. I think it is better to restart the program and resume the downloads when this happens.

Probably is a good idea to remove the limit of connections retries too. The program should keep retrying till a connection is established.

**Comment by iyear** [comment]
When this happens, wouldn't the progress be saved? If normal, any exit due to an error will save the current progress

**Comment by art435** [comment]
I'm not talking about resuming the downloads from where it stopped, I'm talking about resuming the program when it stops due to some errors. Nobody can stay all the time close to the PC to restart the program manually. This should be done automatically.

**Comment by iyear** [comment]
Get. I propose a solution that I don't know if it is feasible: leave the daemon to an external program, which is implemented in good applications on different platforms. Also provide options like `--continue` and `--restart` in the CLI.

Then every time the program exits, the external program will automatically restart tdl and continue working, which is one of the most robust and decoupled approaches.

In some cases, infinite retries do not always work. Restarting is the best practice.

**Comment by art435** [comment]
That sounds a little bit complicated. Why the program is closed when a connection is lost or closed? Can these be separated? Like, keep the program running when a connection is closed or lost and just reconnect.

**Comment by iyear** [comment]
Once an error is received during the download process, the entire program is terminated. This is because tdl cannot make intelligent judgments about the various errors: this is recoverable or this is not recoverable.

**Comment by art435** [comment]
Probably this ? https://t.me/TelethonChat/31449
I changed the time server, I hope it won't happen again.
Regarding the closing tdl, is there a reason why not keep the program running when some errors try to close it? The program should only pause on floodwait and keep running until his job is done. No errors should forcibly close the program, just the connection.

**Comment by iyear** [comment]
emmm. This can also be changed that each file download does not interfere with each other, and if there is an error the current file status is set to failed and does not affect other downloads.

But there are a lot of things to consider, such as some unrecoverable errors (e.g. parameter errors, internal server errors), which would lead to thousands of errors and the program would not stop.

**Comment by art435** [comment]
But, at least some of the errors should be obvious at the program start, for example the user is not a member in a private chat and the download won't start. But if all settings are ok, the program should keep running. Some of them will not be resolved, example Telegram outage, but for the rest of the cases keeping the program running will eventually resume the downloads.

**Comment by iyear** [comment]
The new version has been released, feel free to try it or reopen the issue.
