### ISSUE TITLE
[Feat] If file names contain underscores, replace them by spaces

### ISSUE THREAD

**Issue by art435** [iyear/tdl#103]
The underscores in filenames are added in many cases by Telegram when the filenames are very long. The tdl mimics this behavior and adds underscores when it downloads, even the filenames in chat don't have any. The filenames should be kept clean with no underscore, so tdl should replace them with spaces when it downloads the files.

**Comment by iyear** [comment]
I'm a little confused about the difference between this and #102. But putting that aside, I propose a solution.

Enhance the syntax of filename templates to support text processing functions such as replace. Leave it up to the user to decide what to do.

**Comment by iyear** [comment]
The new version has been released, feel free to try it or reopen the issue.
