### ISSUE TITLE
[Feat] When exporting the json with tdl follow the official order of files

### ISSUE THREAD

**Issue by art435** [iyear/tdl#104]
tdl exports the json with the file ids in reverse order, from the most recent to the oldest ones. The official Telegram client exports from the oldest file ids to the newest ones.

**Comment by iyear** [comment]
The role of exported JSON in tdl is to read the list of messages, does this order make any difference? Changing the order is not very simple.

**Comment by art435** [comment]
I thought that order is important for the program, but I checked with the json exported from the official app and the downloads still happens in reverse order, from the newest to the oldest files. It seems that the order of file ids in json is not important. You can ignore this issue, the tdl should change the order in which it downloads files.

**Comment by art435** [comment]
Closing this because the program controls the order of files downloaded, regardless of the order of file ids in json.
