### ISSUE TITLE
[Feat] tdl should download files from the oldest to the newest ones

### ISSUE THREAD

**Issue by art435** [iyear/tdl#105]
The official client and most programs that download files from chats use the order from the beginning of the chat to the latest files (oldest to newest). tdl uses order from the newest to the oldest. This has causing some troubles when I exported json with id ranges.

tdl should use the order that most programs use, from the oldest files to the newest ones. First I thought that this happening because the tdl exported json in this order too, but I download with the json exported from the official app, that has files ordered from the oldest to the newest, and tdl still downloads from the newest to the oldest.

**Comment by iyear** [comment]
This is due to the fact that after reading in the JSON, it is sorted once to ensure the stability of the fingerprint. In this sorting I sorted the message ids in descending order.

This may be duplicate with #104 , I suggest that only remain one.

**Comment by iyear** [comment]
This can be fixed, but all fingerprints and progress generated in v0.7.0 will be corrupted.

**Comment by iyear** [comment]
The new version has been released, feel free to try it or reopen the issue.
