### ISSUE TITLE
callback: validate domain: is empty[BUG] 

### ISSUE THREAD

**Issue by 123xsz** [iyear/tdl#109]
**Describe the bug**
用群组链接下载的时候返回的错误，已经在telegram客户端允许了外部数据访问

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version:**
0.7.1

**Additional context**

**Comment by iyear** [comment]
Please upload your command or screenshot, a single description will not solve the problem.

**Comment by zk637** [comment]
I also encountered this problem when downloading group link records. Here is my screenshot.I hope this will help
![image](https://user-images.githubusercontent.com/78423939/219415557-75f44be1-71f0-4e66-8a5d-d730439fc62f.png)

**Comment by iyear** [comment]
It looks like your link doesn't contain a message ID. Link format: `t.me/CHATID(NAME)/MESSAGE_ID`

This can be accomplished with a client-side "copy message link".

**Comment by zk637** [comment]
> MESSAGE_ID

Yes, I tried the command again and added MESSAGE_ID,it's work normally thank for your reply.
