### ISSUE TITLE
How to batch download based on message ID?

### ISSUE THREAD

**Issue by Romntic** [iyear/tdl#111]
hello how are u @iyear 
**I would like to thank you for your great work**
can u make download automatic download from 1 to 5 not need to write 1 2 3 4 5  
for example  
this is normal usage 
tdl dl -u https://t.me/tdl/1 -u https://t.me/tdl/2  -u https://t.me/tdl/3  -u https://t.me/tdl/4  -u https://t.me/tdl/4  -u https://t.me/tdl/5
if u can make download from 1 to 5    
5 file 

thanks

**Comment by iyear** [comment]
Try
```shell
# chat input examples: `@iyear`, `iyear`, `123456789`(chat id), `https://t.me/iyear`, `+1 123456789`
tdl chat export -c CHAT_INPUT --from 1 --to 5 --msg -o result.json
tdl dl -f result.json
```
And add other command flags if needed.

Ref: 
- https://github.com/iyear/tdl#chat-utilities
- https://github.com/iyear/tdl#download

**Comment by Romntic** [comment]
tdl login -n quickstart -d  /Applications/Telegram.app                            
Namespace: quickstart
WARN: If data exists in the namespace, data will be overwritten
Importing session from desktop client: /Applications/Telegram.app
open key_data: file "key_data" not found

**Comment by iyear** [comment]
Where did you download the Telegram APP from? https://telegram.org/dl/desktop/mac?

**Comment by iyear** [comment]
On Windows, the Telegram root directory has a `tdata` dir.

**Comment by Romntic** [comment]
![Screen Shot 2023-02-27 at 1 38 49 AM](https://user-images.githubusercontent.com/31198048/221441901-08048b05-5eeb-4254-8c01-86b9add96b76.png)

**Comment by suntong** [comment]
This issue can be closed.
