### ISSUE TITLE
[Feat] path template instead of name template

### ISSUE THREAD

**Issue by yyuchenn** [iyear/tdl#113]
It would be nice if we can customize file paths instead of just filenames. i.e. When I call `tdl -u https://t.me/c/123456/1 --template {{ .DialogID }}_{{ .MessageID }}/{{ .FileName }}`, a new folder named `123456_1` should be created (if it does not exist) and then the files will download into this folder.

It is useful when harvesting a large number of files as one could download files to nested folders instead of letting all files flood the same directory.

**Comment by iyear** [comment]
Accepted

**Comment by iyear** [comment]
The new version has been released, feel free to try it or reopen the issue.
