### ISSUE TITLE
How to solve `Key: 'Options.NS' Error:Field validation for 'NS' failed on the 'required' tag`

### ISSUE THREAD

**Issue by ztdf123** [iyear/tdl#116]
**Describe the bug**
Hi sir. It's 2023/2/23
When i try tdl for the first time，it did not work，i need your help.
![image](https://user-images.githubusercontent.com/44315256/220908887-179dab9a-0318-422a-92ea-2b2fe6f89df6.png)
Error info:
`Key: 'Options.NS' Error:Field validation for 'NS' failed on the 'required' tag`

**To Reproduce**
1. `tdl login -n kris -d "C:\Users\辰\AppData\Roaming\Telegram Desktop\tdata" `
![image](https://user-images.githubusercontent.com/44315256/220909112-19c33b31-7af9-4c60-b83f-c7fc2b16cc6d.png)
2.`tdl dl -u https://t.me/xxxx/345 --proxy socks5://localhost:7890 `
![image](https://user-images.githubusercontent.com/44315256/220908887-179dab9a-0318-422a-92ea-2b2fe6f89df6.png)

**Expected behavior**
It start downloading
**Version:**

Version: 0.7.2
Commit: a8db280
Date: 2023-02-18T06:35:42Z

Win10
go1.18.10 windows/amd64

**Additional context**

When i input 
`tdl --proxy socks5://localhost:7890`
It just show me the help info but nothing else, and i hope i did nothing wrong
![image](https://user-images.githubusercontent.com/44315256/220910876-857a8737-cf39-4444-8450-6ab8db69d37b.png)

Could you please help me?
Thanks a lot and wish you a good day!

**Comment by iyear** [comment]
> You should set the namespace when each command is executed

Try `tdl dl -n kris -u https://t.me/xxxx/345 --proxy socks5://localhost:7890`
