### ISSUE TITLE
[BUG] callback: invoke pool: rpcDoRequest: rpc error code 420: TAKEOUT_INIT_DELAY (83764)

### ISSUE THREAD

**Issue by kehunkun** [iyear/tdl#117]
**Describe the bug**
(callback: invoke pool: rpcDoRequest: rpc error code 420: TAKEOUT_INIT_DELAY (83764))

**To Reproduce**
Use“tdl dl -n kehunkun -u https://t.me/c/xxxx/xxxx --proxy socks5://localhost:1080”

**Screenshots**
![image](https://user-images.githubusercontent.com/126237274/221131963-c21605d4-022c-438f-b3aa-6f25f471c24e.png)

**Version:**
0.7.2

**Additional context**
Unable to download, hope to solve, thank you

**Comment by lyleaf-81** [comment]
![image](https://user-images.githubusercontent.com/63569552/221412477-b7f27268-6167-421c-8a02-0001e5d45ab5.png)
I also encountered this error

**Comment by milk245** [comment]
> **Describe the bug** (callback: invoke pool: rpcDoRequest: rpc error code 420: TAKEOUT_INIT_DELAY (83764))
> 
> **To Reproduce** Use“tdl dl -n kehunkun -u https://t.me/c/xxxx/xxxx --proxy socks5://localhost:1080”
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/126237274/221131963-c21605d4-022c-438f-b3aa-6f25f471c24e.png)
> 
> **Version:** 0.7.2
> 
> **Additional context** Unable to download, hope to solve, thank you

I'm in the same situation as you, look at the message under the verification code you received from telegram, click on allow at the bottom right corner of this message and you'll be fine
![图片](https://user-images.githubusercontent.com/112478745/221634655-4e79b8d5-1f9d-42b8-a5f3-fce35812348c.png)

**Comment by ZKBL** [comment]
I have also encountered this situation, look at the message under the verification code received by telegram, click on allow at the bottom right corner of this message and it will work

---

我也遇到了这种情况，看下 Telegram 收到的验证码下面有几条信息，点一下这个信息右下角的 allow 就可以了

---
![图片](https://user-images.githubusercontent.com/18417140/221636867-a94efd9a-17a8-4d77-986f-ef92f65c285e.png)

**Comment by kehunkun** [comment]
@ZKBL I didn't find that information, maybe it was deleted

**Comment by ZKBL** [comment]
> @ZKBL I didn't find that information, maybe it was deleted

You can delete the tdl data folder   _**~/.tdl**_  and try logging in again

**Comment by ragnorr** [comment]
thank you , it work!
use phone to check this msg allow.

![image](https://user-images.githubusercontent.com/69155337/230602824-afc32194-be6a-43e8-aefd-b48377330817.png)
