### ISSUE TITLE
callback: transfer: export to 201: export auth to 201: rpcDoRequest: rpc error code 400: DC_ID_INVALID

### ISSUE THREAD

**Issue by LimitBreaker01** [iyear/tdl#119]
callback: transfer: export to 201: export auth to 201: rpcDoRequest: rpc error code 400: DC_ID_INVALID

problem still exists
<img width="670" alt="2023-03-01_195734" src="https://user-images.githubusercontent.com/65392605/222133417-59f5c95c-7e0e-4fdf-826b-7599b33d3690.png">

**Comment by iyear** [comment]
duplicate with #106
