### ISSUE TITLE
[BUG] The system cannot find the file specified.

### ISSUE THREAD

**Issue by SenTomoHiro** [iyear/tdl#120]
OS:win10 x64 21H2
Telegram Ver:Official Desktop client 4.6.5 x64

First:
`PS C:\Users\xxx\Desktop\tdl> tdl login -n quickstart -d C:\Users\xxx\AppData\Roaming\
Namespace: quickstart
WARN: If data exists in the namespace, data will be overwritten
Importing session from desktop client: C:\Users\xxx\AppData\Roaming\
open key_data: file "key_data" not found`

Then:
`PS C:\Users\xxx\Desktop\tdl> tdl login -n quickstart -d C:\Users\xxx\AppData\Roaming\Telegram Desktop\tdata\
Namespace: quickstart
WARN: If data exists in the namespace, data will be overwritten
CreateFile C:\Users\xxx\AppData\Roaming\Telegram: The system cannot find the file specified.`

I also tried:
`PS C:\Users\chim\Desktop\tdl> tdl login -n quickstart -d C:\Users\xxx\AppData\Roaming\Telegram Desktop\tdata\key_datas
Namespace: quickstart
WARN: If data exists in the namespace, data will be overwritten
CreateFile C:\Users\xxx\AppData\Roaming\Telegram: The system cannot find the file specified.`

I do have a key_datas file in C:\Users\xxx\AppData\Roaming\Telegram Desktop\tdata\
What's wrong?Can somebody help me out.Thanks!

**Comment by iyear** [comment]
Try `-d "C:\Users\xxx\AppData\Roaming\Telegram Desktop"`

**Comment by SenTomoHiro** [comment]
> Try `-d "C:\Users\xxx\AppData\Roaming\Telegram Desktop"`

PS C:\Users\xxx\Desktop\tdl> tdl login -n quickstart -d C:\Users\xxx\AppData\Roaming\Telegram Desktop
Namespace: quickstart
WARN: If data exists in the namespace, data will be overwritten
CreateFile C:\Users\xxx\AppData\Roaming\Telegram: The system cannot find the file specified.

**Comment by SenTomoHiro** [comment]
But new problem happens:

PS C:\Windows\system32> cd C:\Users\xxx\Desktop\tdl
PS C:\Users\xxx\Desktop\tdl> tdl login -n xxx -d C:\Users\xxx\AppData\Roaming\Telegram
Namespace: xxx
WARN: If data exists in the namespace, data will be overwritten
Importing session from desktop client: C:\Users\xxx\AppData\Roaming\Telegram

? Choose a user id: xxx
Import xxx successfully to 'xxx' namespace!
PS C:\Users\xxx\Desktop\tdl> tdl -n xxx chat ls --debug
Namespace: xxx

It just stuck like this,nothing comes out(whether telegram client is running or not).

I tried other command such as :
tdl dl -n xxx -u https://t.me/xxx --skip-same --debug

Still stucks in 'Namespace: xxx',then nothing  comes out.

**Comment by iyear** [comment]
So try to set `--proxy socks5://host:port`

**Comment by SenTomoHiro** [comment]
> So try to set `--proxy socks5://host:port`

solved thank you
