### ISSUE TITLE
Feature request: Add support for bot account

### ISSUE THREAD

**Issue by AnjanaMadu** [iyear/tdl#124]
Add support for login with a bot account because Uluser accounts may be banned when downloading a lot

**Comment by suntong** [comment]
bot can only download files no bigger than 20M, due to [Telegram API limit](https://core.telegram.org/bots/api#getfile)

**Comment by AnjanaMadu** [comment]
> bot can only download files no bigger than 20M, due to [Telegram API limit](https://core.telegram.org/bots/api#getfile)

I said about MTProto API. not about BotAPI

**Comment by suntong** [comment]
Oh, ok. 

Is there any limit for bots with MTProto API then?

**Comment by AnjanaMadu** [comment]
> Oh, ok.
> 
> Is there any limit for bots with MTProto API then?

Nope

**Comment by iyear** [comment]
Interesting idea! Let me take the time to research it.

**Comment by iyear** [comment]
@AnjanaMadu Unfortunately, bot account is limited by MTProto, and most of the APIs cannot be called (Error: `BOT_METHOD_INVALID`)

**Comment by suntong** [comment]
> bot account is limited by MTProto

Exactly! That's what I thought. Unlimited is impossible.

**Comment by phanirithvij** [comment]
@iyear teldrive uses gotd/td as well and also downloads using bot accounts, maybe look into it as a reference?
