### ISSUE TITLE
The usage workflow?

### ISSUE THREAD

**Issue by suntong** [iyear/tdl#127]
how can i use it (#47)? 

Is it login only _once_, then do the download _many times_, or I have to login _each time_?

I'm running it from a remote server where there is no desktop client, just like #56, in which it is recommended to

> importing the official client session, to help reduce the risk of blocking

How can I do it? 

- what kind of official client session folder I should copy over to my remote server, and how to specify it using the command line please?

https://github.com/iyear/tdl/blob/0edfe5b3d930aaa4b9e6cdbe6a5494ca3b335f99/app/login/desktop.go#L42-L47

Name it "tdata" and use its parent as the `-d` parameter? thx!

Both my local machine and remote server are Debian/Ubuntu.

**Comment by iyear** [comment]
Login once and you can repeat the download.

For remote servers, you can use [Backup](https://github.com/iyear/tdl#backup) to move the local session.

For local session import, I haven't tested Linux. But I think the behavior of creating the tdata dir is consistent as long as the client is downloaded from https://desktop.telegram.org/. 

I'm considering adding some practices in the README.

**Comment by suntong** [comment]
Wow, thanks for the swift response! 

Ok. I'll give it a try and report back...

**Comment by suntong** [comment]
Yep, everything works as expected, just like a charm. Thanks.

> I'm considering adding some practices in the README.

Alright, feel free to close this now, or _later_ after README is updated. 

BTW, 
Telegram user data _under Linux_ is located in the `~/.local/share/TelegramDesktop/` directory.

**Comment by iyear** [comment]
Thanks for the feedback!
