### ISSUE TITLE
[Feat] 你好，有一个关于导出消息的问题请教

### ISSUE THREAD

**Issue by lyleaf-81** [iyear/tdl#128]
你好，能导出文字消息吗，我下载了一些文件，但是需要分类，需要能获取文字消息来进行分类，否则只能跑模型进行人脸相似检测分类，那样子花费时间有些长，想知道都方法能返回文字消息吗

**Comment by iyear** [comment]
在计划中，但是导出格式我还在考虑怎么做。

**Comment by lyleaf-81** [comment]
> 在计划中，但是导出格式我还在思考怎么办。

好的，感谢您的付出。
