### ISSUE TITLE
How to easily tell the (protected) chat message url

### ISSUE THREAD

**Issue by suntong** [iyear/tdl#129]
> Download (protected) chat files from message urls:  
>       `tdl dl -u https://t.me/tdl/1 -u https://t.me/tdl/2`

So how to get such (protected) chat message url like above? (I poked around in my own chats/groups but was never able to figure it out from the UI...) thx.

**Comment by iyear** [comment]
1. Export the history you need via `tdl chat export`. For more information:https://github.com/iyear/tdl/blob/master/docs/desktop_export.md
2. Use `tdl dl -f EXPORTED_FILE` to download the media.

But frankly, it's still a lot of work. I've thought about making a simple TUI to simply browse the history, but that would require research and time.

**Comment by suntong** [comment]
Hmm..., there should be a way to get how many (total) messages have been sent in a group/channel, right?

If so, output that number in `tdl chat ls`, then for the last message of a group/channel, we can construct the urls ourselves.

**Comment by suntong** [comment]
> I will add the max message id in the next version of `tdl chat export` as a temp solution.

Thanks, yeah, this is the easiest/quickest fix for a working solution, albeit not very elegant, as we still have to construct the urls ourselves. Or, 

Maybe add another cli sub-command instead, `getlast` or something, so that it'll output the last message url according to the `dl` format, based on the max message id. Else, just output it after each group/channel in `tdl chat ls` without introducing another cli sub-command.

That might be a more helpful solution.

**Comment by iyear** [comment]
The new version has been released, feel free to try it or reopen the issue.

**Comment by suntong** [comment]
> The new version has been released

How to use it pls?

This what I've tried so far:

```
$ tdl chat export -n ns --type last -c $mych 3
Namespace: ns
input data should be 1 integer when export type is last

$ tdl chat export -n ns --type last 3 -c $mych  
Namespace: ns
input data should be 1 integer when export type is last
```

**Comment by suntong** [comment]
So I tried it with one of my group and got this:

```
{"id":608310358,"messages":[{"id":678251,"type":"message","file":"0"},{"id":678250,"type":"message","file":"0"},{"id":678249,"type":"message","file":"0"},{"id":677922,"type":"message","file":"0"},{"id":677921,"type":"message","file":"0"}]}
```

So, 

- what's the last message url according to the dl format? Is it https://t.me/c/608310358/678251? Why TG says that I have no access to my own group from that url?
- why there is such a huge skipping in the message ids (over 320, from 678249 down to 677922)? I didn't delete any of the messages in that group.

To illustrate it, I got into a group that we both are in, and the last 15 message ids are:

```
{"id":1174669987,"messages":[{"id":39976,"type":"message","file":"0"},{"id":39974,"type":"message","file":"0"},{"id":39971,"type":"message","file":"0"},{"id":39966,"type":"message","file":"0"},{"id":39916,"type":"message","file":"0"},{"id":39905,"type":"message","file":"0"},{"id":39885,"type":"message","file":"0"},{"id":39884,"type":"message","file":"0"},{"id":39883,"type":"message","file":"0"},{"id":39882,"type":"message","file":"0"},{"id":39881,"type":"message","file":"0"},{"id":39876,"type":"message","file":"0"},{"id":39874,"type":"message","file":"0"},{"id":39873,"type":"message","file":"0"},{"id":39869,"type":"message","file":"0"}]}
```

As we can see a skip between 39976 and 39974, yet if I construct a message url of https://t.me/c/1174669987/39975, that url exist and message accessible. 

Moreover, the 39976 is not the last message id. There are still 3 more messages after it, as we speak.

Please double-check.

**Comment by iyear** [comment]
- `tdl export` only count messages that contains media, instead of all messages.
- `tdl export` should be used with `tdl dl -f`

So, workflow is
```shell
tdl export xxxxx -o export.json
tdl dl -f export.json
```

See README download section for details.
