### ISSUE TITLE
[BUG] tdl recover folder lost

### ISSUE THREAD

**Issue by suntong** [iyear/tdl#130]
**Describe the bug**
`tdl recover` will lose the `.tdl/log/` folder for the `latest.log` file.

**To Reproduce**

1. `tdl backup` first, then
1. `tdl recover` to an account without the `~/.tdl` folder
1.  `ls -l ~/.tdl`

**Expected behavior**

`latest.log` is under the `.tdl/log/` folder.

**Version:**

```
$ tdl version
Namespace: qs
Version: 0.7.2
Commit: a8db280
Date: 2023-02-18T06:35:42Z

go1.18.10 linux/amd64
```

**Comment by iyear** [comment]
The original purpose of backup and recover was to transfer `data.kv`, not logs. What's your opinion?

**Comment by suntong** [comment]
Yep, totally agree with the fix -- backup database only.
