### ISSUE TITLE
[Help needed] Can't download anything

### ISSUE THREAD

**Issue by salopelol** [iyear/tdl#131]
Please help me, I followed the tutorial and read this other issue in order to understand : https://github.com/iyear/tdl/issues/55

But I can't download anything, the command prompt just "freezes" after I enter the download command 
![Capture d’écran (480)](https://user-images.githubusercontent.com/80527089/225696501-48afc292-f641-4c47-afd6-63e30f62a280.png)

**Comment by jianala** [comment]
I have the some question.

![1](https://user-images.githubusercontent.com/38732716/225713768-d1aed6f9-8b49-421e-b539-6d041678f082.png)
![2](https://user-images.githubusercontent.com/38732716/225713781-6f58675a-6b45-48c4-b08e-06469493bdf2.png)
[tld.log](https://github.com/iyear/tdl/files/10994330/tld.log)

**Comment by iyear** [comment]
@salopelol Try input command with `--proxy` flag. For example: `tdl dl -n iyear -u xxx --proxy socks5://localhost:YOUR_PORT`

@jianala I checked logs, and it seems that your proxy chain was broken. Why there is a 54049 port?
> write tcp 127.0.0.1:54049->127.0.0.1:7890: wsasend: An established connection was aborted by the software in your host machine.

**Comment by salopelol** [comment]
@iyear I 
![Capture d’écran (481)](https://user-images.githubusercontent.com/80527089/225830683-7bc986bb-5713-4df5-9a1e-be3cbbe92e24.png)
I just did that but it's still the same.

I don't know hot to attach logs sorry

**Comment by iyear** [comment]
@salopelol 

> Q: No response after entering the command?
> 
> A: Check if you need to use a proxy (use proxy flag); Check if your system's local time is correct (use ntp flag or calibrate system time)
> 
> If that doesn't work, run again with debug flag. Then file a new issue and paste your log in the issue.

Logs are stored at `~/.tdl/log`

**Comment by jianala** [comment]
@iyear This time, I used NETSTAT command and proxy logging when running tdl.
I don't know why this is. `write tcp 127.0.0.1:54049->127.0.0.1:7890: wsasend: An established connection was aborted by the software in your host machine.` But everything worked fine when I used the proxy to access other pages and when I used the python with proxy to download something.
[netstat_ab_log.txt](https://github.com/iyear/tdl/files/11003955/netstat_ab_log.txt)
![telegram_proxy](https://user-images.githubusercontent.com/38732716/225971660-cd33702e-ed5e-49b4-a661-af3e66d47814.png)
[latest.log](https://github.com/iyear/tdl/files/11003956/latest.log)
![Clash_for_Windows_log](https://user-images.githubusercontent.com/38732716/225971674-f7c364be-befb-44e8-8cdd-459e01daeed7.png)

**Comment by jianala** [comment]
![Snipaste_2023-03-20_05-52-05](https://user-images.githubusercontent.com/38732716/226211893-877f2af8-22f0-4855-a71a-cd81f5e1a858.png)
我用python带着代理使用了telethon登录了一下，依旧是无法登录，不知道为什么，不太清楚登录的原理。请看看日志回复我解决方案，谢谢了。go语言不熟悉，所以看不太懂。

**Comment by jianala** [comment]
@salopelol @iyear My problem is solved myself.

**Comment by Authnt** [comment]
> @salopelol @iyear My problem is solved myself.-----------谷歌翻译-----------@salopelol @iyear 我的问题自己解决了。

how to solve this problem,i meet the same
