### ISSUE TITLE
[Feat] none mp4 video upload

### ISSUE THREAD

**Issue by suntong** [iyear/tdl#132]
I uploaded a `.mkv` video file. The upload is fine:

`... done! [189.67 MB in 2m4.154s; 1.53 MB/s]`

however, after that I got:

`callback: no h264 track found`

Seems it comes from here --
https://github.com/iyear/tdl/blob/c174aa8d8f81da6cf92266c373aec4ebee4534bd/pkg/uploader/uploader.go#L154-L157

Suggestion: if not a mp4 video, please don't fail the upload, but upload it as doc instead.

**Comment by iyear** [comment]
Thanks for the feedback. It will be fixed in next version.

**Comment by iyear** [comment]
The new version has been released, feel free to try it or reopen the issue.
