### ISSUE TITLE
[BUG] No such file or directory

### ISSUE THREAD

**Issue by xeye666** [iyear/tdl#133]
![image](https://user-images.githubusercontent.com/47184431/226155263-5e6ac580-4783-43e7-ba6a-b5963c9a99e6.png)
下载已经完成，但是上传显示找不到文件。

**Comment by jianala** [comment]
@xeye666  你这个路径就不对，你需要找你文件所在的真实路径 ，你所填写的是例子目录，不是你的目录。

**Comment by xeye666** [comment]
感谢，已解决。

**Comment by iyear** [comment]
Translated by DeepL: 

> You need to find the real path where your files are located, you are filling in the example directory, not your directory.
