### ISSUE TITLE
[BUG] Failed to upload

### ISSUE THREAD

**Issue by xeye666** [iyear/tdl#134]
![image](https://user-images.githubusercontent.com/47184431/226158294-85c569a7-bff2-4e46-b862-6b1f4b803bf4.png)

**Comment by jianala** [comment]
@xeye666  你上传的文件里是不是有文件名是空着的，错误报错是非法切片，应该是文件名的问题，不排除作者没考虑到空文件名报错问题。

**Comment by xeye666** [comment]
是的，我的文件是没有名字的。我改一个名字试一下

**Comment by xeye666** [comment]
> @xeye666 你上面传的文件里不是有文件名是空着的，错误报错是非法切片，应该是文件名的问题，不排除作者没有考虑空文件名报错。
![image](https://user-images.githubusercontent.com/47184431/226173257-7bf3853c-788c-4682-af49-b895c868cabd.png)
仍然不行，可以看到，我的文件夹只有这一个文件

**Comment by jianala** [comment]
@xeye666 你可以试着把日志贴出来~，等待作者解决

**Comment by iyear** [comment]
报错在go-mp4解析上，上游库的问题，我下个版本尝试修复一下

**Comment by xeye666** [comment]
> @xeye666你可以试着把日志贴出来~，等待作者解决

你们的不是这个显示的吗？

**Comment by iyear** [comment]
The new version has been released, feel free to try it or reopen the issue.
