### ISSUE TITLE
[BUG] Can't download with proxy

### ISSUE THREAD

**Issue by jianala** [iyear/tdl#136]
## 使用的命令
```tdl dl -n iyear -u https://t.me/xxxxx/21011 -e mp4,flv --proxy socks5://localhost:7890```
## 所用代理

Clash for Windows,端口号 7890

## 所用系统和路由

路由是openwrt(防火墙端口对本地主机全部开放)，系统是win11(防火墙已关),ipv4和ipv6均可用

## 与其相关
- 使用telegram_media_downloader/Python，可以通过代理正常下载telegram上的资料，但是是批量下载上传，用不上批量功能。
- telethon/python ，API无法登录
- 程序运行期间使用netstat -ab，记录如下
  
## 日志
[tdl_debug.txt](https://github.com/iyear/tdl/files/11015321/tdl_debug.txt)
[netstat_ab_log.txt](https://github.com/iyear/tdl/files/11015400/netstat_ab_log.txt)

## 截图

![Snipaste_2023-03-20_15-51-16](https://user-images.githubusercontent.com/38732716/226278011-df477e9e-57cd-4b98-ae58-be72b5391459.png)

![225976714-88a9aedf-410f-4d7f-86bf-22a25e848ff4](https://user-images.githubusercontent.com/38732716/226278591-6f3b8560-5c07-4064-821c-a779cc69a75d.png)

![Snipaste_2023-03-20_15-48-09](https://user-images.githubusercontent.com/38732716/226277371-cd462c97-dde3-4a02-b6ea-22059c0277d0.png)

**Comment by jianala** [comment]
@iyear 希望查看日志后给一个解决方案，谢谢了！

**Comment by iyear** [comment]
当前不支持http协议的代理，试试 socks5://localhost:7890。

**Comment by jianala** [comment]
@iyear  软件已经正常使用，关于代理的问题我已经解决，谢谢你的帮助。
