### ISSUE TITLE
failed: invoke pool: rpcDoRequest: unable to decode boxed value: unable to decode MessagesMessagesClass: unexpected id 0xc776ba4e

### ISSUE THREAD

**Issue by ragnorr** [iyear/tdl#137]
I let it run about 12hr,then it show "failed: invoke pool: rpcDoRequest: unable to decode boxed value: unable to decode MessagesMessagesClass: unexpected id 0xc776ba4e". 

![image](https://user-images.githubusercontent.com/69155337/228114922-faef336f-41f9-43fc-a0b8-b3f301e08a1d.png)

**Comment by ragnorr** [comment]
thank you sir

**Comment by ragnorr** [comment]
callback: get file: get next chunk: invoke pool: rpcDoRequest: retryUntilAck: retry limit reached after 10 attempts

![image](https://user-images.githubusercontent.com/69155337/229078884-7e9ddcfd-5654-48d0-a168-414e351cf485.png)

**Comment by iyear** [comment]
v0.8.0 has been released, feel free to try it or reopen the issue.
