### ISSUE TITLE
如何下载群组里一个视频  win的命令不会打

### ISSUE THREAD

**Issue by longjiank** [iyear/tdl#141]
tdl dl -u https://t.me/tdl/1
我把https://t.me/tdl/1换成群组链接
输出这个Key: 'Options.NS' Error:Field validation for 'NS' failed on the 'required' tag

**Comment by iyear** [comment]
Please see https://github.com/iyear/tdl#quick-start

**Comment by iyear** [comment]
You should login first, and use `tdl dl`.

You should specify namespace for each command, like quick start
