### ISSUE TITLE
[BUG] Key: 'Options.NS' Error:Field validation for 'NS' failed on the 'required' tag

### ISSUE THREAD

**Issue by cmdedj** [iyear/tdl#143]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version:**
Run `tdl version` in terminal

**Additional context**

**Comment by iyear** [comment]
Please see https://github.com/iyear/tdl#basic-configs

> You should set the namespace when each command is executed:

**Comment by cmdedj** [comment]
thank you very much

**Comment by cmdedj** [comment]
   ~/Dow/tdl_MacOS_arm64  sudo mv tdl /usr/bin            ✔  00:01:52 
Password:
mv: fastcopy: open() failed (to): /usr/bin/tdl: Operation not permitted
    ~/Dow/tdl_MacOS_arm64                                1 ✘  00:02:04 

and how can i fix it in mac

**Comment by iyear** [comment]
Place tdl under PATH, It does not have to be under /usr/bin
