### ISSUE TITLE
Download media files hanging

### ISSUE THREAD

**Issue by DaltonDom** [iyear/tdl#144]
Downloading media files (mp4,flv,etc.) from private channel getting hung up when trying to execute.
I have logged in properly and logs shows a reconnection issue.

![image](https://user-images.githubusercontent.com/23325119/229964220-35f3aeb8-d0ad-40c0-8468-3df2389de4b5.png)
![image](https://user-images.githubusercontent.com/23325119/229964345-89d7b0af-499d-4bce-8e0e-23c43bbf3096.png)

**Comment by iyear** [comment]
Please see https://github.com/iyear/tdl#faq

> Q: No response after entering the command?
> 
> A: Check if you need to use a proxy (use proxy flag); Check if your system's local time is correct (use ntp flag or calibrate system time)
> 
> If that doesn't work, run again with debug flag. Then file a new issue and paste your log in the issue.
