### ISSUE TITLE
[Feat] 能否添加配置文件

### ISSUE THREAD

**Issue by 7peanuts** [iyear/tdl#151]
能否像 yt-dlp 那样可以预先配置文件，这样不用每次都输入一堆参数

**Comment by iyear** [comment]
[Env](https://github.com/iyear/tdl#env) 设置常用配置能否满足需求?

**Comment by 7peanuts** [comment]
也可以，我用的次数不多。
只是觉得有配置文件，修改起来会更方便一些。
比如批量下载的时候，读取 txt 里输入的链接。

另外，环境变量的值该怎么填写，比如：
`TDL_PROXY`
--proxy socks5://localhost:1080
socks5://localhost:1080
都不起作用
![20230418133634](https://user-images.githubusercontent.com/82173614/232680940-81ef5a59-4bcb-46d4-98c7-4f465ce072a5.png)

**Comment by iyear** [comment]
Widnows的系统变量非立刻生效的，考虑重启机器或 https://learn.microsoft.com/zh-cn/powershell/module/microsoft.powershell.core/about/about_environment_variables?view=powershell-7.3

**Comment by 7peanuts** [comment]
> Widnows的系统变量非立刻生效的，考虑重启机器或 https://learn.microsoft.com/zh-cn/powershell/module/microsoft.powershell.core/about/about_environment_variables?view=powershell-7.3

感谢，哈哈，确实是，重新打开 CMD 就好了
