### ISSUE TITLE
[BUG] callback: invoke pool: rpcDoRequest: rpc error code 420: TAKEOUT_INIT_DELAY (86400)

### ISSUE THREAD

**Issue by miccall** [iyear/tdl#152]
**Describe the bug**
when using tdl dl commond 

Preparing DC pool... It may take a while. size: 3
callback: invoke pool: rpcDoRequest: rpc error code 420: TAKEOUT_INIT_DELAY (86400)

**Comment by iyear** [comment]
https://github.com/iyear/tdl/issues/117
