### ISSUE TITLE
[BUG] rpc error code 420: TAKEOUT_INIT_DELAY (85136)

### ISSUE THREAD

**Issue by 5Geng** [iyear/tdl#154]
**Describe the bug**
tdl version: 0.8.8
cmd: tdl dl -n xxx --proxy socks5://localhost:1086 -u address
result: callback: invoke pool: rpcDoRequest: rpc error code 420: TAKEOUT_INIT_DELAY (85494)

What's the solution？

**Comment by iyear** [comment]
https://github.com/iyear/tdl/issues/117
