### ISSUE TITLE
Print"All files will be downloaded to 'downloads' dir",but there's nothing downloaded

### ISSUE THREAD

**Issue by Kurumizz** [iyear/tdl#155]
Hello bro,when i use it to download the protected chat files
it's just printing  "All files will be downloaded to 'downloads' dir"
But there is no display of any download process.
And there's nothing in my 'downloads' dir.
How should I solve this problem? Thanks for your help。
![photo_2023-04-23_00-12-26](https://user-images.githubusercontent.com/131547137/233797376-928d2949-dc1e-4857-bca6-8f8dd70d6c4f.jpg)

**Comment by iyear** [comment]
What's your command?

**Comment by iyear** [comment]
What's the version of your second reply?

**Comment by iyear** [comment]
Is v0.8.2 fixes this problem?

**Comment by Kurumizz** [comment]
> Is v0.8.2 fixes this problem?


v0.8.2 didn't fix this problem.
_________________________________________________________________________________
**tdl chat export -c 1550781555 -n 59008030XX --proxy socks5://localhost:7890
1550781555              ...  [.........<#>......] [790 in 1m34.401s; 8/s]
group: task readLoop: read: read: read intermediate: read length: EOF

tdl version
Version: 0.8.2
Commit: 3d05daf
Date: 2023-04-26T01:50:39Z
go1.19.8 windows/amd64**

**Comment by iyear** [comment]
Try the v0.8.0? I can't ensure it's a bug or your network problem.

**Comment by iyear** [comment]
I guess it's your network problem

**Comment by Kurumizz** [comment]
> I guess it's your network problem

 I'll try it for a while, thanks bro.

**Comment by iyear** [comment]
Try v0.8.6 or v0.9.0. Solution thread in https://github.com/iyear/tdl/issues/158
