### ISSUE TITLE
[Question] callback: invoke pool: rpcDoRequest: rpc error code 420: TAKEOUT_INIT_DELAY (5597)

### ISSUE THREAD

**Issue by 5Geng** [iyear/tdl#157]
version: 0.8.0
cmd: tdl dl -n xxx --proxy socks5://localhost:1086 -u address
response: Preparing DC pool... It may take a while. size: 3
callback: invoke pool: rpcDoRequest: rpc error code 420: TAKEOUT_INIT_DELAY (5597)

What is this error？

**Comment by iyear** [comment]
https://github.com/iyear/tdl/issues/117
