### ISSUE TITLE
[BUG] when file name contains quotation marks stops throwing error

### ISSUE THREAD

**Issue by aliive10** [iyear/tdl#162]
When there are quotation marks in the file name download stops with error:

> callback: open downloads\1987_3988_Doctor_12"_Mix.mp3.tmp: The filename, directory name, or volume label syntax is incorrect.

**Comment by iyear** [comment]
Please see https://github.com/iyear/tdl/blob/master/docs/template.md

You can change default template by passing `--template` flag.
