### ISSUE TITLE
[BUG] callback: invoke pool: rpcDoRequest: rpc error code 420: TAKEOUT_INIT_DELAY (85763)

### ISSUE THREAD

**Issue by SagiriMiya** [iyear/tdl#171]
PS D:\tdl> tdl -n SagiriMiya dl -f .\tdl-export.json
Namespace: SagiriMiya
Preparing DC pool... It may take a while. size: 3
callback: invoke pool: rpcDoRequest: rpc error code 420: TAKEOUT_INIT_DELAY (85763)

**Comment by iyear** [comment]
What's your version

**Comment by Revdep** [comment]
same problem here:
 tdl version
Namespace: xxx
Version: 0.8.4
Commit: 1398f38
Date: 2023-05-05T13:52:37Z

go1.19.8 linux/arm64

**Comment by iyear** [comment]
t.me link is like `https://t.me/telegram/193`

**Comment by Revdep** [comment]
> t.me link is like `https://t.me/telegram/193`, you can get it from `Copy Link` on desktop client

ok, so i can't dowload all the files in a chat just calling https://t.me/telegram/* innit?
There is a way to do so?
