### ISSUE TITLE
[BUG] MacOS  ERROR : open key_data: file "key_data" not found

### ISSUE THREAD

**Issue by pun3ma** [iyear/tdl#172]
<img width="846" alt="截屏2023-05-07 14 13 04" src="https://user-images.githubusercontent.com/14088304/236660921-4238c546-9c4c-4363-91dc-c3cbf1fc7687.png">

请问下 如何解决

**Comment by iyear** [comment]
Do you use client: https://desktop.telegram.org/

macOS has two desktop client versions, but only one is supported.
