### ISSUE TITLE
[Feat] upload with --rm flag

### ISSUE THREAD

**Issue by pongfcnkl** [iyear/tdl#173]
https://github.com/iyear/tdl/issues/86
这个issues只实现了下载，上传好像没有对应的参数

如果很难实现，希望可以支持上传成功自动删除文件的参数，这样也能用系统自带的循环而不会重复上传。

**Comment by iyear** [comment]
Accepted

**Comment by iyear** [comment]
Please upgrade to v0.9.0 and try `tdl up --rm`

Feel free to reopen the issue if you have any questions.
