### ISSUE TITLE
上传：callback: send media: rpcDoRequest: rpc error code 403: CHAT_WRITE_FORBIDDEN

### ISSUE THREAD

**Issue by fomalhaut2017** [iyear/tdl#176]
大佬好！我每次尝试上传文件，上传进度条完了就会提示：callback: send media: rpcDoRequest: rpc error code 403: CHAT_WRITE_FORBIDDEN
不知道咋回事
请教

**Comment by iyear** [comment]
你对这个chat有上传权限吗？

**Comment by fomalhaut2017** [comment]
> 你对这个chat有上传权限吗？

我就是上传到我的收藏夹，按说应该肯定有权限吧

**Comment by iyear** [comment]
你的命令是什么？

**Comment by fomalhaut2017** [comment]
> 

.\tdl -n Sync up -p C:\Users\Lenovo\Downloads\2.tif -c CHAT_INPUT

Sync是我的账号名

**Comment by iyear** [comment]
去除 `-c CHAT_INPUT`，空的聊天即默认上传至收藏夹

**Comment by fomalhaut2017** [comment]
> 去除 `-c CHAT_INPUT`，空的聊天即默认上传至收藏夹

但是去除-c CHAT_INPUT后就会提示required flag(s) "chat" not set

**Comment by iyear** [comment]
尝试 v0.8.5 版本

**Comment by fomalhaut2017** [comment]
> 尝试 v0.8.5 版本

可以了，谢谢大佬耐心细致解答！
