### ISSUE TITLE
[Feat] Export chat based on topics

### ISSUE THREAD

**Issue by kirekr** [iyear/tdl#177]
Does tdl support exporting chat messages based on [topics](https://telegram.org/blog/topics-in-groups-collectible-usernames#topics-in-groups)? Currently I can only export messages by filtering content with regex, but it's not very efficient.

**Comment by iyear** [comment]
Accepted

**Comment by iyear** [comment]
Please upgrade to v0.9.0 and try `tdl chat export --topic TOPIC_ID`. See https://github.com/iyear/tdl#chat-utilities for details.

Feel free to reopen the issue if you have any questions.
