### ISSUE TITLE
[Feat] chat ls给出的列表中能否加上URL？

### ISSUE THREAD

**Issue by guanyubin** [iyear/tdl#178]
Please describe your feature request
目前只有ID，Title和Type吗？

**Comment by iyear** [comment]
请问URL的用途是？感觉用不太到。

**Comment by guanyubin** [comment]
我想把列表分享非别人，然后他可以选择需要的频道关注，我不知道如何通过ID和Title关注一个频道

**Comment by iyear** [comment]
频道链接并不是固定的，部分私密频道的链接只有管理员才能获取。
