### ISSUE TITLE
[BUG] callback: open E:\1641806241_#1552_FILE 2562-02-07 10:39:31.mp4.tmp: The filename, directory name, or volume label syntax is incorrect.

### ISSUE THREAD

**Issue by 7peanuts** [iyear/tdl#183]
打扰了，我通过导出 .json 消息列表进行下载，遇到了两条消息报错，重新单独下载也是报错。
于是我打算找到这两条消息，试试能不能通过链接直接下载，但由于消息太多，不知道如何定位，或者有没有办法能够直接指定消息 ID 进行下载？

**Describe the bug**
`callback: open E:\1641806241_#1552_FILE 2562-02-07 10:39:31.mp4.tmp: The filename, directory name, or volume label syntax is incorrect.`
![20230522113325](https://github.com/iyear/tdl/assets/82173614/96438afd-17ff-435f-a9dd-0b60ce90dc6b)

我的下载命令
`tdl dl -f E:\***.json -d "E:\DLVideos" --rewrite-ext --skip-same -e gz --takeout`

**Version:**
v0.8.6

**Comment by iyear** [comment]
下载模板是默认的吗？

**Comment by 7peanuts** [comment]
> 下载模板是默认的吗？
我更改了命名模板
`#{{ .DialogID }}_{{ .MessageDate }}_#{{ .MessageID }}_{{ .FileName }}`
![20230522113725](https://github.com/iyear/tdl/assets/82173614/eef22392-9c8a-42a8-aa81-d2ab7afb0623)

**Comment by iyear** [comment]
默认模板对`FileName` 在Windows平台的非法字符进行了过滤，你也需要做一些过滤行为。

默认模板：
```
{{ .DialogID }}_{{ .MessageID }}_{{ replace .FileName `/` `_` `\` `_` `:` `_` `*` `_` `?` `_` `<` `_` `>` `_` `|` `_` ` ` `_`  }}
```

**Comment by 7peanuts** [comment]
> 默认模板对`FileName` 在Windows平台的非法字符进行了过滤，你也需要做一些过滤行为。
> 
> 默认模板：
> 
> ```
> {{ .DialogID }}_{{ .MessageID }}_{{ replace .FileName `/` `_` `\` `_` `:` `_` `*` `_` `?` `_` `<` `_` `>` `_` `|` `_` ` ` `_`  }}
> ```
哦哦，明白了，这两条消息文件名里有非法字符，所以我需要把 `replace.FileName` 添加到模版里是吧

**Comment by iyear** [comment]
是的

**Comment by iyear** [comment]
Answer in English:

The default template filters `FileName` for illegal characters on the Windows platform, and you need to do some filtering behavior as well.

Default template:
```
{{ .DialogID }}_{{ .MessageID }}_{{ replace .FileName `/` `_` `\` `_` `:` `_` `*` `_` `?` `_` `<` `_` `>` `_` `|` `_` ` ` `_`  }}
```

Reference: https://github.com/iyear/tdl/blob/master/docs/template.md
