### ISSUE TITLE
[BUG] After resuming downloads with '--skip-same', there are still duplicate downloads

### ISSUE THREAD

**Issue by 7peanuts** [iyear/tdl#185]
**Describe the bug**
我通过导出消息 `.json` 文件来下载，并使用 `--skip-same` 来跳过已下载文件。
当下载中断后，使用 `--continue` 恢复下载时，有些文件会重复下载，目前遇到重复下载的都是视频文件，图片暂时没有遇到重复下载。
经过测试，多次从同一个消息 `.json` 文件下载，也会有部分视频重复下载。

这些重复下载的文件，我看了下文件名的末尾，会带有一个下载时间戳，但是我的命名模版末尾并没有这个时间戳，如下图：

![1](https://user-images.githubusercontent.com/82173614/239973913-4341e9f5-8d98-42be-bedd-6c6f4ab09983.png)
![2](https://user-images.githubusercontent.com/82173614/239974777-f5f4bca0-8ee5-49d5-ae1c-2eaa4ff6570c.png)

这是我的命名模版：
{{ .MessageDate }}_#{{ .DialogID }}_#{{ .MessageID }}_{{ replace .FileName / _ ` _ : _ * _ ? _ < _ > _ | _   _ }}`

**Version:**
v0.8.6

**Comment by iyear** [comment]
Please upgrade to v0.9.0 and feel free to reopen the issue if you have any questions.

**Comment by 7peanuts** [comment]
> Please upgrade to v0.9.0 and feel free to reopen the issue if you have any questions.

非常感谢，v0.9.0 不会重复下载视频文件了。
不过，新版本的图片命名方式和之前的不一样，源文件名变成了一串数字，如下图：
![20230524115153](https://github.com/iyear/tdl/assets/82173614/ea4c8626-5d31-422c-8843-38f31a7a409f)

另外再问一下，读取 `.json` 文件下载时，是否会有遗漏？
因为我发现，有时候中断后重新恢复下载，会下载之前没有下载到的文件，是不是因为这些文件比较大，所以没有及时下载到？
![20230524115815](https://github.com/iyear/tdl/assets/82173614/ed002247-0187-4b66-9d60-29cc277f19ca)

**Comment by 7peanuts** [comment]
> 非常感谢，v0.9.0 不会重复下载视频文件了。

好像仍然有重复下载，会覆盖之前的下载文件。
如图，重启 cmd 或重新输入下载命令后，极少数视频文件被重复下载
![20230524132406](https://github.com/iyear/tdl/assets/82173614/0110a696-75a7-46ad-901a-51aaf202e633)

**Comment by iyear** [comment]
两次的命令是相同的吗？

**Comment by 7peanuts** [comment]
> 两次的命令是相同的吗？

加不加 `--continue` 结果都是一样的，都会从相同的文件开始下载，并覆盖之前下载过的。
但如果有下载完成度不到 100% 的文件，则会先从这个未完成的任务开始。
`tdl dl -f E:\***.json -d "E:\DLVideos" --rewrite-ext --skip-same --continue`

**Comment by iyear** [comment]
本地复现不了。下载一遍后再次使用相同命令则跳过所有已下载的文件。

**Comment by 7peanuts** [comment]
> 本地复现不了。下载一遍后再次使用相同命令则跳过所有已下载的文件，`--skip-name` 基于去除扩展名的文件名、文件大小对比。

是不是与网络质量有关？我这只有视频和 `.gz` 压缩文件（可能是贴纸？）才会重复下载。
并且如果有下载完成度不到 100% 的文件，则不会重复下载，而是会先从这个未完成的任务开始继续下载。

我找了个频道测试：https://t.me/joinchat/AAAAAD-tO7GPvfOU131_vg
导出了最后 100 条消息，下面附件是导出的 `KidProject.json` 文件
[KidProject last 100 messages.zip](https://github.com/iyear/tdl/files/11561836/KidProject.last.100.messages.zip)

然后进行下载，从下面测试图中可以看到，在下载完全部 100 个文件之后，再次启动下载还会重新下载 5 个文件。
这是导出的 cmd 文本 [cmd text.txt](https://github.com/iyear/tdl/files/11561987/cmd.text.txt)
<img src="https://github.com/iyear/tdl/assets/82173614/20a22e4e-3241-4c40-b162-e6b45024dfb92" height=800 >

这是我的环境变量配置：
![env](https://github.com/iyear/tdl/assets/82173614/0bc629ce-585c-42c3-a16c-de8925697a6d)

**Comment by iyear** [comment]
网络问题导致下载其实并不完全成功，设置 `--reconnect-timeout 0`解决网络较差情况下 EOF 问题

**Comment by 7peanuts** [comment]
> 网络问题导致后面几个下载断了，设置 `--reconnect-timeout 0` 解决网络较差情况下 EOF 问题。看来这个参数默认值还是要改大点:P

啊，好像没问题了，这次不会重复下载了 🥳
![20230525152253](https://github.com/iyear/tdl/assets/82173614/a6f9dd23-eb71-42fa-84c0-c1ac57ff4248)
