### ISSUE TITLE
Why cna't I donwload pixelated media?

### ISSUE THREAD

**Issue by SenTomoHiro** [iyear/tdl#191]
I find some pixelated (I mean 'Telegram New Feature to Help Avoid Spoilers in Chats' thing) media at a group,and i want to download them,
No matter I use 
tdl -n xxx chat export -c xxxxxxx , tdl -n xxx dl -f tdl-export.json
 or 
tdl -n xxx dl -u https://t.me/c/xxxxxxx/xxx
, I can't download it.
How can I download them? Or the function doesn't exist at all?

**Comment by iyear** [comment]
Can you give a example message which can be accessed publicly?

**Comment by SenTomoHiro** [comment]
https://t.me/QuanXApp/4047072
I tried this, a pixelated video in a public group, same result.

PS C:\Users\xxx\Desktop\tdl> tdl -n xxx dl -u https://t.me/QuanXApp/4047072 -t 4 --skip-same
Namespace: xxx
DC pool prepared in 4.726392s
All files will be downloaded to 'downloads' dir
PS C:\Users\xxx\Desktop\tdl>

**Comment by iyear** [comment]
My command: `tdl dl -u https://t.me/QuanXApp/4047072`

And it's successful:

```
All files will be downloaded to '.tdl/downloads' dir
1245587517_4047072_IMG_3197.MP4     ... done! [4.42 MB in 2.141s; 1.98 MB/s]
```

I see you use `--skip-same` flag/ Maybe the file has been downloaded in dir, so it's skipped.

**Comment by SenTomoHiro** [comment]
> My command: `tdl dl -u https://t.me/QuanXApp/4047072`
> 
> And it's successful:
> 
> ```
> All files will be downloaded to '.tdl/downloads' dir
> 1245587517_4047072_IMG_3197.MP4     ... done! [4.42 MB in 2.141s; 1.98 MB/s]
> ```
> 
> I see you use `--skip-same` flag. Maybe the file has been downloaded in dir, so it's skipped.

PS C:\Users\xxx\Desktop\tdl> tdl -n xxx dl -u https://t.me/QuanXApp/4047072 -t 4
Namespace: xxx
DC pool prepared in 5.0826268s
All files will be downloaded to 'downloads' dir
PS C:\Users\xxx\Desktop\tdl>

Same thing happens,It just downloaded nothing

**Comment by iyear** [comment]
Still can't reproduce. Have you set any env?

**Comment by SenTomoHiro** [comment]
> Still can't reproduce. Have you set any env?

Does it matter with Parallels Desktop? My windows 10 is running in Parallels Desktop in an iMac.

**Comment by iyear** [comment]
I think it's doesn't matter:P

**Comment by SenTomoHiro** [comment]
> I think it doesn't matter:P

How about socks5?
--proxy socks5://127.0.0.1:10808

**Comment by iyear** [comment]
If DC pool has prepared, it's not network problem.

**Comment by iyear** [comment]
Or try v0.9.0? But I think it's not the key.

**Comment by SenTomoHiro** [comment]
> Or try v0.9.0? But I think it's not the key.

I'm using 0.9.0 now

**Comment by iyear** [comment]
emm, maybe you can try it. Or use `--debug` to print debug logs and paste in the issue.

**Comment by SenTomoHiro** [comment]
> emm, maybe you can try it. Or use `--debug` to print debug logs and paste in the issue.

`PS C:\Users\xxx\Desktop\tdl> tdl -n xxx dl -u https://t.me/QuanXApp/4047072 -t 4 --skip-same --proxy socks5://127.0.0.1:10808 --debug
Namespace: xxx
DC pool prepared in 5.6090981s
All files will be downloaded to 'downloads' dir
PS C:\Users\xxx\Desktop\tdl> tdl -n xxx dl -u https://t.me/QuanXApp/4047072 -t 4 --proxy socks5://127.0.0.1:10808 --debug
Namespace: xxx
DC pool prepared in 4.866018s
All files will be downloaded to 'downloads' dir
PS C:\Users\xxx\Desktop\tdl>`
Nothing different...Even no debug info.

**Comment by iyear** [comment]
log file is stored in ~/.tdl/log

**Comment by iyear** [comment]
And ensure your version is v0.9.0 with command `tdl version`. Your output seems is not v0.9.0

**Comment by SenTomoHiro** [comment]
> And ensure your version is v0.9.0 with command `tdl version`. Your output seems is not v0.9.0

it's weird, I just downloaded https://github.com/iyear/tdl/releases/download/v0.9.0/tdl_Windows_64bit.zip
But in the end, it's:

tdl version
Version: 0.7.2
Commit: a8db280
Date: 2023-02-18T06:35:42Z

go1.18.10 windows/amd64

**Comment by iyear** [comment]
`$Script=iwr -useb https://ghproxy.com/https://raw.githubusercontent.com/iyear/tdl/master/scripts/install.ps1; $Block=[ScriptBlock]::Create($Script); Invoke-Command -ScriptBlock $Block -ArgumentList "", "$True"`

Use command to upgrade your tdl in PATH

**Comment by SenTomoHiro** [comment]
> $Script=iwr -useb https://ghproxy.com/https://raw.githubusercontent.com/iyear/tdl/master/scripts/install.ps1; $Block=[ScriptBlock]::Create($Script); Invoke-Command -ScriptBlock $Block -ArgumentList "", "$True"

It's really weird,OMG!

PS C:\tdl> tdl version
Version: 0.7.2
Commit: a8db280
Date: 2023-02-18T06:35:42Z

go1.18.10 windows/amd64

![1](https://github.com/iyear/tdl/assets/16866452/604306a0-4a20-42af-9705-e5027ebe5323)

I'm 100% sure,I get the right file and the right path

**Comment by iyear** [comment]
You have a v0.7.2 tdl in PATH, if you want to execute tdl in current dir, you should use `.\tdl.exe xx`

**Comment by SenTomoHiro** [comment]
> You have a v0.7.2 tdl in PATH, if you want to execute tdl in current dir, you should use `.\tdl.exe xx`

Thank you! problem solved, the reason is an old version! and I didn't use the right command to run the right version.

**Comment by SenTomoHiro** [comment]
> You have a v0.7.2 tdl in PATH, if you want to execute tdl in current dir, you should use `.\tdl.exe xx`

BTW,where is the PATH exactly?I want to find it out and delete the old version :D

**Comment by iyear** [comment]
Run `Get-Command tdl` in Powershell

**Comment by SenTomoHiro** [comment]
> Run `Get-Command tdl` in Powershell

Thank you, you are very patient, I aprriciate that.

Unfortunately I got a new problem:

Download aborted.
group: task readLoop: read: read: read intermediate: read length: EOF

This happens every 20 times of downloading.

**Comment by iyear** [comment]
Try set `--reconnect=timeout 0` flag

**Comment by SenTomoHiro** [comment]
> Try set `--reconnect-timeout 0` flag

Let me thank you again, another problem solved, you are an excllent developer!
