### ISSUE TITLE
[BUG] 系统为macos 13.4版本，使用脚本安装报错

### ISSUE THREAD

**Issue by GHubgenius** [iyear/tdl#192]
0x00系统为macos 13.4版本，使用脚本安装报错误。
# Install latest version
curl -sSL https://ghproxy.com/https://raw.githubusercontent.com/iyear/tdl/master/scripts/install.sh | sudo bash

0x01脚本执行到rename tdl的时候提示没有这个文件或目录。
执行命令：
aa@aa/ % curl -sSL https://ghproxy.com/https://raw.githubusercontent.com/iyear/tdl/master/scripts/install.sh | sudo bash
错误信息：
Target version: v0.9.0
Downloading tdl from https://github.com/iyear/tdl/releases/download/v0.9.0/tdl_MacOS_64bit.tar.gz
mv: rename tdl to /usr/local/bin/tdl: No such file or directory

0x02手动创建了 /usr/local/bin/tdl后，再执行依然到这一步报错。
信息如下：
Target version: v0.9.0
Downloading tdl from https://github.com/iyear/tdl/releases/download/v0.9.0/tdl_MacOS_64bit.tar.gz
mv: rename tdl to /usr/local/bin/tdl/tdl: No such file or directory

**Comment by iyear** [comment]
Can anyone who has Mac help improve shell sceipt? Thanks!

**Comment by murphysking** [comment]
我这里Macos 10.15没问题，可能是文件下载失败。可以挂代理或者加上`--proxy`参数

<img width="1441" alt="iShot2023-08-07 18 09 12" src="https://github.com/iyear/tdl/assets/22335334/a255ffda-5283-406d-996d-415ad1625cd8">

**Comment by SaulLockYip** [comment]
在terminal里进入到/usr/local/bin的目录下再执行就可以了
