### ISSUE TITLE
[BUG] replace .FileName not working as expected 

### ISSUE THREAD

**Issue by jxmesth** [iyear/tdl#193]
**Describe the bug**
'replace .FileName' not working as expected.

**To Reproduce**
When using the template, using 'replace .FileName' does not accurately replace the filename.

**Expected behavior**
The filename should be replaced.

**Screenshots**
Screenshots contain private info but here's the output:

> C:\Users\user\Downloads\tdl_Windows_64bit>
tdl -n user download -f tdl-export.json -d "C:\Users\user\Download-test" --template "{{ formatDate .MessageDate }}_{{ replace .FileName `/` `_` `\` `_` `:` `_` `*` `_` `?` `_` `<` `_` `>` `_` `|` `_`  }}"

>All files will be downloaded to 'C:\Users\user\Downloads\Download-test' dir
CPU: 0.00% Memory: 23.77 MB Goroutines: 22
2023-04-03 10:46:54_ffff.mp4        ...  0.0% [..................] [0 B in 129ms; 0 B/s]
[................................................................] [0s]
callback: open C:\Users\user\Downloads\Download-test\2023-04-03 10:46:54_ffff.mp4.tmp: The filename, directory name, or volume label syntax is incorrect.

**Version:**
Version: 0.9.0
Commit: 3be32ed

**Comment by iyear** [comment]
You should also replace the special characters in the result of formatDate

**Comment by iyear** [comment]
I consider that it's a bug, and I will change the format of `formatDate`. The filename doesn't work on the most platforms.

**Comment by jxmesth** [comment]
@iyear thanks for the amazing work. Do you have an estimate on how long this should take?
I'm trying to download a few channels before they close.

**Comment by jxmesth** [comment]
@iyear I can see that anew version was released. Does it contain the fix for this issue?

**Comment by iyear** [comment]
Sorry, I was a bit busy a while ago, I'll implement it in the next version

**Comment by iyear** [comment]
Please upgrade to v0.9.5 and feel free to reopen the issue if you have any questions.
