### ISSUE TITLE
Options.NS' Error:Field validation for 'NS' failed  on `window`

### ISSUE THREAD

**Issue by NormTurtle** [iyear/tdl#194]
**Describe the bug**
on window Tdl can't be used can't be login at my side :( 
![image](https://github.com/iyear/tdl/assets/108952834/be5e4421-51d8-4a54-9fce-8bb69771cb4b)

**To Reproduce**
download https://github.com/iyear/tdl/releases/download/v0.9.0/tdl_Windows_64bit.zip then use it 

`.\tdl.exe login --code`
**Expected behavior**
as workas expected 
**Screenshots**
![image](https://github.com/iyear/tdl/assets/108952834/8f8c71e0-a2b4-4ed5-b625-82389a23a73d)

**Version:**
Version: 0.9.0
Commit: 3be32ed
Date: 2023-05-24T02:40:20Z

go1.19.9 windows/amd64

**Comment by NormTurtle** [comment]
even if i manged to get login via `--code``
this thing bugs me
![image](https://github.com/iyear/tdl/assets/108952834/123ed298-88d5-4252-84f3-cc2f9be7e0a6)

**Comment by NormTurtle** [comment]
![image](https://github.com/iyear/tdl/assets/108952834/9112ebd9-9526-4922-978d-c5c4009627fc)

okay so app is fully `BUG` on window

**Comment by iyear** [comment]
https://github.com/iyear/tdl/issues/143

**Comment by NormTurtle** [comment]
@iyear 
![image](https://github.com/iyear/tdl/assets/108952834/c6d05b19-2791-40ca-a4a7-572d03f48f4a)
can i have some guide how to use it , the README things are making me so much confused , im dabbling more than a hour in readme got nothign then just erros 😢

**Comment by iyear** [comment]
Use latest version and try again.
