### ISSUE TITLE
[Feat]  export/import message to another chat

### ISSUE THREAD

**Issue by kuhytitusdlz** [iyear/tdl#196]
Hi there, thanks for this excellent tool! It's possible to add "chat import" function, to import message content to another chat (with save history to avoid duplicate message on next import)?
And, it would be grate, if export/import support save media content in json, as base64-encoded variable.

**Comment by iyear** [comment]
Thanks for your positive feedback! Do you mean https://github.com/iyear/tdl/issues/8? It's a bit difficult to impl it currently. But I will try it.

**Comment by kuhytitusdlz** [comment]
yes, the goal is to implement a forwarder with time loop to check new message, or even with EventHandler for new message.
Can you say which IDE you using for Go in this project?

**Comment by kuhytitusdlz** [comment]
Hi @iyear ,

thanks for `chat export`/`forwad --mode clone` options. It's useful for this issue, but is it possible to add an option not to download/upload already downloaded/uploaded messages?
