### ISSUE TITLE
[Feat] Search!

### ISSUE THREAD

**Issue by suntong** [iyear/tdl#197]
Please consider adding the search feature, and only count messages that contains media, just like the [export](https://github.com/iyear/tdl/issues/129#issuecomment-1482139009).

So that we can download the same KW (say the name of a TV series)  in one shot. thx.

**Comment by suntong** [comment]
Hmm, found this https://github.com/iyear/tdl/commit/f0004b0872bb54328dc945bdd5f4bfccd99532cc, but how to use it pls?

**Comment by iyear** [comment]
regex filter has been deprecated. Try v0.9.0 and use expr engine to filter media messages. https://github.com/iyear/tdl#chat-utilities

**Comment by suntong** [comment]
> Try v0.9.0 and use expr engine to filter media messages. https://github.com/iyear/tdl#chat-utilities

Would you give an example how to search on `Topics[].Title: string # Title of topic` please?

I've checked https://expr.medv.io/docs/Language-Definition, but am still not sure. thx.

**Comment by iyear** [comment]
Try `"count(Topics, .Title contains 'mp4')>0"`

**Comment by suntong** [comment]
```
$ tdl chat ls -f "count(Topics, .Title contains 'mp4')>0"
ID         Type     VisibleName          Username             Topics
```

> adding the search feature, and only count messages that contains media, 

The goal of this ticket is to search for a keyword, say `MyTVSeries`, and

> So that we can download the same KW (say the name of a TV series) in one shot.

download the whole `MyTVSeries`  TV Series mp4 files in one shot.

just like how the [export](https://github.com/iyear/tdl/issues/129#issuecomment-1482139009) is doing.

However, I don't think the new `-f` feature allows us to do it --

```sh
$ tdl chat ls -f "Type contains 'channel' && VisibleName contains 'Saved' && Topics, .Title contains 'mp4'"
failed to compile filter: unexpected token Operator(",") (1:66)
 | Type contains 'channel' && VisibleName contains 'Saved' && Topics, .Title contains 'mp4'
 | .................................................................^

$ tdl chat ls -f "Type contains 'channel' && VisibleName contains 'Saved' && .Title contains 'mp4'"
failed to compile filter: cannot use pointer accessor outside closure (1:60)
 | Type contains 'channel' && VisibleName contains 'Saved' && .Title contains 'mp4'
 | ...........................................................^

$ tdl chat ls -f "Type contains 'channel' && VisibleName contains 'Saved' && Topics.Title contains mp4"
callback: failed to run filter: invalid operation: int(Title) (1:67)
 | Type contains 'channel' && VisibleName contains 'Saved' && Topics.Title contains mp4
 | ..................................................................^
```

**Comment by iyear** [comment]
You mean export some specific messages in all media messages in all dialogs?

**Comment by suntong** [comment]
OK, 

suppose I posted/found a series of media files having a common keyword, the typical case is a post of a TV Series media files, of which all have a common keyword, say `MyTVSeries`.

The ticket is about finding all ID (via the search feature) of such media files, and export them so that they can be downloaded together with a single download command.

**Comment by iyear** [comment]
So the media files are distributed in different dialogs?

**Comment by suntong** [comment]
Oh, no, _in the same channel or group_, forgot to stress that. Updated above.

**Comment by iyear** [comment]
So why not use `tdl chat export -f "Views>200 && Media.Name endsWith '.zip' && Media.Size > 5*1024*1024"`?
