### ISSUE TITLE
[BUG] To easily copy the name of uploaded file

### ISSUE THREAD

**Issue by suntong** [iyear/tdl#198]
**Describe the bug**
A clear and concise description of what the bug is -- In TD on Android, if I long click a [tdl](https://github.com/iyear/tdl) uploaded media file, and do a copy, I will only get `video/mp4`. It is only when I select the whole media file, then use the TD's copy, am I able to get the name, but this time it is everything, i.e.:

`My.mp4 - video/mp4`

**Expected behavior**

It would be better than when I right click an uploaded media file, and do a copy, I will only get the actual name, `My.mp4`, instead of the not-that-useful `video/mp4`. 

**Version:**
Run `tdl version` in terminal

```
$ tdl version
Version: 0.7.3
Commit: 88f4592
Date: 2023-03-22T02:28:40Z
```

**Comment by iyear** [comment]
Accpeted

**Comment by iyear** [comment]
<img width="254" alt="image" src="https://github.com/iyear/tdl/assets/61452000/de4090b5-2a9f-4c4d-8b80-4f1b3a897152">

But that's how it's done at the moment, am I misunderstanding the issue?

**Comment by suntong** [comment]
My bad, I copied the wrong part.
