### ISSUE TITLE
The video file uploaded using the tdl tool does not display a preview image in the Telegram channel. [Feat] 

### ISSUE THREAD

**Issue by jianchao123** [iyear/tdl#206]
The video file uploaded using the tdl tool does not display a preview image in the Telegram channel. Is there a solution?

**Comment by runningdown** [comment]
I use ffmpeg to generate a .thubmb thumbnail file with the same name, and you can preview it. The author wrote this function in the code, but it is not reflected in the document.

我使用ffmpeg生成同名的.thubmb缩略图文件，就可以预览了，在代码中作者写了这个功能，只不过没在文档中体现

**Comment by lloyd18** [comment]
> I use ffmpeg to generate a .thubmb thumbnail file with the same name, and you can preview it. The author wrote this function in the code, but it is not reflected in the document.
> 
> 我使用ffmpeg生成同名的.thubmb缩略图文件，就可以预览了，在代码中作者写了这个功能，只不过没在文档中体现

怎么用啊，大佬
