### ISSUE TITLE
[BUG] 单个文件下载失败时不会断点续传

### ISSUE THREAD

**Issue by WindyCloudCute** [iyear/tdl#212]
**Describe the bug**
当网络连接不稳定时,下载大文件会导致中断.

**To Reproduce**
Steps to reproduce the behavior: 网络不稳定时皆可复现

**Expected behavior**
应该允许断点续传或者下载失败时候重新下载整个文件.

**Screenshots**

**Version:**
Version: 0.9.1
Commit: defb372
Date: 2023-05-31T13:39:17Z

go1.19.9 windows/amd64

**Additional context**

**Comment by iyear** [comment]
目前并没有做到文件粒度的断点续传，后续版本可将文件以http形式向外暴露，使用更优秀的外部下载器实现下载特性
