### ISSUE TITLE
Key: 'Options.NS' Error:Field validation for 'NS' failed on the 'required' tag

### ISSUE THREAD

**Issue by sheshuiyu** [iyear/tdl#217]
why i can't login
what does error message mean

![屏幕截图(2)](https://github.com/iyear/tdl/assets/40339566/9e6b5bc8-72d0-4cc3-87c4-ea4d5c268b39)
_Key: 'Options.NS' Error:Field validation for 'NS' failed on the 'required' tag_

**Comment by iyear** [comment]
https://github.com/iyear/tdl/issues/143
