### ISSUE TITLE
[Feat] 视频类型不支持预览

### ISSUE THREAD

**Issue by jiemo9527** [iyear/tdl#221]
视频类型应该支持预览，而不是以文件格式发送

**Comment by iyear** [comment]
你的视频是什么格式？目前只有mp4被Telegram支持预览

**Comment by jiemo9527** [comment]
就是mp4

**Comment by lloyd18** [comment]
same question / 同样的问题

![Screenshot_2023-07-15_23-05-07](https://github.com/iyear/tdl/assets/10294460/26400893-b451-4878-bf2f-47e7dd05085c)

**Comment by iyear** [comment]
能否提供可复现的视频文件？

**Comment by iyear** [comment]
Please upgrade to v0.9.5 and feel free to reopen the issue if you have any questions.
