### ISSUE TITLE
[BUG] Error: msg_id too high

### ISSUE THREAD

**Issue by suntong** [iyear/tdl#224]
**Describe the bug**

I'm getting the error of `group: task userCallback: initConnection: invoke: rpcDoRequest: msg_id too high` for every operation after upgrading to the latest version.

**To Reproduce**

```
$ tdl dl --debug -u https://t.me/c/19xxx29/218
group: task userCallback: initConnection: invoke: rpcDoRequest: msg_id too high
```

**Version:**
Run `tdl version` in terminal

```
$ tdl version
Version: 0.9.2
Commit: c60880f
Date: 2023-06-10T14:45:36Z

go1.19.9 linux/amd64
```

**Comment by iyear** [comment]
https://github.com/iyear/tdl#troubleshooting

> Q: Why no response after entering the command? And why there is 'msg_id too high' in the log?
> 
> A: Check if you need to use a proxy (use proxy flag); Check if your system's local time is correct (use ntp flag or calibrate system time)
> 
> If that doesn't work, run again with --debug flag. Then file a new issue and paste your log in the issue.
