### ISSUE TITLE
[BUG] Error: msg_id too high

### ISSUE THREAD

**Issue by suntong** [iyear/tdl#227]
**Describe the bug**

I'm getting the error of `group: task userCallback: initConnection: invoke: rpcDoRequest: msg_id too high` for every operation after upgrading to the latest version.

And, my system's local time is correct / calibrated.

**To Reproduce**

```
% timedatectl
               Local time: Thu 2023-06-22 12:52:34 EDT
           Universal time: Thu 2023-06-22 16:52:34 UTC
                 RTC time: Thu 2023-06-22 16:52:39
                Time zone: Canada/Eastern (EDT, -0400)
System clock synchronized: no
              NTP service: n/a
          RTC in local TZ: no

$ tdl dl --debug -u https://t.me/c/19xxx29/218
group: task userCallback: initConnection: invoke: rpcDoRequest: msg_id too high
```

NB, that's the exact output even when the ` --debug` is used.

**Version:**
Run `tdl version` in terminal

```
$ tdl version
Version: 0.9.2
Commit: c60880f
Date: 2023-06-10T14:45:36Z

go1.19.9 linux/amd64
```

**Comment by iyear** [comment]
Have you tried `--ntp` flag?
