### ISSUE TITLE
[Feat] Fast resume download

### ISSUE THREAD

**Issue by nalllen** [iyear/tdl#228]
Remember the last successfully downloaded file/message id so if you close the program, then run the download command again it will start downloading from there right away without the need to read the whole export.json file and compere what files you have already downloaded.

This would be useful if  you want to download a old channel with thousands of messages and files as the current metod is slow and would also download anything that you might have removed.

Example: After downloading the first "oldest" 100 files you can close the program, then when you start it again it will immediately start downloading file 101 and onwards.

https://github.com/Dineshkarthik/telegram_media_downloader
Worked this way but its sadly not maintained anymore, it often skip files and have a hard time downloading old files.

**Comment by iyear** [comment]
This has been implemented.

If the last download of the same `data source` was incomplete, the downloader will ask the user to continue the download or to download from the beginning.

Or don't ask and directly `continue` or `restart`
```
# resume
tdl dl -u https://t.me/tdl/1 --continue
# restart
tdl dl -u https://t.me/tdl/1 --restart
```
