### ISSUE TITLE
[BUG] open key_data: file "key_data" not found

### ISSUE THREAD

**Issue by CharlesTran** [iyear/tdl#232]
MACOS

input: 
./tdl login -d "/Applications/Telegram.app"

output: 
Importing session from desktop client: /Applications/Telegram.app
open key_data: file "key_data" not found

Can you help me?

**Comment by iyear** [comment]
Are you using the desktop client? https://telegram.org/dl/desktop/mac / https://github.com/telegramdesktop/tdesktop

**Comment by ZhenShaw** [comment]
same  error， download from   https://github.com/telegramdesktop/tdesktop

**Comment by iyear** [comment]
@ZhenShaw Can you search `key_data` in your home dir? I don't have mac device.

**Comment by ZhenShaw** [comment]
> @ZhenShaw Can you search `key_data` dir in your home dir? I don't have mac device.

resloved! Sorry, it does't need to set -d "/Applications/Telegram.app",  use default will be ok.

**Comment by smashkins** [comment]
same error... file "key_data" not found.
I'm on Sonoma 14.1.2 and Telegram is the https://telegram.org/dl/desktop/mac

**Comment by iyear** [comment]
@smashkins Paste your command.  And can you search key_data dir in your home dir?

**Comment by smashkins** [comment]
```
tdl login
```
This give me an error such as  ```open key_data: file "key_data" not found```
but ```key_data``` dir doesn't exist on my home dir

Anyway I resolved it with qrcode login.

**Comment by leoshane13** [comment]
I download this telegram https://telegram.org/dl/desktop/mac instead the old version, and I could login with **tdl login** now, thanks
