### ISSUE TITLE
[BUG] callback: invoke pool: rpcDoRequest: rpc error code 420: TAKEOUT_INIT_DELAY (85920)

### ISSUE THREAD

**Issue by rohowwin** [iyear/tdl#234]
Preparing DC pool... It may take a while. size: 3
callback: invoke pool: rpcDoRequest: rpc error code 420: TAKEOUT_INIT_DELAY (85920)
请问输入下载指令之后出现这个错误需要如何解决

**Comment by leorcdias** [comment]
I still can't download, even after allowing the message in the app and running the command again. Only after remove `--takeout` does it work
