### ISSUE TITLE
[BUG] callback: validate domain: is empty

### ISSUE THREAD

**Issue by comercy** [iyear/tdl#239]
**Describe the bug**
Download failed when try to download a file from chat group(newest function?member can create many threads in chat).

**To Reproduce**
copy a link from chat group.It will says the link only available to member joined.
download from TDL, get a error"callback: validate domain: is empty"

**Expected behavior**
download success.

**Screenshots**

**Version:**
Run `tdl version` in terminal
0.9.3

**Additional context**

**Comment by iyear** [comment]
Please paste the command you input.

**Comment by comercy** [comment]
> Please paste the command you input.
i.e.
tdl dl -n XXX -l 4 -u https://t.me/c/1736335520/850/18246
callback: validate domain: is empty

**Comment by tmasixpence** [comment]
callback: validate domain: is empty

**Comment by iyear** [comment]
Please upgrade to v0.11.1 and feel free to reopen the issue if you have any questions.
