### ISSUE TITLE
Download command doesn't recognize links

### ISSUE THREAD

**Issue by aknight2015** [iyear/tdl#241]
![Screenshot from 2023-07-18 17-17-01](https://github.com/iyear/tdl/assets/47067592/ef34c0a3-6f39-4012-bed2-8759bab97ed0)

**Comment by iyear** [comment]
What's your version? Run `./tdl version` and paste information in the issue.

**Comment by iyear** [comment]
Please read the docs. You should use `-u` flag to specify urls. Like `tdl download -u https://t.me/puretaboox/1966`
