### ISSUE TITLE
安装好tdl后，运行login登录报错

### ISSUE THREAD

**Issue by ctmaomao** [iyear/tdl#245]
**Describe the bug**
PS C:\tdl> tdl login
WARN: If data exists in the namespace, data will be overwritten
Key: 'Options.NS' Error:Field validation for 'NS' failed on the 'required' tag

**Version:**
Version: 0.9.3
Commit: bef3fab
Date: 2023-06-30T10:37:00Z
go1.19.10 windows/amd64

**Comment by tilongzs** [comment]
+1

**Comment by iyear** [comment]
每个命名空间代表一个 Telegram 账号

你应该在每次执行命令时设置命名空间：

```shell
tdl -n iyear
# 或
export TDL_NS=iyear # 推荐做法
```

**Comment by tilongzs** [comment]
唉……tdl -n iyear没啥用，还是修改环境变量，增加TDL_NS=iyear吧，估计作者就没怎么测试过Windows

**Comment by tilongzs** [comment]
我才注意到有个“快速开始”。估计楼主跟我一样无视它直接去看“使用方法”了。
然而“使用方法”里的第一个设置指令“tdl -n iyear”的结果就是没反应，跟不用说Windows终端没有export指令也就不可能执行“export TDL_NS=iyear ”，在Windows终端应该是“set TDL_NS=iyear”。
![tdl -n iyear](https://img1.imgtp.com/2023/07/26/pXx4gdEo.jpg)

继续第二个登录指令，“tdl login”自然就会出现楼主一样的错误。所以你这篇教程的步骤需要调整。

**Comment by QPYIDRWIMG** [comment]
tdl -n iyear

**Comment by shen-lan** [comment]
所以到底怎么用。。。 执行 tdl -n iyear了，甚至手动在 环境变量里加 TDL_NS iyear了，都没用。执行命令还是会提示报错 
```
❯ tdl chat ls
Key: 'Options.NS' Error:Field validation for 'NS' failed on the 'required' tag
```

**Comment by shen-lan** [comment]
@tilongzs  老哥问题解决了吗

**Comment by ctmaomao** [comment]
解决啦 现在正常使用了

Li qing ***@***.***> 于 2023年10月18日周三 19:55写道：
