### ISSUE TITLE
[BUG] I can't download with `--takeout` flag

### ISSUE THREAD

**Issue by 7peanuts** [iyear/tdl#247]
**Describe the bug**

如图，使用 `--takeout` 命令下载时，一直卡在这个界面，下载文件夹里也只有几个空的缓存文件。
去掉后，能正常下载。
我一段时间没用了，好像前面几个版本就没用过了，之前下载的时候添加 `--takeout` 是可以下载的。

![20230724230657](https://github.com/iyear/tdl/assets/82173614/def1ea87-ee47-4f55-b1df-d3945e522189)
另外，再问下，为什么使用 `e gz` 跳过扩展名为 `.gz` 的贴纸文件，还是会下载？
是不是这个文件原始扩展名不是 `.gz`

**Version:**
v0.9.3

**Comment by leorcdias** [comment]
Same problem here. Even after allow data export request message

**Comment by iyear** [comment]
I reproduced the problem, but I think it's Telegram server issue. Because I was able to get the takeout session id normally.

```
2023-07-26 14:39:38	INFO	dl	dcpool/dcpool.go:111	get takeout id	{"id": 4785732825182172572}
```

**Comment by iyear** [comment]
@7peanuts The exclude filter filters files based on their file extension on the server. Do sticker files show up on Telegram with a `.gz` extension?

**Comment by 7peanuts** [comment]
> @7peanuts The exclude filter filters files based on their file extension on the server. Do sticker files show up on Telegram with a `.gz` extension?

哦，我搞错了，是 `.tgs` 的动态贴纸，下载下来变成 `.gz`

`--takeout` 无法下载，是因为我帐号受限了吗？下载时，桌面客户端就会无法显示新信息，得重启才能显示。

**Comment by Rainsheep** [comment]
same problem.   --takeout can not download

**Comment by Abu3safeer** [comment]
Here too

**Comment by the4anoni** [comment]
I can't download files using `--takeout` too

**Comment by Abu3safeer** [comment]
Any update regarding this?

**Comment by iyear** [comment]
Please try v0.17.5.
