### ISSUE TITLE
[Feat]速度超过1MB/S就会Download aborted.

### ISSUE THREAD

**Issue by golden777** [iyear/tdl#255]
经多次尝试,发现服务器方面限制单线程速度为1MB/S,超过就会 Download aborted.
网络质量好,单线程就能达到,反之多线程总速度超过1MB/S就会 aborted.
刚才又试了,单线程,时间长了也会 Download aborted.
断点续传和自动重试或许能改善.
请求增加断点续传,或者把下载URL直接转给下载软件来来处理

**Comment by hoixding** [comment]
遇到同样的问题，限速以后也有一定效果

**Comment by hoixding** [comment]
遇到同样的问题，限速以后也有一定效果

**Comment by Rainsheep** [comment]
+1
