### ISSUE TITLE
win11登录问题 Key: 'Options.NS' Error:Field validation for 'NS' failed on the 'required' tag

### ISSUE THREAD

**Issue by ctmaomao** [iyear/tdl#256]
我在win11下，成功安装后，尝试设定
tdl -n iyear
# or
export TDL_NS=iyear # recommended
使用powershell或者cmd命令行执行tdl都没有反应
执行exprot发现这不是win命令
网上查了一下说win命令要用setx TDL_NS iyear
设置环境变量后，可以使用 echo %TDL_NS% 命令来验证其值
我在powershell环境输入
PS setx TDL_NS iyear
成功: 指定的值已得到保存。
验证后如下：
PS C:\> echo %TDL_NS%
%TDL_NS%
完成上述设定后，我尝试执行login，还是出现如下报错
PS C:\> tdl login
WARN: If data exists in the namespace, data will be overwritten
Key: 'Options.NS' Error:Field validation for 'NS' failed on the 'required' tag
如果执行quickstart命令的话，好像显示登录上去了
PS C:\> tdl login -n quickstart -d Z:\-\Telegram
WARN: If data exists in the namespace, data will be overwritten
Importing session from desktop client: Z:\-\Telegram
? Choose a user id: xxxxxxxx
Import xxxxxxxxx successfully to 'quickstart' namespace!
? Do you want to logout existing desktop session? [? for help] (y/N)

然后我尝试下载视频链接
? Do you want to logout existing desktop session? No
PS C:\> tdl dl -u https://t.me/freedom_watch/8177
Key: 'Options.NS' Error:Field validation for 'NS' failed on the 'required' tag

然后这个NS错误又出现了
请问是我哪里操作不对么？还是说我有遗漏什么地方？
非常感谢大佬协助！

**Comment by iyear** [comment]
#245
