### ISSUE TITLE
0.2.1版本，下載報錯

### ISSUE THREAD

**Issue by tsinit2001** [iyear/tdl#26]
0.2.0版本，能夠正常下載的同一個文件，在0.2.1版本，下載就提示錯誤。
WIN 7 系統，先用0.2.0版本測試：
 .\tdl dl url -n hebine1 --proxy socks5://localhost:2333 -u https://t.me/c/1650884719/1198
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ...  0.0% [..................] [0 B in 8.54s; 0 B/s]
[K[................................................................] [9s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ...  6.4% [#.................] [512.00 KB in 8.64s; ~ETA: 2m15s; 59
26 KB/s]
[K[###.............................................................] [9s; 59.26 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ...  6.4% [#.................] [512.00 KB in 8.74s; ~ETA: 2m17s; 58
58 KB/s]
[K[###.............................................................] [9s; 58.58 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ...  6.4% [#.................] [512.00 KB in 8.841s; ~ETA: 2m19s; 5
.92 KB/s]
[K[###.............................................................] [9s; 57.92 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ...  6.4% [#.................] [512.00 KB in 8.941s; ~ETA: 2m20s; 5
.27 KB/s]
[K[###.............................................................] [9s; 57.27 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ...  6.4% [#.................] [512.00 KB in 9.041s; ~ETA: 2m22s; 5
.63 KB/s]
[K[###.............................................................] [9s; 56.63 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ...  6.4% [#.................] [512.00 KB in 9.141s; ~ETA: 2m23s; 5
.01 KB/s]
[K[###.............................................................] [9s; 56.01 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ...  6.4% [#.................] [512.00 KB in 9.241s; ~ETA: 2m25s; 5
.41 KB/s]
[K[###.............................................................] [9s; 55.41 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ...  6.4% [#.................] [512.00 KB in 9.341s; ~ETA: 2m26s; 5
.81 KB/s]
[K[###.............................................................] [9s; 54.81 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ...  6.4% [#.................] [512.00 KB in 9.441s; ~ETA: 2m28s; 5
.23 KB/s]
[K[###.............................................................] [9s; 54.23 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 12.8% [##................] [1.00 MB in 9.541s; ~ETA: 1m10s; 107
33 KB/s]
[K[#######.........................................................] [10s; 107.33 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 12.8% [##................] [1.00 MB in 9.641s; ~ETA: 1m11s; 106
22 KB/s]
[K[#######.........................................................] [10s; 106.22 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 12.8% [##................] [1.00 MB in 9.741s; ~ETA: 1m11s; 105
13 KB/s]
[K[#######.........................................................] [10s; 105.13 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 12.8% [##................] [1.00 MB in 9.841s; ~ETA: 1m12s; 104
06 KB/s]
[K[#######.........................................................] [10s; 104.06 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 12.8% [##................] [1.00 MB in 9.941s; ~ETA: 1m13s; 103
01 KB/s]
[K[#######.........................................................] [10s; 103.01 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 19.2% [###...............] [1.50 MB in 10.041s; ~ETA: 43s; 152.
8 KB/s]
[K[############....................................................] [10s; 152.98 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 19.2% [###...............] [1.50 MB in 10.141s; ~ETA: 43s; 151.
7 KB/s]
[K[############....................................................] [10s; 151.47 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 19.2% [###...............] [1.50 MB in 10.241s; ~ETA: 44s; 149.
9 KB/s]
[K[############....................................................] [10s; 149.99 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 19.2% [###...............] [1.50 MB in 10.341s; ~ETA: 44s; 148.
4 KB/s]
[K[############....................................................] [10s; 148.54 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 19.2% [###...............] [1.50 MB in 10.442s; ~ETA: 45s; 147.
0 KB/s]
[K[############....................................................] [10s; 147.10 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 25.6% [####..............] [2.00 MB in 10.541s; ~ETA: 32s; 194.
0 KB/s]
[K[################................................................] [11s; 194.30 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 25.6% [####..............] [2.00 MB in 10.641s; ~ETA: 32s; 192.
7 KB/s]
[K[################................................................] [11s; 192.47 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 25.6% [####..............] [2.00 MB in 10.741s; ~ETA: 32s; 190.
8 KB/s]
[K[################................................................] [11s; 190.68 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 25.6% [####..............] [2.00 MB in 10.841s; ~ETA: 33s; 188.
2 KB/s]
[K[################................................................] [11s; 188.92 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 25.6% [####..............] [2.00 MB in 10.941s; ~ETA: 33s; 187.
9 KB/s]
[K[################................................................] [11s; 187.19 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 32.0% [#####.............] [2.50 MB in 11.041s; ~ETA: 23s; 231.
7 KB/s]
[K[####################............................................] [11s; 231.87 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 32.0% [#####.............] [2.50 MB in 11.141s; ~ETA: 24s; 229.
9 KB/s]
[K[####################............................................] [11s; 229.79 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 32.0% [#####.............] [2.50 MB in 11.241s; ~ETA: 24s; 227.
4 KB/s]
[K[####################............................................] [11s; 227.74 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 32.0% [#####.............] [2.50 MB in 11.341s; ~ETA: 24s; 225.
4 KB/s]
[K[####################............................................] [11s; 225.74 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 32.0% [#####.............] [2.50 MB in 11.441s; ~ETA: 24s; 223.
6 KB/s]
[K[####################............................................] [11s; 223.76 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 38.4% [######............] [3.00 MB in 11.541s; ~ETA: 19s; 266.
9 KB/s]
[K[########################........................................] [12s; 266.19 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 38.4% [######............] [3.00 MB in 11.641s; ~ETA: 19s; 263.
0 KB/s]
[K[########################........................................] [12s; 263.90 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 38.4% [######............] [3.00 MB in 11.741s; ~ETA: 19s; 261.
5 KB/s]
[K[########################........................................] [12s; 261.65 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 38.4% [######............] [3.00 MB in 11.841s; ~ETA: 19s; 259.
4 KB/s]
[K[########################........................................] [12s; 259.44 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 38.4% [######............] [3.00 MB in 11.941s; ~ETA: 19s; 257.
7 KB/s]
[K[########################........................................] [12s; 257.27 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 44.9% [########..........] [3.50 MB in 12.041s; ~ETA: 15s; 297.
6 KB/s]
[K[############################....................................] [12s; 297.66 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 44.9% [########..........] [3.50 MB in 12.141s; ~ETA: 15s; 295.
1 KB/s]
[K[############################....................................] [12s; 295.21 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 44.9% [########..........] [3.50 MB in 12.241s; ~ETA: 16s; 292.
9 KB/s]
[K[############################....................................] [12s; 292.79 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 44.9% [########..........] [3.50 MB in 12.341s; ~ETA: 16s; 290.
2 KB/s]
[K[############################....................................] [12s; 290.42 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 44.9% [########..........] [3.50 MB in 12.441s; ~ETA: 16s; 288.
9 KB/s]
[K[############################....................................] [12s; 288.09 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 51.3% [#########.........] [4.00 MB in 12.541s; ~ETA: 12s; 326.
2 KB/s]
[K[################################................................] [13s; 326.62 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 51.3% [#########.........] [4.00 MB in 12.641s; ~ETA: 12s; 324.
3 KB/s]
[K[################################................................] [13s; 324.03 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 51.3% [#########.........] [4.00 MB in 12.741s; ~ETA: 12s; 321.
9 KB/s]
[K[################################................................] [13s; 321.49 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 51.3% [#########.........] [4.00 MB in 12.841s; ~ETA: 12s; 318.
8 KB/s]
[K[################################................................] [13s; 318.98 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 51.3% [#########.........] [4.00 MB in 12.941s; ~ETA: 12s; 316.
2 KB/s]
[K[################################................................] [13s; 316.52 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 57.7% [##########........] [4.50 MB in 13.041s; ~ETA: 10s; 353.
5 KB/s]
[K[####################################............................] [13s; 353.35 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 57.7% [##########........] [4.50 MB in 13.141s; ~ETA: 10s; 350.
6 KB/s]
[K[####################################............................] [13s; 350.66 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 57.7% [##########........] [4.50 MB in 13.241s; ~ETA: 10s; 348.
2 KB/s]
[K[####################################............................] [13s; 348.02 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 57.7% [##########........] [4.50 MB in 13.341s; ~ETA: 10s; 345.
1 KB/s]
[K[####################################............................] [13s; 345.41 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 57.7% [##########........] [4.50 MB in 13.441s; ~ETA: 10s; 342.
4 KB/s]
[K[####################################............................] [13s; 342.84 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 57.7% [##########........] [4.50 MB in 13.541s; ~ETA: 10s; 340.
0 KB/s]
[K[####################################............................] [14s; 340.30 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 64.1% [###########.......] [5.00 MB in 13.641s; ~ETA: 8s; 375.3
 KB/s]
[K[########################################........................] [14s; 375.34 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 64.1% [###########.......] [5.00 MB in 13.741s; ~ETA: 8s; 372.6
 KB/s]
[K[########################################........................] [14s; 372.61 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 64.1% [###########.......] [5.00 MB in 13.841s; ~ETA: 8s; 369.9
 KB/s]
[K[########################################........................] [14s; 369.92 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 64.1% [###########.......] [5.00 MB in 13.941s; ~ETA: 8s; 367.2
 KB/s]
[K[########################################........................] [14s; 367.27 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 64.1% [###########.......] [5.00 MB in 14.041s; ~ETA: 8s; 364.6
 KB/s]
[K[########################################........................] [14s; 364.65 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 64.1% [###########.......] [5.00 MB in 14.141s; ~ETA: 8s; 362.0
 KB/s]
[K[########################################........................] [14s; 362.07 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 64.1% [###########.......] [5.00 MB in 14.241s; ~ETA: 8s; 359.5
 KB/s]
[K[########################################........................] [14s; 359.53 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 64.1% [###########.......] [5.00 MB in 14.341s; ~ETA: 8s; 357.0
 KB/s]
[K[########################################........................] [14s; 357.02 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 64.1% [###########.......] [5.00 MB in 14.441s; ~ETA: 8s; 354.5
 KB/s]
[K[########################################........................] [14s; 354.55 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 64.1% [###########.......] [5.00 MB in 14.541s; ~ETA: 8s; 352.1
 KB/s]
[K[########################################........................] [15s; 352.11 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 64.1% [###########.......] [5.00 MB in 14.641s; ~ETA: 8s; 349.7
 KB/s]
[K[########################################........................] [15s; 349.71 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 70.5% [############......] [5.50 MB in 14.741s; ~ETA: 6s; 382.0
 KB/s]
[K[############################################....................] [15s; 382.07 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 70.5% [############......] [5.50 MB in 14.841s; ~ETA: 6s; 379.4
 KB/s]
[K[############################################....................] [15s; 379.49 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 70.5% [############......] [5.50 MB in 14.941s; ~ETA: 6s; 376.9
 KB/s]
[K[############################################....................] [15s; 376.95 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 70.5% [############......] [5.50 MB in 15.041s; ~ETA: 6s; 374.4
 KB/s]
[K[############################################....................] [15s; 374.45 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 70.5% [############......] [5.50 MB in 15.141s; ~ETA: 6s; 371.9
 KB/s]
[K[############################################....................] [15s; 371.97 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 70.5% [############......] [5.50 MB in 15.241s; ~ETA: 7s; 369.5
 KB/s]
[K[############################################....................] [15s; 369.53 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 70.5% [############......] [5.50 MB in 15.341s; ~ETA: 7s; 367.1
 KB/s]
[K[############################################....................] [15s; 367.12 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 76.9% [#############.....] [6.00 MB in 15.441s; ~ETA: 5s; 397.9
 KB/s]
[K[################################################................] [15s; 397.90 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 76.9% [#############.....] [6.00 MB in 15.541s; ~ETA: 5s; 395.3
 KB/s]
[K[################################################................] [16s; 395.34 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 76.9% [#############.....] [6.00 MB in 15.641s; ~ETA: 5s; 392.8
 KB/s]
[K[################################################................] [16s; 392.82 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 76.9% [#############.....] [6.00 MB in 15.741s; ~ETA: 5s; 390.3
 KB/s]
[K[################################################................] [16s; 390.32 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 76.9% [#############.....] [6.00 MB in 15.841s; ~ETA: 5s; 387.8
 KB/s]
[K[################################################................] [16s; 387.86 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 76.9% [#############.....] [6.00 MB in 15.941s; ~ETA: 5s; 385.4
 KB/s]
[K[################################################................] [16s; 385.42 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 76.9% [#############.....] [6.00 MB in 16.041s; ~ETA: 5s; 383.0
 KB/s]
[K[################################################................] [16s; 383.02 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 83.3% [##############....] [6.50 MB in 16.141s; ~ETA: 3s; 412.3
 KB/s]
[K[#####################################################...........] [16s; 412.37 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 83.3% [##############....] [6.50 MB in 16.241s; ~ETA: 3s; 409.8
 KB/s]
[K[#####################################################...........] [16s; 409.83 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 83.3% [##############....] [6.50 MB in 16.341s; ~ETA: 3s; 407.3
 KB/s]
[K[#####################################################...........] [16s; 407.32 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 83.3% [##############....] [6.50 MB in 16.441s; ~ETA: 3s; 404.8
 KB/s]
[K[#####################################################...........] [16s; 404.84 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 83.3% [##############....] [6.50 MB in 16.541s; ~ETA: 3s; 402.3
 KB/s]
[K[#####################################################...........] [17s; 402.39 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 83.3% [##############....] [6.50 MB in 16.641s; ~ETA: 3s; 399.9
 KB/s]
[K[#####################################################...........] [17s; 399.98 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 83.3% [##############....] [6.50 MB in 16.741s; ~ETA: 3s; 397.5
 KB/s]
[K[#####################################################...........] [17s; 397.59 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 87.2% [###############...] [6.80 MB in 16.841s; ~ETA: 3s; 413.6
 KB/s]
[K[#######################################################.........] [17s; 413.63 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 87.2% [###############...] [6.80 MB in 16.941s; ~ETA: 3s; 411.1
 KB/s]
[K[#######################################################.........] [17s; 411.19 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 87.2% [###############...] [6.80 MB in 17.041s; ~ETA: 3s; 408.7
 KB/s]
[K[#######################################################.........] [17s; 408.78 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 87.2% [###############...] [6.80 MB in 17.14s; ~ETA: 3s; 406.41
KB/s]
[K[#######################################################.........] [17s; 406.41 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 87.2% [###############...] [6.80 MB in 17.24s; ~ETA: 3s; 404.06
KB/s]
[K[#######################################################.........] [17s; 404.06 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 87.2% [###############...] [6.80 MB in 17.34s; ~ETA: 3s; 401.73
KB/s]
[K[#######################################################.........] [17s; 401.73 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 87.2% [###############...] [6.80 MB in 17.44s; ~ETA: 3s; 399.42
KB/s]
[K[#######################################################.........] [17s; 399.42 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 93.6% [################..] [7.30 MB in 17.54s; 426.33 KB/s]
[K[###########################################################.....] [18s; 426.33 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 93.6% [################..] [7.30 MB in 17.64s; 423.92 KB/s]
[K[###########################################################.....] [18s; 423.92 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 93.6% [################..] [7.30 MB in 17.74s; 421.53 KB/s]
[K[###########################################################.....] [18s; 421.53 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 93.6% [################..] [7.30 MB in 17.84s; 419.17 KB/s]
[K[###########################################################.....] [18s; 419.17 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 93.6% [################..] [7.30 MB in 17.94s; 416.83 KB/s]
[K[###########################################################.....] [18s; 416.83 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 93.6% [################..] [7.30 MB in 18.04s; 414.52 KB/s]
[K[###########################################################.....] [18s; 414.52 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... 93.6% [################..] [7.30 MB in 18.14s; 412.23 KB/s]
[K[###########################################################.....] [18s; 412.23 KB/s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ... [32mdone![0m [7.80 MB in 18.162s; 438.04 KB/s]

至此，順利下載完成，得到一個7.8M，播放時長19秒的視頻。
之後，換用0.2.1版本再對同一個文件進行下載，就會出現錯誤提示：
[KPS E:\tg\td3> .\tdl21 dl url -n hebine1 --proxy socks5://localhost:2333 -u https://t.me/c/1650884719/1198
[K[32mAll files will be downloaded to 'downloads' dir[0m
[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ...  0.0% [..................] [0 B in 83ms; 0 B/s]
[K[................................................................] [0s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ...  0.0% [..................] [0 B in 183ms; 0 B/s]
[K[................................................................] [0s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ...  0.0% [..................] [0 B in 283ms; 0 B/s]
[K[................................................................] [0s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ...  0.0% [..................] [0 B in 383ms; 0 B/s]
[K[................................................................] [0s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ...  0.0% [..................] [0 B in 483ms; 0 B/s]
[K[................................................................] [0s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ...  0.0% [..................] [0 B in 583ms; 0 B/s]
[K[................................................................] [1s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ...  0.0% [..................] [0 B in 683ms; 0 B/s]
[K[................................................................] [1s]
[2A[K[34m1650884719_1198_BMjAyMjA5MTYyMzM3M[0m~ ...  0.0% [..................] [0 B in 783ms; 0 B/s]
[K[................................................................] [1s]
panic: unaligned 64-bit atomic operation

goroutine 63 [running]:
runtime/internal/atomic.panicUnaligned()
        runtime/internal/atomic/unaligned.go:8 +0x2d
runtime/internal/atomic.Xadd64(0x14123834, 0x1)
        runtime/internal/atomic/atomic_386.s:125 +0x11
go.uber.org/atomic.(*Int64).Add(...)
        go.uber.org/atomic@v1.10.0/int64.go:50
go.uber.org/atomic.(*Int64).Inc(...)
        go.uber.org/atomic@v1.10.0/int64.go:60
github.com/gotd/td/telegram.(*Client).dc.func1()
        github.com/gotd/td@v0.68.1/telegram/pool.go:69 +0x6c
github.com/gotd/td/internal/pool.(*DC).createConnection(0x1406e000, 0x1)
        github.com/gotd/td@v0.68.1/internal/pool/pool.go:72 +0x24
github.com/gotd/td/internal/pool.(*DC).acquire(0x1406e000, {0x14a10a4, 0x143e3e30})
        github.com/gotd/td@v0.68.1/internal/pool/pool.go:181 +0x1e8
github.com/gotd/td/internal/pool.(*DC).Invoke(0x1406e000, {0x14a10a4, 0x143e3e30}, {0x149be84, 0x14502030}, {0x149bdd0,
0x145820b8})
        github.com/gotd/td@v0.68.1/internal/pool/pool.go:246 +0x82
github.com/gotd/td/tg.(*Client).AuthImportAuthorization(0x1445d798, {0x14a10a4, 0x143e3e30}, 0x14502030)
        github.com/gotd/td@v0.68.1/tg/tl_auth_import_authorization_gen.go:204 +0x7d
github.com/gotd/td/telegram.(*Client).transfer(0x14123600, {0x14a10a4, 0x143e3e30}, 0x1445d798, 0x5)
        github.com/gotd/td@v0.68.1/telegram/transfer.go:30 +0xad
github.com/gotd/td/telegram.(*Client).dc(0x14123600, {0x14a10a4, 0x143e3e30}, 0x5, 0x1, 0x14094430)
        github.com/gotd/td@v0.68.1/telegram/pool.go:97 +0x421
github.com/gotd/td/telegram.(*Client).invokeSub(0x14123600, {0x14a10a4, 0x143e3e30}, 0x5, {0x149e508, 0x14594140}, {0x14
9e4b8, 0x143fe038})
        github.com/gotd/td@v0.68.1/telegram/sub_conns.go:20 +0xbb
github.com/gotd/td/telegram.(*Client).invokeDirect(0x14123600, {0x14a10a4, 0x143e3e30}, {0x149e508, 0x14594140}, {0x149e
4b8, 0x143fe038})
        github.com/gotd/td@v0.68.1/telegram/invoke.go:68 +0x3f5
github.com/gotd/td/telegram.InvokeFunc.Invoke(0x143fe4c0, {0x14a10a4, 0x143e3e30}, {0x149e508, 0x14594140}, {0x149e4b8,
0x143fe038})
        github.com/gotd/td@v0.68.1/telegram/middleware.go:15 +0x4c
github.com/gotd/contrib/middleware/floodwait.(*SimpleWaiter).Handle.func1({0x14a10a4, 0x143e3e30}, {0x149e508, 0x1459414
0}, {0x149e4b8, 0x143fe038})
        github.com/gotd/contrib@v0.13.0/middleware/floodwait/simple_waiter.go:77 +0xa7
github.com/gotd/td/telegram.InvokeFunc.Invoke(0x143b73c0, {0x14a10a4, 0x143e3e30}, {0x149e508, 0x14594140}, {0x149e4b8,
0x143fe038})
        github.com/gotd/td@v0.68.1/telegram/middleware.go:15 +0x4c
github.com/gotd/td/tg.(*Client).UploadGetFile(0x143fe4c8, {0x14a10a4, 0x143e3e30}, 0x14594140)
        github.com/gotd/td@v0.68.1/tg/tl_upload_get_file_gen.go:340 +0x7d
github.com/gotd/td/telegram/downloader.master.Chunk({{0x14a15a8, 0x143fe4c8}, 0x1, 0x0, {0x14a38f0, 0x143e3d40}}, {0x14a
10a4, 0x143e3e30}, 0x300000, 0x80000)
        github.com/gotd/td@v0.68.1/telegram/downloader/master.go:44 +0xc7
github.com/gotd/td/telegram/downloader.(*reader).next(0x14098200, {0x14a10a4, 0x143e3e30}, 0x300000, 0x80000)
        github.com/gotd/td@v0.68.1/telegram/downloader/reader.go:92 +0x73
github.com/gotd/td/telegram/downloader.(*reader).nextPlain(0x14098200, {0x14a10a4, 0x143e3e30})
        github.com/gotd/td@v0.68.1/telegram/downloader/reader.go:87 +0xc4
github.com/gotd/td/telegram/downloader.(*reader).Next(0x14098200, {0x14a10a4, 0x143e3e30})
        github.com/gotd/td@v0.68.1/telegram/downloader/reader.go:54 +0xe7
github.com/gotd/td/telegram/downloader.(*Downloader).parallel.func2.1({0x14a10a4, 0x143e3e30})
        github.com/gotd/td@v0.68.1/telegram/downloader/parallel.go:50 +0xf1
github.com/gotd/td/internal/tdsync.(*CancellableGroup).Go.func1()
        github.com/gotd/td@v0.68.1/internal/tdsync/cancel_group.go:48 +0x2c
golang.org/x/sync/errgroup.(*Group).Go.func1()
        golang.org/x/sync@v0.0.0-20220819030929-7fc1605a5dde/errgroup/errgroup.go:75 +0x62
created by golang.org/x/sync/errgroup.(*Group).Go
        golang.org/x/sync@v0.0.0-20220819030929-7fc1605a5dde/errgroup/errgroup.go:72 +0xa6

是否是因爲沒有64位的問題？請問會提供WIN 64位的版本麼？

**Comment by tsinit2001** [comment]
已經看到了新出的WIN 64位版本，使用正常了。多謝。
另外，再多請教一下，
[KPS E:\tg\td3> .\tdl21 version
Version: 0.2.1
Commit: 0229184
Date: 2022-09-21T13:42:06Z

go1.18.5 windows/amd64
PS E:\tg\td3> .\tdl21 up
Key: 'Options.NS' Error:Field validation for 'NS' failed on the 'required' tag
PS E:\tg\td3>
這個更新的命令，是否我的語法錯了啊？

**Comment by iyear** [comment]
报错请看： https://github.com/iyear/tdl/issues/14

**Comment by tsinit2001** [comment]
哦哦。學習了。多謝大佬！
