### ISSUE TITLE
[BUG]  on arm proxy not work

### ISSUE THREAD

**Issue by saturn99** [iyear/tdl#264]
**Describe the bug**
when use `--proxy socks5://x.x.x.x:port` or `export TDL_PROXY=x.x.x.x:port` on arm device's, `tdl` can't connect 

**To Reproduce**
```
armv7> tdl login --reconnect-timeout 0m20s --debug -n mtwo --code --proxy socks5://192.168.1.3:7891
WARN: If data exists in the namespace, data will be overwritten
start: create auth key: write SetClientDHParamsRequest: write: write intermediate: write tcp 192.168.1.38:37584->192.168.1.3:7891: i/o timeout
```
proxy address in this case (192.168.1.3:7891) is working correctly

test proxy on arm
```
armv7> curl -x "socks5://192.168.1.3:7891" $site/ip.php 
5.y.y.11
```
OR

test proxy and tdl on pc (x64)
```
PC-x64> tdl login --reconnect-timeout 0m20s --debug -n mtwo --code --proxy socks5://192.168.1.3:7891
WARN: If data exists in the namespace, data will be overwritten
WARN: Using the built-in APP_ID & APP_HASH may increase the probability of blocking
Login...
? Enter your phone number: (+86 12345678900)
```

**Screenshots**
![image](https://github.com/iyear/tdl/assets/5188799/fd354101-2b3b-4239-9acc-ad4a26a38a33)

**Version:**
Version: 0.9.6
Commit: ab8095d
Date: 2023-08-03T07:14:00Z

go1.19.11 linux/arm

**Comment by iyear** [comment]
Usually network functions are independent of the platform arch, so I don't know what happened...

**Comment by iyear** [comment]
The i/o timeout error is still usually proxy related.

**Comment by iyear** [comment]
Try new version and feel free to reopen the issue if you have any questions

**Comment by shizhai** [comment]
the same issue happend on my raspberry pi
