### ISSUE TITLE
[BUG] 无法登录

### ISSUE THREAD

**Issue by lilith-rong** [iyear/tdl#269]
**Describe the bug**

用比较新版本的tdl无法登录，可能是tdl的问题，也可能是我安装的telegram的问题
使用0.6版本的tdl可以正常登录，但是使用更新的版本无法登录，报错内容为
no data found in possible paths, please specify path to Telegram Desktop directory with `-d` flag
加上了telegram的目录之后，报错内容为
CreateFile C:\Program: The system cannot find the file specified.

**To Reproduce**
安装最新版微软商店当中的telegram，使用0.6以上的tdl（推测可能可以复现的步骤）
微软商店下载的telegram给我的目录为：C:\Program Files\WindowsApps\TelegramMessengerLLP.TelegramDesktop_4.8.10.0_x64__t4vj0pshhgkwm

**Expected behavior**

**Screenshots**
![image](https://github.com/iyear/tdl/assets/97450033/52907bb8-afc3-4d5f-ba66-0fd16aa3dffe)

**Version:**
Run `tdl version` in terminal
图中tdl为0.6版本，tdl-back为0.9.6版本

**Additional context**

**Comment by iyear** [comment]
请使用 `-d "路径"`
