### ISSUE TITLE
[BUG] 下载时，会出现CPU占用率、内存占用率刷屏

### ISSUE THREAD

**Issue by Hurpods** [iyear/tdl#275]
![Snipaste_2023-08-20_17-35-37](https://github.com/iyear/tdl/assets/30931892/b7832613-ceaa-44fa-9010-b413e13717c2)
如图所示
操作步骤：
tdl login
tdl dl -u xxxx
等待几秒后就出现了刷屏。设置了TDL_NS和TDL_PROXY的环境变量
环境：Windows11、PowerShell 7.3.6

**Comment by iyear** [comment]
本地无法复现，这通常与终端有关，部分终端未实现控制字符。请使用 Windows Terminal 再次尝试

**Comment by Tiannyaaa** [comment]
拉宽你的PowerShell的窗口就能解决。

**Comment by himonkiy** [comment]
> 拉宽你的PowerShell的窗口就能解决。

牛逼
