### ISSUE TITLE
导出第x条消息到第y条消息这个功能是取消了吗？

### ISSUE THREAD

**Issue by Tiannyaaa** [iyear/tdl#284]
Please describe your feature request
![image](https://github.com/iyear/tdl/assets/109339357/5c8127e1-20a8-4ae0-b360-b0f81edd91eb)
如还有此功能，新版本应使用哪条命令？

**Comment by iyear** [comment]
```shell
# 导出指定消息 ID 范围内的消息
tdl chat export -c CHAT_INPUT -T id -i 100,500
```
