### ISSUE TITLE
如何用本程序获得登录验证码？

### ISSUE THREAD

**Issue by doradayel** [iyear/tdl#286]
本程序登录后选择了登出telegram桌面版，再次登录提示需要输入发送到其他设备上的code。由于没有装手机版，现在已经无法登录，求助。

**Comment by iyear** [comment]
没有其他办法，需要在手机上先使用短信验证码登录后才可以在桌面版登录。tdl在登录时有提示：`NB: Ensure that you can re-login to desktop client`

**Comment by doradayel** [comment]
> 没有其他办法，需要在手机上先使用短信验证码登录后才可以在桌面版登录。tdl在登录时有提示：`NB: Ensure that you can re-login to desktop client`

我装了手机版发现也是要求输入在其他设备上接收到的验证码，查了下发现很多人都出现这个问题。

建议文档中增加相关提示，我这号已经废了，得等6个月自动注销

**Comment by qwmnerbvqwmn** [comment]
现在（2025/8/15）使用tdl chat export --all --raw -T last -i 100 -o latest_messages.json  -c 777000 获取 telegram发送的消息，里边有验证码的消息，777000是telegram的chat id，可以用tdl chat ls查看消息列表，第一列就是chat id
