### ISSUE TITLE
[Feat] users in chat export

### ISSUE THREAD

**Issue by lukas016** [iyear/tdl#288]
Hi, is possible add users into chat export command for channels? Maybe as optional field or list of participants for post-processing.

--raw export contains User id, but it isn't very user-friendly and other information about user are missing, if you want to just archive your channels.

I did naive implementation https://github.com/iyear/tdl/compare/master...lukas016:tdl:master

It isn't very hard but i am not expert on telegram API and maybe it is agains concept of your app.

**Comment by iyear** [comment]
Thanks for the code, I understand what you mean.

The intention of `chat export` is not to backup, but to export files that are compatible with Telegram Desktop JSON format to download files.

I would prefer to add a new `chat users` command to export all members of a dialog. You can use some JSON tools or scripts to map the user to the raw message.

What do you think of this?

**Comment by lukas016** [comment]
sure no problem, it will be flexible solution.

But chat users has to be used with chat export --raw only because standard output doesn't contain any information about users.

Question:
what is different between --raw and standard output. Is raw still compatible with Telegram Desktop JSON?

**Comment by iyear** [comment]
Well. std output is compatible with Telegram Desktop JSON, but raw output is only for dev/debugging(maybe backup)

**Comment by lukas016** [comment]
@iyear Do you want to implement it or can i do it?

**Comment by iyear** [comment]
@lukas016 Feel free to do it. Any contribution is welcomed!

**Comment by lukas016** [comment]
Fixes #298
