### ISSUE TITLE
[BUG]  tdl chat export 下载问题

### ISSUE THREAD

**Issue by pkr5277** [iyear/tdl#289]
![WX20230904-112308@2x](https://github.com/iyear/tdl/assets/38154917/bc405727-2361-4992-b003-4b2dd21446b8)

如图，我使用了tdl chat export -c这个命令，但是之下载下来了json，没有任何文件，然后如果用-d指定下载目录，就是报错unknown shorthand flag: 'd' in -d，下载的json里有文件信息，但是没下载任何文件

![WX20230904-112516@2x](https://github.com/iyear/tdl/assets/38154917/8dcf97aa-e883-4478-8c5a-ad0b205c6b59)

**Comment by iyear** [comment]
`chat export` 命令的作用就是这样，仅导出兼容 Telegram Desktop 的 JSON 文件，请再使用 `tdl dl -f xxx.json` 来下载具体文件

**Comment by pkr5277** [comment]
> `chat export`命令的作用就是这样，仅导出兼容 Telegram Desktop 的 JSON 文件，请再使用`tdl dl -f xxx.json`来下载具体文件
谢谢大佬，成功了
