### ISSUE TITLE
[BUG] can't download

### ISSUE THREAD

**Issue by yuanlaishihaoge** [iyear/tdl#293]
All files will be downloaded to '/workspace' dir
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1235f17]

goroutine 42 [running]:
github.com/iyear/tdl/pkg/downloader.(*Downloader).download(0xc0005602a0, {0x197ab58, 0xc0000c5180}, 0x0)
	github.com/iyear/tdl/pkg/downloader/downloader.go:128 +0x317
github.com/iyear/tdl/pkg/downloader.(*Downloader).Download.func1()
	github.com/iyear/tdl/pkg/downloader/downloader.go:88 +0x29
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.3.0/errgroup/errgroup.go:72 +0xa5

**Comment by yuanlaishihaoge** [comment]
tdl dl -u https://t.me/viego47/xxx-d /workspace

**Comment by iyear** [comment]
What's your version

**Comment by yuanlaishihaoge** [comment]
> What's your version

Version: 0.10.0
Commit: 94b1806
Date: 2023-09-11T11:53:53Z

go1.19.12 linux/amd64
