### ISSUE TITLE
downloader support chat mode. provide `from`  `to` flag

### ISSUE THREAD

**Issue by iyear** [iyear/tdl#3]

**Comment by tsinit2001** [comment]
大佬能指點一下，如何以chat爲單位來進行下載麼？

**Comment by iyear** [comment]
@tsinit2001 It will be supported in v0.3.0, and currently I focus on bug fixes.

**Comment by iyear** [comment]
1a5ec3403eb8ac8e2a1a817838da8e87839d5528
