### ISSUE TITLE
[Feat] download from raw file as input

### ISSUE THREAD

**Issue by lukas016** [iyear/tdl#302]
Hi, i have little problem with create archive of chats with external tool. Problem is double calling of Telegram API for same resource.

My workflow:
1. tdl chat ls -o json > chats.json
2. tdl chat users -c "11111111" -o users.json
3. tdl chat export -c "11111111" --raw -o history.json
4. tdl chat export -c "11111111" --raw -o download.json
5. tdl chat download -d output -f download.json

As you can see, i have to call 2 times chat export. Primary i need raw output because it contains userID and i can linked message with users. But raw output cannot be use with download command so i have to call chat export again for "standard json" which i can use with download command.
I am little afraid from Telegram API ratelimiters and i want to avoid of double calling chat export.
I tried load history.json into app but media structure are implemented as interface in tg.Message so i couldn't use directly this structure and i cannot find better solution. My current solution have own implementation of raw format for parsing and i use same logic as you in tdl but it have fear with compatibility in future and i prefer cleaner solution.

Is possible implement support of raw output into tdl download? Or do you have better idea how i can avoid of double calling of tdl chat export?

**Comment by iyear** [comment]
You're right. I'll try to support it.

**Comment by lukas016** [comment]
@iyear i can implement it. I just want to find a solution together.

Suggested solution:
Create new option --raw-extend, which will add same fields for files as you use in standard export.

**Comment by omnieusza** [comment]
I was going to ask the same question. 
I too do raw export and a "download" export.
I am doing this to avoid downloading the same file twice which might be in several channels.

I am currently using an SQLite DB to track the downloads but I need the File_id and some other metadata (FwdFrom.FromID.ChannelID, FwdFrom.SavedFromPeer.ChannelID, etc.

The raw output might be a bit too much data, would it be possible to add some of these fields to a normal export (--all, --complete)

**Comment by lukas016** [comment]
Yes, it is possible. You can create or extend new format of output without big issue.

Standard golang parser without special settings (https://pkg.go.dev/encoding/json#Decoder.DisallowUnknownFields) ignores json fields which aren't in target. So you can use one file as source for different use cases.

I saw third-party parser in your code where you use mapstructure to remap generic structure (probably map) to structure message.

So i don't expect any problems with extend of format.

But it depends on parsers. If you want to keep compatibility with telegram desktop export format, i recommend avoid extend of normal export format because you won't able to guarantee compatibility with third-party software (in this case telegram desktop app).

Maybe create own format which can be backward compatible with normal export will be better solution.

**Comment by iyear** [comment]
After some consideration, could we do the breaking change? Put raw message into the standard format as an optional field. This will make the output compatible with the Telegram Desktop client's output format.
