### ISSUE TITLE
[BUG] Error `timeout` when attempting to run 2 `tdl` instances at the same time  

### ISSUE THREAD

**Issue by thekoc** [iyear/tdl#303]
**Describe the bug**
Error `timeout` occurs when attempting to run 2 `tdl` instances at the same time  

**To Reproduce**
Open two terminals. Type `tdl chat ls` in one terminal. **BEFORE** it completes, type the same command in the second terminal. It will complain `timeout` instantly.

**Expected behavior**
Two instances should be able to run simultaneously. Although the program supports multithreads when downloading files, only one chat can be exported at the same time using the current command. I tried to run two instance to simultaneously export multiple chats but this error occurs.

**Screenshots**
<img width="291" alt="Screenshot 2023-09-12 at 8 02 37 PM" src="https://github.com/iyear/tdl/assets/15809388/f1d45002-07d7-4942-b671-7a4ad19f4ce7">

**Version:**
Version: 0.9.8
Commit: 79f38ec
Date: 2023-09-07T11:18:36Z

go1.19.12 darwin/amd64

**Additional context**
It seems like there has something to do with the `data.kv` file. I tried to create a fake HOME folder and copy .tdl there then set different $HOME variable for two instances and the error disappears. Not sure if it's intended.

**Comment by iyear** [comment]
Indeed, tdl uses the embedded database https://github.com/etcd-io/bbolt, which does not support multi-process concurrent operations. Another option is to use other C/S architecture databases. WDYT?

**Comment by thekoc** [comment]
> Indeed, tdl uses the embedded database https://github.com/etcd-io/bbolt, which does not support multi-process concurrent operations. Another option is to use other C/S architecture databases. WDYT?

Hi, first let me thanks for your wonderful work. The program is the most reliable and powerful telegram downloader I've tried so far. 

As for the lock problem,  I could list some reasons why multi-instance `tdl` should be supported.

1. Exporting multiple (large) chats at the same time. (It is unachievable for now)
2. Start a new download while the previous download has not been finished.
3. Monitoring new messages and download automatically (It would require a "monitoring instance" and a "download instance"

Certainly changes to the database would bring some extra work so I think it's essentially depends on whether you feel it worths the effort. You might be interested in this file database [nutsdb](https://github.com/nutsdb/nutsdb). It's seemingly supports multi-process access. ([See](https://github.com/nutsdb/nutsdb/issues/100))

Or you could consider close the database every time the write/read finishes and reopen it when needed to prevent long occupation? Because the database seems to be r/w not very often so the costs are negligible?

**Comment by iyear** [comment]
Yes, it's necessary to support multiple instances. Thanks for your reasons and suggestions.

For nutsdb, it doesn't support multi-process access. There is something wrong with that issue.
- https://github.com/nutsdb/nutsdb/blob/master/db.go#L184-L189
- https://github.com/elves/elvish/issues/1222#issuecomment-1255681821

For frequently open/close db, it's expensive. boltdb use mmap/munmap syscall to operate db file. Getting peers data will frequently open the db.

Maybe we still need a C/S key-value database even relational db like MySQL/PostgresQL/etc.

**Comment by iyear** [comment]
Fixed in v0.14.0
