### ISSUE TITLE
Is it possible to implement retries for failed uploads parts

### ISSUE THREAD

**Issue by divyam234** [iyear/tdl#304]
Instead of using gotd native uploader  why can't   a uploder be implemented which takes care of uploading failed parts or event wait for it to resume connection to telegram servers , in current scenerio gotd cancels the whole context if the error is not  of flood type which disrupts the whole upload process.

Instead of passing rpc instance to Uploader Interface   pass  Telegram Client instance  so when  during uploading  individual parts  if engine is closed somehow   just reconnect client  and redo the upload  for that part  as rpc instance doesn't expose reconnect function. 

This will require custom Uploder maybe in tdl itself.

**Comment by iyear** [comment]
Can we impl a retries middleware and pass it to ?https://github.com/iyear/tdl/blob/d3c02afe24b408f58cdcc58d12b1a8db82d02e65/pkg/dcpool/dcpool.go#L34

**Comment by divyam234** [comment]
@iyear  Yeah this looks good invoking UploadSaveBigFilePart  or UploadSaveFilePart  directly here could work .

**Comment by divyam234** [comment]
also https://github.com/gotd/td/blob/cf0eed78e93cea5fe7843bd9da0be130ed53784d/telegram/uploader/big.go#L35 problem is here if  engine is closed just reconnect itself here.

**Comment by divyam234** [comment]
I tired with ```engine forcibly closed``` this error uploading doesn't fail but there is slight speed drop off which is obvious.

**Comment by iyear** [comment]
Please upgrade to [v0.13.0](https://github.com/iyear/tdl/releases/tag/v0.13.0) and feel free to reopen the issue if you have any questions.
