### ISSUE TITLE
Using TDL upload 16:9 video will be transformed into a 1:1 video

### ISSUE THREAD

**Issue by ASIjacket** [iyear/tdl#31]
![image](https://user-images.githubusercontent.com/26643085/192304783-3b1b0500-aa61-4e3c-b9f6-1503fb009163.png)

tdl_Linux_64 0.21
Debian 10

**Comment by iyear** [comment]
The current upload command does not get the duration and resolution of the video.

Considering that `upload` is not an overly used command (normal users are limited to 5M/s, which can usually be reached by official clients), the early development focus will not be on `upload`.

This will be optimized in a future release:)

**Comment by ASIjacket** [comment]
Thanks for your reply.

In my way, TDL may be a better choice for command line users.

I've tried some upload tools based on Telegram-API (using api-id), but all of them have a speed limit for premium users. Except for TDL. Besides, Telegram_CLI doesn't work well in the command line.

Faster upload may be a good future for TDL. Except for an enhanced version :)
