### ISSUE TITLE
[Feat] Downloading a file not from a message, but from a link in a message

### ISSUE THREAD

**Issue by 40OIL** [iyear/tdl#317]
The bot I needed stopped sending files to the group in messages, and started giving out buttons with links; The structure inside the message is something like this:

```
<something-at-the-beginning>

"Media":null,
"ReplyMarkup":{"Rows":[
   {"Buttons":[
      {"Text":"Скачать у бота","URL":"https://t.me/1111111111_bot?start=10090"}]},
   {"Buttons":[
      {"Text":"Скачать с сайта ??","URL":"https://2222222222.ru/book/10090"}]}]},

<something-at-the-end>
```

"Скачать с сайта" = "Download from the site"
?? - picture U+1F310 "Globe With Meridians" on the button, in unicode it looks like codes F0 9F 8C 90

Suggested Solution
You can take the link from the message with the button "Download from the site ??" and download the file from this link. But the site requires authorization through Telegram, so it’s not yet clear to me whether I can download it like that.

You can also call it in the default browser (authorization is already there). Then the browser will do everything.

**Comment by iyear** [comment]
This doesn't seem to be the goal of tdl, and it's hard to recognize whether a link needs to be downloaded or not. You may choose to export the message using `tdl export --raw` and extract the link using the `jq` command before proceeding further.

**Comment by 40OIL** [comment]
great idea!
Tell me then how to limit the output of tdl export --raw ?

`tdl chat export -c 1111111111 --raw -T id -i 98746 -o output8.json`
and
`tdl chat export -c 1111111111 --raw --topic 98746 -o output10.json`
displays an empty list of messages

`tdl chat export -c 1111111111 --raw -T last -i 1 -o output9.json`
displays the latest message with an attached file

**Comment by iyear** [comment]
Try `tdl chat export -c 1111111111 --raw -T id -i 98746,98746 -o output8.json`

**Comment by 40OIL** [comment]
> tdl chat export -c 1111111111 --raw -T id -i 98746,98746 -o output8.json

displays an empty list of messages

`{"id":1111111111,"messages":[]}`

**Comment by 40OIL** [comment]
timestamp of last message 98024 with attachment = 1695238251

`tdl chat export -c 1111111111 --raw -T time -i 1695238251,1695817127 -o output12.json`
displays 1 message with attachment

`tdl chat export -c 1111111111 --raw -T time -i 1695239251,1695817127 -o output12.json`
_start timestamp 1695239251, taken more than 1695238251_
displays an empty list

**Comment by iyear** [comment]
This is correct, the time type exports messages sent at times between a and b. The larger start time means that the time of 98024 will not be included.

**Comment by iyear** [comment]
My mistake. You should add `--all` flag to export non-media messages.

**Comment by 40OIL** [comment]
it worked!
`export --all --raw `works with all search parameters, and `-T last`, and `-T id`, and all others

**Comment by 40OIL** [comment]
One problem was discovered - Telegram desktop 4.10 x64 stops receiving (or displaying?) fresh messages, even after running `tdl chat export -c 1111111111 --all --raw -T id -i 3333 -o output.json`
After restarting Telegram, all these messages arrive and are visible.

Previously I had a script that ran
`tdl chat export -c 1111111111 -T id -i 3333 -o output.json`
`tdl dl -f output.json --skip-same`
and after them everything worked fine

**Comment by iyear** [comment]
https://github.com/iyear/tdl#troubleshooting

But ensure you can re-login the desktop client!

**Comment by 40OIL** [comment]
I re-logged out, it didn't help.
after running tdl with the --all --raw parameters in the telegram client, I have 2 reaction options:
1) when you click on any group or chat, an empty window with a background opens instead of messages, or
2) it only shows old messages, it doesn’t download or show new ones.

**Comment by iyear** [comment]
It means re-login with tdl. `tdl login` and  select YES

**Comment by 40OIL** [comment]
after I logged out of the Telegram desktop client and logged in again, my tdl refused to work without
`tdl login -n MyName -d c:\path\to\TelegramDesktop`
Is there anything else that needs to be done?
