### ISSUE TITLE
[Feat] 下载器直接推送至Aria2 RPC地址

### ISSUE THREAD

**Issue by lilyblessing** [iyear/tdl#319]
Please describe your feature request
现在的是`以 HTTP 服务器的形式提供文件下载`
可否直接向Aria2推送下载请求，`http://localhost:6800/jsonrpc`，对于多个文件下载这是比较方便的方式。
当然如`Motrix`的默认端口不同`16800`，希望可以交给用户自行配置

**Comment by iyear** [comment]
It doesn't look like it's tdl's responsibility.
