### ISSUE TITLE
[BUG]  wget: unrecognized option '--show-progress'

### ISSUE THREAD

**Issue by 0xddy** [iyear/tdl#320]
Target version: v0.11.0 
Downloading tdl from https://github.com/iyear/tdl/releases/download/v0.11.0/tdl_Linux_64bit.tar.gz 
wget: unrecognized option '--show-progress' 
Usage: wget [OPTION]... [URL]... 
Try `wget --help' for more options.

**Comment by iyear** [comment]
What's your system info? Maybe your wget version is too old.

**Comment by 0xddy** [comment]
@iyear 
new err：callback: validate domain: is empty

./tdl dl -u https://t.me/c/123/44/123-n koa

**Comment by iyear** [comment]
`./tdl dl -u https://t.me/c/123/44/123 -n koa`

**Comment by 0xddy** [comment]
@iyear  就是这样写的，上面是复制的搞错了  -n 前后有空格

**Comment by 0xddy** [comment]
```
[root@sweet-poll-5 ~]# ./tdl dl -u https://t.me/c/1581392526/44/3321 -n koa
callback: validate domain: is empty


```

**Comment by iyear** [comment]
Try `https://t.me/c/1581392526/3321`. This looks like a bug, tdl is not handling the message links copied from topic correctly.

**Comment by iyear** [comment]
Please upgrade to v0.11.1 and feel free to reopen the issue if you have any questions.
