### ISSUE TITLE
[BUG] group: task readLoop: read: read: read intermediate: read length: EOF

### ISSUE THREAD

**Issue by orbit666** [iyear/tdl#321]
> [#######################################################.........] [3m0s; 2.47 MB/s]
Download aborted.
group: task readLoop: read: read: read intermediate: read length: EOF
> 

![image](https://github.com/iyear/tdl/assets/63085968/4118d433-dea3-43cf-86b0-248c2de78588)

This error will occur during downloading, causing the download to be interrupted.

**Comment by iyear** [comment]
https://github.com/iyear/tdl/issues/158#issuecomment-1551116053

**Comment by orbit666** [comment]
Thank you very much for your answer. The problem is solved.
