### ISSUE TITLE
[BUG] Actual hyperlinks not extracted from markdown style linked text inside messages

### ISSUE THREAD

**Issue by huuck** [iyear/tdl#332]
**Describe the bug**
Message content does not include hyperlinks and any other Markdown style text.

**To Reproduce**
run `tdl export -c XXX -n YYY --raw --with-content --all` for a channel that has messages that have been linked like this `[Link text](https://website-name.com)`. The message contents will only include `Link text`.

**Expected behavior**
Get the full markdown style link and link text.

**Screenshots**
n/a

**Version:**
0.9.2

**Additional context**
n/a

**Comment by iyear** [comment]
This is not an important duty of tdl. You can export JSON with the `--raw` flag and look at the `Entities` field of the `Message` and parse it yourself!

**Comment by huuck** [comment]
My bad, I have completely missed this. The extra fields seem to do the trick!
