### ISSUE TITLE
[BUG] callback: get file: get next chunk: invoke pool: rpcDoRequest: engine was closed

### ISSUE THREAD

**Issue by 727729853** [iyear/tdl#336]
Sometimes it happens, sometimes it doesn't

**Comment by MissingTwins** [comment]
I think the problem related to the threads and tasks, I had to append  `-t 1 -l 1` otherwise it will fail every time.

**Comment by himonkiy** [comment]
> I think the problem related to the threads and tasks, I had to append `-t 1 -l 1` otherwise it will fail every time.

Even though I used '-l 1 -t 1', I still encounter issues. I believe it's highly likely a network problem, possibly due to the unstable proxy address I'm using.

**Comment by iyear** [comment]
Please upgrade to [v0.13.0](https://github.com/iyear/tdl/releases/tag/v0.13.0) and feel free to reopen the issue if you have any questions.
