### ISSUE TITLE
[BUG] callback: resolve: invoke pool: rpcDoRequest: rpc error code 400: USERNAME_INVALID

### ISSUE THREAD

**Issue by darkuser4455** [iyear/tdl#341]
This bug happens when i tried to download content from a channel 

to get the error you need to try to download content from https://t.me/ATTACHED_GIF/309451

I think it is due to _ (underscore) 

This is only Group that this tool cannot download content from 
Developer Keep this up this is a great tool 
![Capture](https://github.com/iyear/tdl/assets/147382984/50354cdd-8fa8-44e1-a2e3-ee15a764e4f4)

**Comment by iyear** [comment]
It has nothing to do with underscores, it depends on whether the username is accessible to your currently logged in account or not. On my side, ATTACHED_GIF doesn't exist.

**Comment by Reaper176** [comment]
I am also having this issue. I login just fine with the only one singular account that I use but it does not allow me to download from a room that I otherwise have access to on the account.

**Comment by iyear** [comment]
Unfortunately, I can't reproduce it. Is there any way for me to add them and debug.
