### ISSUE TITLE
[Feat] formatDate function support custom pattern

### ISSUE THREAD

**Issue by lw900925** [iyear/tdl#343]
Please improve `formatData` function to support custom pattern.

eg:
```
{{ .FileName }}_{{ formatDate .DownloadDate 'yyyy-MM-dd HH:mm:ss.SSS'}}_{{ .FileSize }}
```

or some other usage.

Thanks!!!

**Comment by iyear** [comment]
Upgrade to v0.12.0 and see new function def: https://docs.iyear.me/tdl/guide/template/

Feel free to reopen the issue if you have any question.
