### ISSUE TITLE
[BUG] 不能下载了

### ISSUE THREAD

**Issue by ChastityS** [iyear/tdl#345]
<img width="664" alt="1232" src="https://github.com/iyear/tdl/assets/114201336/5c851fc7-f0dc-49d0-8cbe-8b1c80f9bd90">
不知道什么无法进行下载

**Comment by iyear** [comment]
删除takeout参数，目前不知道takeout session无法请求的原因

**Comment by ChastityS** [comment]
逆天 真的好了可以下载了 谢谢大佬
