### ISSUE TITLE
callback: parse message id: strconv.Atoi: parsing "": invalid syntax

### ISSUE THREAD

**Issue by Reaper176** [iyear/tdl#348]
**Describe the bug**
[A clear and concise description of what the bug is.](callback: parse message id: strconv.Atoi: parsing "": invalid syntax)

**To Reproduce**
tdl dl -n MYUSERNAME -u https://web.telegram.org/MYUSERNAME/#-1001503406491

**Expected behavior**
It start downloading

**Screenshots**
If needed I will happily provide these.

**Version:**
Version: 0.12.0
Commit: 9b49746
Date: 2023-10-15T10:20:59Z

go1.19.13 linux/amd64

**Additional context**

**Comment by iyear** [comment]
https://docs.iyear.me/tdl/guide/download/#from-links
