### ISSUE TITLE
[Feat] Add tdl into brew

### ISSUE THREAD

**Issue by asjdf** [iyear/tdl#352]
Hi, there are two solutions to make the TDL support install via brew.

1. create the formulae under your personal account.
2. use official formulae.

Joining the official library makes it easier for users to install, and creating personal formulae makes it easier to update. 

I'd be happy to help you implement this feature (really just a few config file changes).

Thank you for bringing us such a great project❤️.

**Comment by iyear** [comment]
I prefer to join the official repository. Thanks for your contribution:)

**Comment by iyear** [comment]
It looks like the formulas in homebrew-core have to be built from source. But the formulas generated by goreleaser will download directly from GitHub releases. 🤔

**Comment by asjdf** [comment]
I think you should be able to open a branch of homebrew-core under your account, then we can let goreleaser commit to the repository, and start a PR to homebrew-core.

**Comment by iyear** [comment]
The question is: https://docs.brew.sh/Acceptable-Formulae#we-dont-like-binary-formulae

The official formula only accepts compiling from source code and cannot download pre-built binary files from releases. You can compare the differences between the self-owned formula of goreleaser and the formula submitted to the official one.

- homebrew-core: https://github.com/Homebrew/homebrew-core/blob/master/Formula/g/goreleaser.rb
- self-owned: https://github.com/goreleaser/homebrew-tap/blob/master/Formula/goreleaser.rb

**Comment by iyear** [comment]
https://github.com/iyear/tdl/pull/386
