### ISSUE TITLE
[BUG] callback: get file: get next chunk: invoke pool: rpcDoRequest: retryUntilAck: retry limit reached after 5 attempts

### ISSUE THREAD

**Issue by Superoldman96** [iyear/tdl#353]
callback: get file: get next chunk: invoke pool: rpcDoRequest: retryUntilAck: retry limit reached after 5 attempts

**Comment by iyear** [comment]
Please upgrade to [v0.13.0](https://github.com/iyear/tdl/releases/tag/v0.13.0) and feel free to reopen the issue if you have any questions.
