### ISSUE TITLE
[BUG]（maybe not）about login 关于登录错误

### ISSUE THREAD

**Issue by jiuyuanlvbu** [iyear/tdl#361]
**win10平台，我登录时候出错**
我使用的资源是最新的（V.0.12.1），[tdl_Windows_64bit.zip](https://github.com/iyear/tdl/releases/download/v0.12.1/tdl_Windows_64bit.zip)，在cmd输入登录代码时候报错。
---
代码及报错信息如下:
```
C:\Users\admin>tdl login -n quickstart -d E:/tdl/TelegramDesktop
WARN: If data exists in the namespace, data will be overwritten
Importing session from desktop client: E:/tdl/TelegramDesktop
open key_data: file "key_data" not found
```

我查看了代码，发现大概是“[tdl](https://github.com/iyear/tdl/tree/e15a721404fb9fdf0d6484e9f4a78211a1661d15)/[app](https://github.com/iyear/tdl/tree/e15a721404fb9fdf0d6484e9f4a78211a1661d15/app)/[login](https://github.com/iyear/tdl/tree/e15a721404fb9fdf0d6484e9f4a78211a1661d15/app/login)/desktop.go”这个文件里的50行提及的错误（我仅仅粗略读了代码，不一定是这里）
`accounts, err := tdtdesktop.Read(appendTData(desktop), []byte(opts.Passcode))
	if err != nil {
		return err
	}`

**To Reproduce**
- cmd 输入 登录代码 `tdl login -n quickstart -d E:/tdl/TelegramDesktop`
- 报错
```WARN: If data exists in the namespace, data will be overwritten
Importing session from desktop client: E:/tdl/TelegramDesktop
open key_data: file "key_data" not found
```

**Expected behavior**
我期望是正常登录不报错。

**Screenshots**
no.

**Version:**

```
Version: 0.12.1
Commit: 20d7705
Date: 2023-10-23T16:14:46Z

go1.19.13 windows/amd64

```
**Additional context**
我使用telegram的是官方桌面版本，我注意到报错信息里提到“key_data”，我到软件安装目录（\Telegram Desktop\tdata）里查看发现有只有一个“**key_datas**”的文件。这个报错说的缺失的“key_data”到底是什么，我该如何解决？

**Comment by iyear** [comment]
tdl目录下是你的 Telegram 桌面安装路径吗？key_data 找不到说明你给的路径有问题

**Comment by kidsoyo** [comment]
> ## **win10平台，我登录时候出错**
> 我使用的资源是最新的（V.0.12.1），[tdl_Windows_64bit.zip](https://github.com/iyear/tdl/releases/download/v0.12.1/tdl_Windows_64bit.zip)，在cmd输入登录代码时候报错。
> 代码及报错信息如下:
> 
> ```
> C:\Users\admin>tdl login -n quickstart -d E:/tdl/TelegramDesktop
> WARN: If data exists in the namespace, data will be overwritten
> Importing session from desktop client: E:/tdl/TelegramDesktop
> open key_data: file "key_data" not found
> ```
> 
> 我查看了代码，发现大概是“[tdl](https://github.com/iyear/tdl/tree/e15a721404fb9fdf0d6484e9f4a78211a1661d15)/[app](https://github.com/iyear/tdl/tree/e15a721404fb9fdf0d6484e9f4a78211a1661d15/app)/[login](https://github.com/iyear/tdl/tree/e15a721404fb9fdf0d6484e9f4a78211a1661d15/app/login)/desktop.go”这个文件里的50行提及的错误（我仅仅粗略读了代码，不一定是这里） `accounts, err := tdtdesktop.Read(appendTData(desktop), []byte(opts.Passcode)) if err != nil { return err }`
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> * cmd 输入 登录代码 `tdl login -n quickstart -d E:/tdl/TelegramDesktop`
> * 报错
> 
> ```
> Importing session from desktop client: E:/tdl/TelegramDesktop
> open key_data: file "key_data" not found
> ```
> 
> **Expected behavior** 我期望是正常登录不报错。
> 
> **Screenshots** no.
> 
> **Version:**
> 
> ```
> Version: 0.12.1
> Commit: 20d7705
> Date: 2023-10-23T16:14:46Z
> 
> go1.19.13 windows/amd64
> ```
> 
> **Additional context** 我使用telegram的是官方桌面版本，我注意到报错信息里提到“key_data”，我到软件安装目录（\Telegram Desktop\tdata）里查看发现有只有一个“**key_datas**”的文件。这个报错说的缺失的“key_data”到底是什么，我该如何解决？

tdl login -n quickstart -d "E:\tdl\TelegramDesktop"

**Comment by Parantric** [comment]
我也是遇到了这种问题，还没找到解决方法，请问你的这个问题解决了吗？

**Comment by kidsoyo** [comment]
> 我也是遇到了这种问题，还没找到解决方法，请问你的这个问题解决了吗？

路径加引号

**Comment by Parantric** [comment]
> tdl login -n quickstart -d "E:\tdl\TelegramDesktop"

![Snipaste_2024-01-20_10-04-24](https://github.com/iyear/tdl/assets/104410710/c14f3896-5f81-42b9-bce6-0e637d4dba8d)
没用，我是用的最新版的 64 位，windows11 系统，这个问题一直过不去。

**Comment by kidsoyo** [comment]
是tg版本问题么，我是win10 x64，tg官方版，没问题呀
![image](https://github.com/iyear/tdl/assets/35915585/71152d67-ddb1-4c5b-8ec0-225d0d72099e)

**Comment by Parantric** [comment]
> 是 tg 版本问题么，我是 win10 x64，tg 官方版，没问题呀 ![image](https://private-user-images.githubusercontent.com/35915585/298248667-71152d67-ddb1-4c5b-8ec0-225d0d72099e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MTg3NDAsIm5iZiI6MTcwNTcxODQ0MCwicGF0aCI6Ii8zNTkxNTU4NS8yOTgyNDg2NjctNzExNTJkNjctZGRiMS00YzViLThlYzAtMjI1ZDBkNzIwOTllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDAyNDA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4NWZmNTJiZmUzN2M0YWYyNGRiZjAyMTUzZDZhNTY2MzcxNWY5ZGJiYmFjNjZiYzhjNmExYTUzMzE0ZTBkOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b2nRbOjKmu3M6YgEh4JanmznVPF9BKIDa1PsXbCG3L8)

重装了一下 tg 还是这个错误，不知道为什么... ...无语了

**Comment by iyear** [comment]
@Parantric 客户端是否设置了 passcode? 如果设置了需要加上 `-p YOUR_PASSCODE`

**Comment by Parantric** [comment]
> @Parantric* 客户端是否设置了 passcode? 如果设置了需要加上 `-p YOUR_PASSCODE`

十分感谢，确实是这个问题，我设置了「锁屏密码」。文档中提到过这个参数「YOUR_PASSCODE」标注说是“本地密码”，以为是 TG 的 username 和 password 的这个 password 的，问题已解决，谢谢！
