### ISSUE TITLE
[BUG] Download aborted: get file: get next chunk: invoke pool: rpcDoRequest: retryUntilAck: engine forcibly closed: context canceled

### ISSUE THREAD

**Issue by KingFuRong** [iyear/tdl#364]
**Describe the bug**
using tdl -n Scorpio dl -f result.json --desc -e jpg,png,mp4 --reconnect-timeout 0 --skip-same -l 4
just download No more than 10s Error is thrown

**To Reproduce**
open cmd
input tdl -n Scorpio dl -f result.json --desc -e jpg,png,mp4 --reconnect-timeout 0 --skip-same -l 4

**Expected behavior**
download normal

**Screenshots**
![image](https://github.com/iyear/tdl/assets/119987402/a22fa7ff-6189-427e-bb57-7121dbe85719)

**Version:**
v0.12.1

**Additional context**

**Comment by ProuHan** [comment]
Download aborted: get file: get next chunk: invoke pool: rpcDoRequest: retryUntilAck: engine forcibly closed: context canceled
这是个啥问题？
用的是
tdl dl -n quickstart -f tdl-export.json --proxy socks5://localhost:7890 --reconnect-timeout 0 --continue

**Comment by taynpg** [comment]
我也是这个问题

**Comment by nikkoozz** [comment]
我也遇到了这个问题

**Comment by iyear** [comment]
Please upgrade to [v0.13.0](https://github.com/iyear/tdl/releases/tag/v0.13.0) and feel free to reopen the issue if you have any questions.
