### ISSUE TITLE
[BUG] Misleading Error Message for Download Failure Due to Insufficient Directory Write Permissions

### ISSUE THREAD

**Issue by HisAtri** [iyear/tdl#375]
**Describe the bug**
When attempting to download files in Linux using the "-d" parameter to specify a file directory, a misleading error message "rpc error code -503: Timedout" is displayed if the specified directory lacks write permissions. This error message suggests a network issue, leading users to take a misleading and troubleshoot their network configuration.

**To Reproduce**
Use the "-d" parameter to specify a directory without write permission.

**Expected behavior**
The error message should accurately reflect the root cause of the download failure, which in this case is insufficient write permissions on the specified directory. Users should be informed that the download failed due to write permission issues.

**Screenshots**

**Version:**
[v0.12.1](https://github.com/iyear/tdl/releases/tag/v0.12.1)

**Additional context**
Upon granting write permissions to the current user group using chmod, the issue was resolved, confirming that the lack of write permissions on the directory was indeed the cause of the download failure.

-----------
"rpc error code -503: Timedout"可能由参数"-d"指定的目录缺少写入权限导致，使用chmod给予写入权限即可解决。

**Comment by iyear** [comment]
Please upgrade to [v0.13.0](https://github.com/iyear/tdl/releases/tag/v0.13.0) and feel free to reopen the issue if you have any questions.
