### ISSUE TITLE
[Feat] 自动获取消息并命名文件夹,将同一消息文件放入文件夹中

### ISSUE THREAD

**Issue by zhangzongwan** [iyear/tdl#387]
Please describe your feature request
telegram中文件(视频和图片)是以消息为分割的,我希望下载多文件时能够按照不同的消息对文件进行分类(例如创建不同文件夹对应不同消息的文件),而不是现在全下载到一个文件夹中分不清文件是来源于哪个消息的,不知道能否做到.
The files (videos and images) in Telegram are divided by messages. I hope that when downloading multiple files, they can be categorized according to different messages (for example, creating different folders corresponding to files from different messages), instead of currently downloading all files into one folder where it is unclear which message they originate from. I wonder if it's possible to achieve this.

**Comment by iyear** [comment]
Use https://docs.iyear.me/tdl/en/guide/template/ to define file names distinguished by messages, and then you can write a small script to archive these files yourself. tdl should not implement overly customized requirements.

**Comment by zhangzongwan** [comment]
thanks a lot

**Comment by zhangzongwan** [comment]
额外的问题:消息id与对话id有何不同,其次有没有办法获得消息或对话的内容.
extra question:what is the different between message id and diaglog id,and if it is possible to get the content of message or diaglog?
