### ISSUE TITLE
[BUG] export chat not working

### ISSUE THREAD

**Issue by mjdalmaazmi** [iyear/tdl#396]
hello
when I try to export chats it's failed although other command such as "tdl dl -n zg -u https://t.me/telegram/193" is working without any issue

<img width="557" alt="Screenshot 2023-12-01 at 2 20 48 AM" src="https://github.com/iyear/tdl/assets/126062760/a14b3b15-218f-42e5-bd91-cf164dc9a9fd">

**Comment by iyear** [comment]
you should replace CHAT with your specific chat.
