### ISSUE TITLE
登录错误

### ISSUE THREAD

**Issue by connorzhuang** [iyear/tdl#397]
你好，有个问题就是我现在一个账号登录过了，这个session存储到etcd后，之后登录是拿到etcd中的session进行登录，但是偶尔会出现一个问题，就是一直登录不了，一直卡在tgc.runwithAuth。如果我把这个账号的session删除之后，再进行验证码登录，又可以正常登录了，希望可以帮我解解惑

**Comment by connorzhuang** [comment]
是的

**Comment by iyear** [comment]
Sorry, I can't debug a bug with only a description and no access to the source code.
