### ISSUE TITLE
[BUG] 终端一直刷新CPU: 0.00% Memory: 28.22 MB Goroutines: 41

### ISSUE THREAD

**Issue by yy16** [iyear/tdl#399]
**Describe the bug**
下载时候，终端会一直刷新CPU: 0.00% Memory: 29.61 MB Goroutines: 41
CPU: 0.00% Memory: 29.61 MB Goroutines: 41
CPU: 0.00% Memory: 29.61 MB Goroutines: 41
CPU: 0.00% Memory: 29.61 MB Goroutines: 41
这样子

**To Reproduce**
Steps to reproduce the behavior: downloading

**Expected behavior**

**Screenshots**
![Snipaste_2023-12-03_20-33-28](https://github.com/iyear/tdl/assets/67261579/0e4b55c2-0689-4b1d-86c0-b56af72c7c07)
![Snipaste_2023-12-03_20-33-44](https://github.com/iyear/tdl/assets/67261579/14789b78-2238-40f5-8802-7eadd9b45433)

**Version:**
Version: 0.13.0
Commit: 6c49808
Date: 2023-11-21T15:36:00Z

go1.19.13 windows/amd64

**Additional context**

**Comment by Indranil012** [comment]
> The page is not wide enough. The next version will optimize the adaptive size.

Still I can reproduce the issue on termux.
