### ISSUE TITLE
Support channel comment link

### ISSUE THREAD

**Issue by iyear** [iyear/tdl#40]

**Comment by jhdxr** [comment]
Hi can I check if it's still working? I tried just now and tdl download the media from related main post/message instead of the comment itself.

**Comment by iyear** [comment]
@jhdxr Is `https://t.me/opencfdchannel/4434?comment=360409` the kind of link you're talking about? Sorry, it's not supported yet. The closure of this issue may have been a mistake.

You can use [X](https://docs.iyear.me/tdl/guide/tools/export-messages/#from-topicreplies) as an alternative.

https://t.me/opencfdchannel/4434?comment=360409 will be supported in next version.

**Comment by jhdxr** [comment]
Yeah that's what I'm asking for. Thanks for the prompt update and work.

**Comment by iyear** [comment]
Please upgrade to v0.12.0 and feel free to reopen the issue if you have any question.
