### ISSUE TITLE
[BUG]  error when downloading retry limit reached after 10 attempts

### ISSUE THREAD

**Issue by yy16** [iyear/tdl#400]
**Describe the bug**
error when downloading

**To Reproduce**

**Expected behavior**

**Screenshots**
![Snipaste_2023-12-04_20-14-03](https://github.com/iyear/tdl/assets/67261579/bf98c4b1-85b0-4713-a9ee-235138584d58)

**Version:**
latest

**Additional context**

**Comment by iyear** [comment]
Run with `--debug` flag and find log in `~/.tdl/log/latest.log`. Search `retry middleware` and paste some of them.

**Comment by iyear** [comment]
Can you reproduce it again? I can't find related log in the log file. retry middleware means some server-side errors.

**Comment by iyear** [comment]
No other reasons, the retries are occurring because the server's acknowledgment cannot be received. Under normal circumstances, this should not happen. Try changing the proxy or check if the network environment is blocking certain network packets.
