### ISSUE TITLE
[Feat] Download several files from a channel at once, using name as a parameter

### ISSUE THREAD

**Issue by Lciron** [iyear/tdl#402]
It would be interesting if you could download several files from the same channel at once, using the name of the message as a parameter, for example:

A concert channel has hundreds of shows, but I want to download all the Guns n Roses shows, so I would put a filter or parameter to only download everything that has the name Guns n Roses.

**Comment by iyear** [comment]
Please combine `tdl chat export --filter` and `tdl dl -f` to reach it.

Ref:
- https://docs.iyear.me/tdl/guide/tools/export-messages/
- https://docs.iyear.me/tdl/guide/download/#from-json
