### ISSUE TITLE
[Feat]  Can you spare some time to write an example of sending encrypted chat messages

### ISSUE THREAD

**Issue by connorzhuang** [iyear/tdl#407]
I encrypted the message according to the official document, and the method did not display an error. However, the other party did not receive the message, which may be due to the incorrect encryption method

**Comment by iyear** [comment]
What is this requirement and can you provide more details? I don't know why tdl needs this feature.

**Comment by connorzhuang** [comment]
Launching secret chats on the Mac client may also result in the other party not receiving information, so I want to try using APIs to verify this issue

**Comment by iyear** [comment]
It's about tdl?

**Comment by connorzhuang** [comment]
I have added many features to the TDL framework, and secret chatting is something I have been researching recently

**Comment by iyear** [comment]
I cannot see the source code, so I can do nothing. The issue section is used to track bugs and features, not for technical consultations.
