### ISSUE TITLE
file forwarding from private restricted group not working 

### ISSUE THREAD

**Issue by anaschaudhary33** [iyear/tdl#408]
The command ```tdl -n ilog1 forward --from https://t.me/c/2033096998/3905/3919?single``` do the progress successfully but it actually doesn't forward the file, I can't see the file in "saved message".

**Version:**
Version: 0.13.0
Commit: 6c49808
Date: 2023-11-21T15:36:00Z

go1.19.13 linux/arm64

**Comment by anaschaudhary33** [comment]
[latest.log](https://github.com/iyear/tdl/files/13583253/latest.log)

**Comment by iyear** [comment]
Fixed in v0.13.2
