### ISSUE TITLE
[BUG] Cannot Log In and List Chats

### ISSUE THREAD

**Issue by vivabonito** [iyear/tdl#409]
**Describe the bug**

Cannot get TDL to work. Used v0.13.1 and v0.13.0. Tried on Linux (Kali) and Windows 10 and neither work. On Linux, login does not work at all. On Windows 10, login is successful, but then no command (i.e. tdl chat ls) works. Error is same on both Linux and Windows (Error: open key_data: file "key_data" not found).

**To Reproduce**

1. Linux:

```
└─$ tdl login -n telegram_username-d /usr/bin/telegram-desktop
WARN: If data exists in the namespace, data will be overwritten
Importing session from desktop client: /usr/bin
Error: open key_data: file "key_data" not found
open key_data:
    github.com/gotd/td/session/tdesktop.ReadFS
        github.com/gotd/td@v0.89.0/session/tdesktop/tdesktop.go:35
  - file "key_data" not found:
    github.com/gotd/td/session/tdesktop.open
        github.com/gotd/td@v0.89.0/session/tdesktop/file.go:60

└─$ whereis telegram-desktop
telegram-desktop: /usr/bin/telegram-desktop /usr/share/man/man1/telegram-desktop.1.gz
```

2. Windows

```
λ tdl login -n telegram_username -d "C:\Users\user\AppData\Roaming\Telegram Desktop"
WARN: If data exists in the namespace, data will be overwritten
Importing session from desktop client: C:\Users\user\AppData\Roaming\Telegram Desktop

? Choose a user id: 1260491107
Import 1260491107 successfully to 'telegram_username' namespace!
? Do you want to logout existing desktop session? No

λ tdl chat ls
Error: open kv:
    github.com/iyear/tdl/app/internal/tgc.New
        github.com/iyear/tdl/app/internal/tgc/tgc.go:47
  - namespace is required:
    github.com/iyear/tdl/pkg/kv.(*legacy).open
        github.com/iyear/tdl/pkg/kv/legacy.go:111
```

**Expected behavior**

tdl is supposed to log into specified Telegram user account and list existing chats using "tdl chat ls" command as per documentation.

**Screenshots**

**Version:**
Run `tdl version` in terminal

v0.13.0 (Linux) and v0.13.1 (Windows)

**Additional context**

Please help fix this issue.

**Comment by iyear** [comment]
For Linux:
Try `tdl login -n telegram_username` without `-d`, it will automatically detect data path.
If it still cannot find the data path for Telegram Desktop, try searching for the 'tdata' directory and specify it as the path.

For Windows:
> You should set the namespace when each command is executed

https://docs.iyear.me/tdl/guide/global-config/#-n--ns
