### ISSUE TITLE
How to Download Entire Chat with Media from Specific User

### ISSUE THREAD

**Issue by vivabonito** [iyear/tdl#412]
Hi, I have used the following command:

```
└─$ tdl -n telegram_username chat ls | grep "username_I_am_looking_for"
1320258929 private  username_I_am_looking_for

└─$ tdl -n telegram_username chat export -c CHAT --topic 1320258929 --with-content
Error: callback: failed to get peer: resolve: retry middleware skip: rpcDoRequest: rpc error code 400: USERNAME_NOT_OCCUPIED
callback:
    github.com/gotd/td/telegram.(*Client).Run.func3
        github.com/gotd/td@v0.89.0/telegram/connect.go:151
  - failed to get peer: resolve: retry middleware skip: rpcDoRequest: rpc error code 400: USERNAME_NOT_OCCUPIED
```

I believe the issue is because I am using chat ID (1320258929) as opposed to topic ID (which is 6 digits max). Therefore, I would like to ask how you back up private user chats? I understand that tdl is only for exporting and not backup. In the Telegram Desktop app GUI, you can export each chat with all media and files to machine-readable JSON or human-readable HTML. Is this already implemented in tdl, and if not, can it be in the future? I can help with this if you can point me in the right direction with regard to Telegram API access and API documentation.

Let me know. Thanks.

**Comment by vivabonito** [comment]
The tdl export chat works. Could you please give me an example of how to use tdl dl -f to filter out for chat ID 1320258929 as per example above? Would it be tdl dl -f "1320258929"? Let me know. Thanks.

**Comment by vivabonito** [comment]
Also, I checked the root path (/usr/local/bin/tdl) and home path (~/.tdl) for the chat export after it completed, and could not find it. Do you know where it exports it to by default?

**Comment by iyear** [comment]
You should read the doc. `tdl dl -f` means pass a JSON file instead of filter. `tdl chat export -f` means filter.
