### ISSUE TITLE
pdf file forwarding not working

### ISSUE THREAD

**Issue by anaschaudhary33** [iyear/tdl#414]
When I try to forward from private restricted group the pdf forward doesn't work.(while other media, message forward successfully)
It says "error: empty message content, skip send: 389"

**Version:**
Version: 0.13.0
Commit: 6c49808
Date: 2023-11-21T15:36:00Z

go1.19.13 linux/arm64

**Comment by iyear** [comment]
Can you try it with v0.13.2?

**Comment by anaschaudhary33** [comment]
Same error.
Also text message forwarding is not working in 0.13.2

**Comment by iyear** [comment]
Try v0.13.3

**Comment by anaschaudhary33** [comment]
It's working now.🤗
