### ISSUE TITLE
not download

### ISSUE THREAD

**Issue by always1314** [iyear/tdl#415]
Error: group:
    github.com/gotd/td/internal/mtproto.(*Conn).Run
        github.com/gotd/td@v0.89.0/internal/mtproto/conn.go:214
  - task readLoop:
    github.com/gotd/td/internal/tdsync.(*LogGroup).Go.func1
        github.com/gotd/td@v0.89.0/internal/tdsync/log_group.go:48
  - read:
    github.com/gotd/td/internal/mtproto.(*Conn).readLoop
        github.com/gotd/td@v0.89.0/internal/mtproto/read.go:193
  - read:
    github.com/gotd/td/transport.(*connection).Recv
        github.com/gotd/td@v0.89.0/transport/connection.go:70
  - read intermediate:
    github.com/gotd/td/internal/proto/codec.Intermediate.Read
        github.com/gotd/td@v0.89.0/internal/proto/codec/intermediate.go:73
  - read length:
    github.com/gotd/td/internal/proto/codec.readLen
        github.com/gotd/td@v0.89.0/internal/proto/codec/codec.go:35
  - EOF

**Comment by iyear** [comment]
What's your command? What's your version? Provide detail instead of just an error

**Comment by always1314** [comment]
下载群组的内容，然后报错了 tdl -n dl  --continue --skip-same -f .\tdl-export.json -t 8 --pool 5 -s 262144

**Comment by iyear** [comment]
Try flag `--reconnect-timeout 0`
