### ISSUE TITLE
[BUG]  from macos 

### ISSUE THREAD

**Issue by lupengji** [iyear/tdl#417]
open new  cmd 
/dev/fd/12:1: command not found: Error:
/dev/fd/12:2: no such file or directory: github.com/iyear/tdl/cmd.New.func1
/dev/fd/12:3: no such file or directory: github.com/iyear/tdl/cmd/root.go:57
/dev/fd/12:cd:4: too many arguments
/dev/fd/12:5: no such file or directory: github.com/iyear/tdl/pkg/kv.newLegacy
/dev/fd/12:6: no such file or directory: github.com/iyear/tdl/pkg/kv/legacy.go:42
/dev/fd/12:cd:7: string not in pwd: -

use 
tdl version                                                                                                                       
Error: create kv storage:
    github.com/iyear/tdl/cmd.New.func1
        github.com/iyear/tdl/cmd/root.go:57
  - open db:
    github.com/iyear/tdl/pkg/kv.newLegacy
        github.com/iyear/tdl/pkg/kv/legacy.go:42

**Comment by iyear** [comment]
What's your command? I can't understand your errors.

**Comment by lupengji** [comment]
> What's your command? I can't understand your errors.
use iterm 
when  use "tdl version"  command 
 
Error: create kv storage:
    github.com/iyear/tdl/cmd.New.func1
        github.com/iyear/tdl/cmd/root.go:57
  - open db:
    github.com/iyear/tdl/pkg/kv.newLegacy
        github.com/iyear/tdl/pkg/kv/legacy.go:42
  - timeout

**Comment by David-Azaani** [comment]
hi
I get this response when I want to forward !

**Comment by iyear** [comment]
This means that the database has already been opened and is in use by another tdl process, and currently, only one TDL instance can be kept running.

Multi-instance is already on the roadmap.
