### ISSUE TITLE
Error: open kv:   *****  - namespace is required:

### ISSUE THREAD

**Issue by flyingwasabi** [iyear/tdl#420]
用的是m2 的mac， sonoma的系统
按照教程用一键安装好之后，iwr -useb https://docs.iyear.me/tdl/install.ps1 | iex
用官方客户端登陆。tdl login -n quickstart
再尝试下载视频，tdl dl -u https://t.me/c/198******
但是每次都是报同样的错误，
Error: open kv:
    github.com/iyear/tdl/app/internal/tgc.New
        github.com/iyear/tdl/app/internal/tgc/tgc.go:47
  - namespace is required:
    github.com/iyear/tdl/pkg/kv.(*legacy).open
        github.com/iyear/tdl/pkg/kv/legacy.go:111

请问是哪里设置不对吗？
谢谢

**Comment by iyear** [comment]
https://docs.iyear.me/tdl/guide/global-config/#-n--ns
