### ISSUE TITLE
[BUG] Download Half Error

### ISSUE THREAD

**Issue by Adriannnf** [iyear/tdl#423]
tdl -n adrian dl -f .\tdl-export.json --desc -i mp4 --proxy socks5://127.0.0.1:2080

[###########################...................] [1m11s; 2.56 MB/s]
Error: group:
    github.com/gotd/td/internal/mtproto.(*Conn).Run
        github.com/gotd/td@v0.89.0/internal/mtproto/conn.go:214
  - task readLoop:
    github.com/gotd/td/internal/tdsync.(*LogGroup).Go.func1
        github.com/gotd/td@v0.89.0/internal/tdsync/log_group.go:48
  - read:
    github.com/gotd/td/internal/mtproto.(*Conn).readLoop
        github.com/gotd/td@v0.89.0/internal/mtproto/read.go:193
  - read:
    github.com/gotd/td/transport.(*connection).Recv
        github.com/gotd/td@v0.89.0/transport/connection.go:70
  - read intermediate:
    github.com/gotd/td/internal/proto/codec.Intermediate.Read
        github.com/gotd/td@v0.89.0/internal/proto/codec/intermediate.go:73
  - read length:
    github.com/gotd/td/internal/proto/codec.readLen
        github.com/gotd/td@v0.89.0/internal/proto/codec/codec.go:35
  - EOF

**Comment by iyear** [comment]
https://docs.iyear.me/tdl/guide/global-config/#--reconnect-timeout

Try `--reconnect-timeout 0` flag.
