### ISSUE TITLE
[Feat] Multiple instances

### ISSUE THREAD

**Issue by yy16** [iyear/tdl#424]
Please describe your feature request
正在下载的时候，新建一个终端下载其它文件会报错
Error: create kv storage:
    github.com/iyear/tdl/cmd.New.func1
        github.com/iyear/tdl/cmd/root.go:57
  - open db:
    github.com/iyear/tdl/pkg/kv.newLegacy
        github.com/iyear/tdl/pkg/kv/legacy.go:42
  - timeout

**Comment by iyear** [comment]
This means that the database has already been opened and is in use by another tdl process, and currently, only one TDL instance can be kept running.

Multi-instance is already on the roadmap.

**Comment by iyear** [comment]
Fixed in v0.14.0
