### ISSUE TITLE
Error: open key_data: file "key_data" not found

### ISSUE THREAD

**Issue by jamacco94** [iyear/tdl#43]
Getting an error when while setup login:  tdl login -d "D:\Telegram_Desktop\Telegram.exe"

open key_data: file "key_data" not found

**Comment by iyear** [comment]
`tdl login -d "D:\Telegram_Desktop"`

**Comment by jamacco94** [comment]
Now this error

tdl dl -n iyear -u https://t.me/c/1833313498/402

callback: not authorized. please login first

**Comment by iyear** [comment]
```
tdl login -n iyear -d "D:\Telegram_Desktop"
tdl dl -n iyear -u https://t.me/c/1833313498/402
```

**Comment by jamacco94** [comment]
Thank you very much @iyear , it's working!
