### ISSUE TITLE
"tdl chat ls -f "列出会话类型，需要完善type提示。

### ISSUE THREAD

**Issue by augviolet** [iyear/tdl#431]
tdl chat ls -f 输出以下过滤字段：
ID: int64 # ID of dialog
**Type: string # Type of dialog. Can be 'user', 'channel' or 'group'**
VisibleName: string # Title of channel and group, first and last name of user. If empty, output '-'
Username: string # Username of dialog. If empty, output '-'
Topics[].ID: int # ID of topic
Topics[].Title: string # Title of topic
注意type类型里的描述不应该提示“user”，而是“private”。
tdl chat ls -f "Type == 'user'" 这个命令是无效的，虽然不报错，但是似乎只会导出空白
应当是：
tdl chat ls -f "Type == 'private'"
最好完善下哇~~~

**Comment by iyear** [comment]
Thanks, it will be fixed in the next release.

**Comment by iyear** [comment]
Fixed in v0.14.0
