### ISSUE TITLE
[BUG] 新的消息链接

### ISSUE THREAD

**Issue by augviolet** [iyear/tdl#434]
https://t.me/ShortcutsCN/19134?single&comment=494202
类似的https://t.me/c/fewhejet/5864?single&thread=4202（虚构的，但自己私有频道是存在的）
这种链接似乎源于发送媒体文件的时候以组合的方式发送，复制链接的时候就容易会有“single”

PS D:\desktop\tdl脚本> tdl dl -u https://t.me/ShortcutsCN/19134?single&comment=494202

Id     Name            PSJobTypeName   State         HasMoreData     Location             Command
--     ----            -------------   -----         -----------     --------             -------
3      Job3            BackgroundJob   Running       True            localhost            tdl dl -u https://t.me/S…
comment=494202: The term 'comment=494202' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

PS D:\desktop\tdl脚本> tdl dl -u https://t.me/ShortcutsCN/19134?comment=494202
All files will be downloaded to 'downloads' dir
坊间八卦 - 兼互助(1154500568):494202 -> download~ ... done! [26.53 KB in 3.238s; 8.12 KB/s]

**Comment by iyear** [comment]
It is supported, and downloading works fine locally with `https://t.me/c/1292489806/561?thread=558`. Can you provide the error message?

**Comment by augviolet** [comment]
> It is supported, and downloading works fine locally with `https://t.me/c/1292489806/561?thread=558`. Can you provide the error message?

"Not supported though, for this link: [https://t.me/ShortcutsCN/19134?single&comment=494202] or this link [https://t.me/c/19xxxxx69/416?single&thread=267]
Of course, these two types of links are the same as the links without "single&". Removing "single&" does not affect downloading."

![ww](https://github.com/iyear/tdl/assets/100132230/9bdc9d4f-688f-41a4-b8dd-2c86a6259049)

**Comment by iyear** [comment]
You need to quote the link above. The error displayed is a shell error, not a tdl error.

**Comment by augviolet** [comment]
> You need to quote the link above. The error displayed is a shell error, not a tdl error.

Thank you, I understand.
