### ISSUE TITLE
[BUG] Unable to download media from private group

### ISSUE THREAD

**Issue by lalit0506** [iyear/tdl#435]
**Describe the bug**
After logging in successfully, I am able to download the suggested quickstart media -
 tdl dl -n quickstart -u https://t.me/telegram/193

However when i try to download anything from one of my private group, it shows the below auth error -
Error: callback:
    github.com/gotd/td/telegram.(*Client).Run.func3
        github.com/gotd/td@v0.89.0/telegram/connect.go:151
  - not authorized. please login first

**Screenshots**
![image](https://github.com/iyear/tdl/assets/57571927/fbeeb32e-2c5c-4e2c-8ae2-b8858e6cd7b5)
![image](https://github.com/iyear/tdl/assets/57571927/ac030dd4-c502-45e5-80f2-5cc9c9852510)

**Version:**
Version: 0.14.0
Commit: 21a3408
Date: 2023-12-24T07:58:29Z

go1.19.13 darwin/arm64

**Comment by augviolet** [comment]
你都显示没登录，先登录注入命名空间，另外私密频道你得确定你当前的账号在群组频道里

**Comment by lalit0506** [comment]
> 你都显示没登录，先登录注入命名空间，另外私密频道你得确定你当前的账号在群组频道里

Yeah, I did login successfully and yes my account is there in that private group.
To further describe the login part, I tried two ways of login, both worked fine -

 1) tdl login -n quickstart
 2) tdl login -n quickstart --code

However the above mentioned issue is still there

**Comment by lalit0506** [comment]
Tried to login and logout several times and finally it worked, thanks

**Comment by dmnbme** [comment]
无法下载私密频道的文件
已登录，公开频道文件可正常下载
执行`tdl chat export -c 频道地址`后报错，信息如下
```
Error: callback:
    github.com/gotd/td/telegram.(*Client).Run.func3
        github.com/gotd/td@v0.89.0/telegram/connect.go:151
  - failed to get peer: unexpected deeplink type "join"
```

麻烦大佬了
