### ISSUE TITLE
[BUG] 无法下载私密频道的文件

### ISSUE THREAD

**Issue by dmnbme** [iyear/tdl#437]
**Describe the bug**
无法下载私密频道的文件，公开频道文件可正常下载

**To Reproduce**

执行`tdl chat export -c 频道地址`后报错，信息如下
```
Error: callback:
    github.com/gotd/td/telegram.(*Client).Run.func3
        github.com/gotd/td@v0.89.0/telegram/connect.go:151
  - failed to get peer: unexpected deeplink type "join"
```

**Version:**
Version: 0.14.0
Commit: 21a3408
Date: 2023-12-24T07:58:29Z

go1.19.13 darwin/arm64

**Comment by iyear** [comment]
The channel invitation link can't be used as input for `-c`.
