### ISSUE TITLE
[BUG] Error: group:

### ISSUE THREAD

**Issue by Adriannnf** [iyear/tdl#439]
PS E:\tdl> tdl -n adnn chat ls
Error: start:
    github.com/gotd/td/internal/mtproto.(*Conn).Run
        github.com/gotd/td@v0.89.0/internal/mtproto/conn.go:201
  - dial failed:
    github.com/gotd/td/internal/mtproto.(*Conn).connect
        github.com/gotd/td@v0.89.0/internal/mtproto/connect.go:21
  - context deadline exceeded
PS E:\tdl> tdl -n adnn chat ls --proxy socks5://127.0.0.1:2080
Error: group:
    github.com/gotd/td/internal/mtproto.(*Conn).Run
        github.com/gotd/td@v0.89.0/internal/mtproto/conn.go:214
  - task userCallback:
    github.com/gotd/td/internal/tdsync.(*LogGroup).Go.func1
        github.com/gotd/td@v0.89.0/internal/tdsync/log_group.go:48
  - initConnection:
    github.com/gotd/td/telegram/internal/manager.(*Conn).init
        github.com/gotd/td@v0.89.0/telegram/internal/manager/conn.go:230
  - invoke:
    github.com/gotd/td/telegram/internal/manager.(*Conn).init.func1
        github.com/gotd/td@v0.89.0/telegram/internal/manager/conn.go:221
  - rpcDoRequest:
    github.com/gotd/td/internal/mtproto.(*Conn).Invoke
        github.com/gotd/td@v0.89.0/internal/mtproto/rpc.go:44
  - retryUntilAck:
    github.com/gotd/td/internal/rpc.(*Engine).Do
        github.com/gotd/td@v0.89.0/internal/rpc/engine.go:141
  - retry limit reached after 1 attempts
PS E:\tdl>

**Comment by iyear** [comment]
Try `--reconnect-timeout 0` and see https://docs.iyear.me/tdl/guide/global-config/#--reconnect-timeout for details
