### ISSUE TITLE
請教一下，導出記錄的日期和格式。

### ISSUE THREAD

**Issue by tsinit2001** [iyear/tdl#44]
# specify the time period with timestamp format, default is start from 1970-01-01, end to now
tdl chat export -c CHAT_INPUT --from 1665700000 --to 1665761624

這個例句的數字中，1665是固定內容麼？之後的70年，00月和00日麼？那麼，1665 76 16 24爲神馬是今天的意思呢？

**Comment by iyear** [comment]
https://www.unixtimestamp.com/
