### ISSUE TITLE
[BUG] 下载中断

### ISSUE THREAD

**Issue by znxs** [iyear/tdl#443]
![image](https://github.com/iyear/tdl/assets/76854978/89449014-66bf-4a38-b887-cb9f3cc7f678)
下着下着就断了，感觉小文件下载没什么问题，大文件就会这样

**Comment by iuiiuiiiu** [comment]
同样问题，大文件会中断
![tdl_error](https://github.com/iyear/tdl/assets/8214028/4591aa46-b474-4b99-a9ae-04fc121f9b11)

**Comment by iyear** [comment]
Give your command and try `--reconnect-timeout 0` 

https://docs.iyear.me/tdl/guide/global-config/#--reconnect-timeout

**Comment by iuiiuiiiu** [comment]
> Give your command and try `--reconnect-timeout 0`
> 
> https://docs.iyear.me/tdl/guide/global-config/#--reconnect-timeout

It works! Thanks.
