### ISSUE TITLE
[BUG] download problem 

### ISSUE THREAD

**Issue by Zuuux** [iyear/tdl#448]
i have that error for no reason, i'm login 
![image_2024-01-08_171826244](https://github.com/iyear/tdl/assets/148497373/02f3ac32-3d4e-4fda-8224-c58f768d5790)

**Comment by SupMaMates** [comment]
Mee too! 
![image](https://github.com/iyear/tdl/assets/16089936/a548d59c-0ea6-480c-9356-2919209b4921)

**Comment by ziyufrank** [comment]
<img width="736" alt="Screenshot 2024-01-11 044559" src="https://github.com/iyear/tdl/assets/156246012/69c2e075-9f88-4f46-b6e4-0eaf52da046e">
how to fix it

**Comment by ziyufrank** [comment]
I tried running it on mac and the namespace didn't appear instead of logging into the account directly it had no issues exporting the chat directory and downloading the group everything worked fine don't take the space when downloading the start group directory and exporting the group directory Naming is to directly enter the command

**Comment by fetisherst** [comment]
同样的情况，每次都一半报错，无法下完
> Error: group:
>     github.com/gotd/td/internal/mtproto.(*Conn).Run
>         github.com/gotd/td@v0.89.0/internal/mtproto/conn.go:214
>   - task readLoop:
>     github.com/gotd/td/internal/tdsync.(*LogGroup).Go.func1
>         github.com/gotd/td@v0.89.0/internal/tdsync/log_group.go:48
>   - read:
>     github.com/gotd/td/internal/mtproto.(*Conn).readLoop
>         github.com/gotd/td@v0.89.0/internal/mtproto/read.go:193
>   - read:
>     github.com/gotd/td/transport.(*connection).Recv
>         github.com/gotd/td@v0.89.0/transport/connection.go:70
>   - read intermediate:
>     github.com/gotd/td/internal/proto/codec.Intermediate.Read
>         github.com/gotd/td@v0.89.0/internal/proto/codec/intermediate.go:73
>   - read length:
>     github.com/gotd/td/internal/proto/codec.readLen
>         github.com/gotd/td@v0.89.0/internal/proto/codec/codec.go:35
>   - EOF

**Comment by iyear** [comment]
Add flag `--reconnect-timeout 0` and see https://docs.iyear.me/tdl/guide/global-config/#--reconnect-timeout for details

**Comment by laopaoer-wallet** [comment]
Error: group:
github.com/gotd/td/internal/mtproto.(*Conn).Run
github.com/gotd/td@v0.89.0/internal/mtproto/conn.go:214

task readLoop:
github.com/gotd/td/internal/tdsync.(*LogGroup).Go.func1
github.com/gotd/td@v0.89.0/internal/tdsync/log_group.go:48
read:
github.com/gotd/td/internal/mtproto.(*Conn).readLoop
github.com/gotd/td@v0.89.0/internal/mtproto/read.go:193
read:
github.com/gotd/td/transport.(*connection).Recv
github.com/gotd/td@v0.89.0/transport/connection.go:70
read intermediate:
github.com/gotd/td/internal/proto/codec.Intermediate.Read
github.com/gotd/td@v0.89.0/internal/proto/codec/intermediate.go:73
read length:
github.com/gotd/td/internal/proto/codec.readLen
github.com/gotd/td@v0.89.0/internal/proto/codec/codec.go:35
EOF
