### ISSUE TITLE
[BUG] forward failed, send multi media: retry middleware skip: invoke pool: rpcDoRequest: rpc error code 500: WORKER_BUSY_TOO_LONG_RETRY

### ISSUE THREAD

**Issue by jerryc127** [iyear/tdl#462]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version:**
Run `tdl version` in terminal

Version: 0.14.1
Commit: 3021de5
Date: 2024-01-05T16:27:43Z

go1.19.13 linux/amd64

**Additional context**

upload failed, send multi media: retry middleware skip: invoke pool: rpcDoRequest: rpc error code 500: WORKER_BUSY_TOO_LONG_RETRY

![image](https://github.com/iyear/tdl/assets/16351105/2413ca10-6f3b-4efd-a578-9608abbe5508)

**Comment by jerryc127** [comment]
Has the problem been fixed? Can a new version be released soon?

**Comment by iyear** [comment]
Released in v0.15.0
