### ISSUE TITLE
how can i use it

### ISSUE THREAD

**Issue by fengguowudi** [iyear/tdl#47]
PS D:\Telegram Desktop> tdl login -n quickstart -d D:\Telegram Desktop
Namespace: quickstart
WARN: If data exists in the namespace, data will be overwritten
CreateFile D:\Telegram: The system cannot find the file specified

**Comment by iyear** [comment]
` tdl login -n quickstart -d "D:\Telegram Desktop"`

**Comment by fengguowudi** [comment]
![](https://ucgimg.fmapp.com/Public/imgquality/attachv1/image/20221030/20221030130747_45388.png)
长时间卡顿无回应

**Comment by iyear** [comment]
https://github.com/iyear/tdl#basic-configs Please use proxy flag

**Comment by fengguowudi** [comment]
![](https://ucgimg.fmapp.com/Public/imgquality/attachv1/image/20221030/20221030143017_45878.png)
一样的

**Comment by iyear** [comment]
Try to use `ntp` flag, maybe your system time is incorrect. If that still doesn't work, use `--debug` to print the full log and paste it into a reply.

**Comment by fengguowudi** [comment]
it's OK
