### ISSUE TITLE
[BUG] 我是用macos登录的时候报错请问这是什么原因啊？

### ISSUE THREAD

**Issue by leoshane13** [iyear/tdl#473]
> tdl login -d /Applications/Telegram.app --proxy socks5://localhost:8120
WARN: If data exists in the namespace, data will be overwritten
Importing session from desktop client: /Applications/Telegram.app
Error: open key_data:
    github.com/gotd/td/session/tdesktop.ReadFS
        github.com/gotd/td@v0.89.0/session/tdesktop/tdesktop.go:35
  - file "key_data" not found:
    github.com/gotd/td/session/tdesktop.open
        github.com/gotd/td@v0.89.0/session/tdesktop/file.go:60

**Comment by iyear** [comment]
Can https://github.com/iyear/tdl/issues/232 solve it?

**Comment by leoshane13** [comment]
重新下载了一个桌面版的telegram，现在可以登录没有报错了，谢谢大佬
