### ISSUE TITLE
[BUG] Builds failing due to goreleaser deprecation/removal of replacements

### ISSUE THREAD

**Issue by raouftmg** [iyear/tdl#476]
As of June 6th 2023 goreleaser no longer supports archives.replacements, so the following is causing the goreleaser action to fail:

  replacements:
      darwin: MacOS
      linux: Linux
      windows: Windows
      386: 32bit
      amd64: 64bit

with line 33: field replacements not found in type config.Archive

**Comment by iyear** [comment]
v1.18.2 works

https://github.com/iyear/tdl/blob/master/.github/workflows/release.yml#L39
