### ISSUE TITLE
callback: validate domain: is empty

### ISSUE THREAD

**Issue by nqxing** [iyear/tdl#48]
After logging in and starting to download the following error occurred, what is the reason?

![image](https://user-images.githubusercontent.com/37923544/198977571-c96c35d1-27f6-4544-bf3d-c725d659cad3.png)

**Comment by iyear** [comment]
`-u` flag must be exact to the message, for example: https://t.me/telegram/193.

If you want to export all medias of the channel, please refer to the `-f` flag in https://github.com/iyear/tdl#download

**Comment by nqxing** [comment]
> `-u` flag must be exact to the message, for example: https://t.me/telegram/193.
> 
> If you want to export all medias of the channel, please refer to the flag in https://github.com/iyear/tdl#download`-f`


Thank you. I got it wrong
