### ISSUE TITLE
What should I do next, about login

### ISSUE THREAD

**Issue by Little1Git** [iyear/tdl#480]
Please describe your feature request
![屏幕截图 2024-02-01 102747](https://github.com/iyear/tdl/assets/101879070/8fd69250-a78f-432a-87c1-66582154249c)

**Comment by iyear** [comment]
Option background: When using the desktop client sessions with tdl, the desktop client may fail to receive messages properly. Therefore, you can choose to delete the session of the desktop client and restart it. You should login again, so the tdl and desktop client sessions will no longer conflict.

Note: You can manually logout of the desktop client's account and login again to achieve the same purpose.
