### ISSUE TITLE
[BUG]  Files are not saved properly when using " .FileName " filter only.

### ISSUE THREAD

**Issue by ruZeph** [iyear/tdl#486]
**Describe the bug**
Using .FileName templates doesn't download the files properly. It throws error like this: 

```PowerShell
Premium Learning Centre(6943402955):2194 -> Downloads_\Tree 02 : Tree (Part - 02).mp4 error: post file: 
rename file: rename Downloads_\Tree 02 : Tree (Part - 02).mp4.tmp Downloads_\Tree 02 : Tree (Part - 02).mp4: The parameter is incorrect.
```
**To Reproduce**
Use only filename to download:
```PowerShell
tdl dl -f .\Tree_Till_Chap_5.json -d .\Downloads_\ --template "{{ .FileName }}"
```

**Expected behavior**
The files are downloaded properly.

**Screenshots**
![image](https://github.com/iyear/tdl/assets/92640971/698fd7ac-3e9e-4c9d-ada0-9070cdf0d452)

**Version:**
Run `tdl version` in terminal
Version: 0.15.1
Commit: 1e605a0
Date: 2024-01-31T14:13:25Z

go1.19.13 windows/amd64

**Additional context**
I have also used this template:
{{ replace .FileName `/` `_` `\` `_` `:` `_` `*` `_` `?` `_` `<` `_` `>` `_` `|` `_` ` ` `_`  }}

But it thorws more errors like this:
```PowerShell
Error: callback:
    github.com/gotd/td/telegram.(*Client).Run.func3
        github.com/gotd/td@v0.89.0/telegram/connect.go:151
  - parse template:
    github.com/iyear/tdl/app/dl.newIter
        github.com/iyear/tdl/app/dl/iter.go:61
  - template: dl:1: unexpected "/" in operand
```

**Comment by iyear** [comment]
My command works.

```
tdl dl -u URL --template "{{ replace .FileName `/` `_` `\` `_` `:` `_` `*` `_` `?` `_` `<` `_` `>` `_` `|` `_` ` ` `_`  }}"
```

**Comment by ruZeph** [comment]
I see. You have to wrap the custom formatting within quotes, else windows will treat them as symbols. Thanks!!
