### ISSUE TITLE
[BUG] forward the single of group item

### ISSUE THREAD

**Issue by saturn99** [iyear/tdl#487]
**Describe the bug**
If we want to forward only one file from a group of files, tdl will download all files as a group and then forward it.

**To Reproduce**
In this channel, we have group items including 3 files

![image](https://github.com/iyear/tdl/assets/5188799/c6e37ac9-b408-427c-bf0a-c42b81bc44db)

- https://t.me/TDLTDLTEST/2 file1
- https://t.me/TDLTDLTEST/3 file2
- https://t.me/TDLTDLTEST/4 file3

I want to forward only file 2 with URL https://t.me/TDLTDLTEST/3 

If I run this command:
`./tdl forward -n xxx --from "https://t.me/TDLTDLTEST/3"`
All files in the group will be sent

![image](https://github.com/iyear/tdl/assets/5188799/563d20b5-48c3-457e-987d-3ff7a6c4cbe2)

**Expected behavior**
i expected forward command work similar 
```
./tdl dl -n xxx -t 1  -u "https://t.me/TDLTDLTEST/3" 
./tdl up -n xxx -c "---" -p downloads/ 
```

**Version:**
```
Version: 0.15.1
Commit: 1e605a0
Date: 2024-01-31T14:13:25Z

go1.19.13 linux/amd64
```

**Additional context**

in Telegram, these addresses refer to a group item

- https://t.me/TDLTDLTEST/2 file1
- https://t.me/TDLTDLTEST/3 file2
- https://t.me/TDLTDLTEST/4 file3

And Telegram itself uses the `?single` parameters to separate this item

- https://t.me/TDLTDLTEST/2?single  file1
- https://t.me/TDLTDLTEST/3?single file2
- https://t.me/TDLTDLTEST/4?single  file3

As a result, this method can be used to clarify whether the user intends to download a single file or the entire group

**Comment by iyear** [comment]
Accepted
