### ISSUE TITLE
[BUG] - error when downloading using JSON file with no new messages 

### ISSUE THREAD

**Issue by cintainfinita** [iyear/tdl#488]
**Describe the bug**
If the json file has no messages and you try to download, you will get an error.

**To Reproduce**
use a json file with no new messages like this one:

{"id":SOME_ID_HERE_IT_WAS_REDACTED,"messages":[]}

**Expected behavior**
Something like "no new messages to download"

**Screenshots**
panic: runtime error: index out of range [0] with length 0

goroutine 25 [running]:
github.com/iyear/tdl/app/dl.(*iter).process(0x14000534f20, {0x101eb4130, 0x14000336320})
	github.com/iyear/tdl/app/dl/iter.go:131 +0xb64
github.com/iyear/tdl/app/dl.(*iter).Next(0x14000534f20, {0x101eb4130, 0x14000336320})
	github.com/iyear/tdl/app/dl/iter.go:106 +0x98
github.com/iyear/tdl/pkg/downloader.(*Downloader).Download(0x140000a3300, {0x101eb40f8?, 0x1400045db90?}, 0x14000231878?)
	github.com/iyear/tdl/pkg/downloader/downloader.go:38 +0x78
github.com/iyear/tdl/app/dl.Run({0x101eb40f8?, 0x1400045db90}, 0x1400020e000, {0x101eb27e0?, 0x14000532660}, {{0x16f43b8d3, 0xc}, 0x0, 0x1, {0x1400053c000, ...}, ...})
	github.com/iyear/tdl/app/dl/dl.go:126 +0xe08
github.com/iyear/tdl/cmd.NewDownload.func1.1({0x101eb4130?, 0x1400054c230?}, 0x191?, {0x101eb27e0, 0x14000532660})
	github.com/iyear/tdl/cmd/dl.go:33 +0x80
github.com/iyear/tdl/cmd.tRun.func1({0x101eb4130?, 0x1400054c230?})
	github.com/iyear/tdl/cmd/root.go:160 +0x3c
github.com/iyear/tdl/cmd.tRun.Run.func2({0x101eb4130, 0x1400054c230})
	github.com/iyear/tdl/pkg/tclient/tclient.go:124 +0x60
github.com/gotd/td/telegram.(*Client).Run.func3({0x101eb4130, 0x1400054c230})
	github.com/gotd/td@v0.89.0/telegram/connect.go:150 +0xa4
github.com/gotd/td/telegram.(*Client).Run.(*CancellableGroup).Go.func6()
	github.com/gotd/td@v0.89.0/internal/tdsync/cancel_group.go:48 +0x34
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.6.0/errgroup/errgroup.go:78 +0x58
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
	golang.org/x/sync@v0.6.0/errgroup/errgroup.go:75 +0x98

**Version:**
Version: 0.14.1
Commit: Homebrew
Date: 2024-01-05T16:27:43Z

go1.21.5 darwin/arm64

**Comment by iyear** [comment]
duplicate with #474. Run `brew upgrade telegram-downloader` to upgrade tdl to latest version.
