### ISSUE TITLE
 --ns looks like an invalid command

### ISSUE THREAD

**Issue by zhangyiming748** [iyear/tdl#49]
when i typed
```shell
./tdl -n zsxwz
```
Directly back to help information
```shell
Telegram Downloader, but more than a downloader

Usage:
  tdl [command]

Available Commands:
  backup      Backup your data
  chat        A set of chat tools
  completion  Generate the autocompletion script for the specified shell
  dl          Download anything from Telegram (protected) chat
  help        Help about any command
  login       Login to Telegram
  recover     Recover your data
  up          Upload anything to Telegram
  version     Check the version info

Flags:
      --debug          enable debug mode
  -h, --help           help for tdl
  -l, --limit int      max number of concurrent tasks (default 2)
  -n, --ns string      namespace for Telegram session
      --ntp string     ntp server host, if not set, use system time
      --proxy string   proxy address, only socks5 is supported, format: protocol://username:password@host:port
  -s, --size int       part size for transfer, max is 512*1024 (default 131072)
  -t, --threads int    threads for transfer one item (default 4)

Use "tdl [command] --help" for more information about a command.
```
how do i get one session?

**Comment by iyear** [comment]
`-n` is just a flag used in other commands, using `-n` alone is meaningless

**Comment by zhangyiming748** [comment]
> `-n` is just a flag used in other commands, using `-n` alone is meaningless

i use another command
```shell
$  ./tdl login -n quickstart -d /Applications/Telegram.app
```
it return
```shell
Namespace: quickstart
WARN: If data exists in the namespace, data will be overwritten
Importing session from desktop client: /Applications/Telegram.app
open key_data: file "key_data" not found
```
how do i found `key_data`?

**Comment by iyear** [comment]
Are you using the official Telegram desktop client?

**Comment by zhangyiming748** [comment]
> Are you using the official Telegram desktop client?

yes office Telegram for mac , i download it on official website

my computer is macbook m1

**Comment by iyear** [comment]
Please print tree of dir `/Applications/Telegram.app`

**Comment by iyear** [comment]
Oh I know, tdl only supports the client: https://desktop.telegram.org/ . Telegram has two official desktop clients XD

**Comment by zhangyiming748** [comment]
> Oh I know, tdl only supports the client: https://desktop.telegram.org/ . Telegram has two official desktop clients XD

i will try again 
thanks

**Comment by maige12138** [comment]
> > Oh I know, tdl only supports the client: https://desktop.telegram.org/ . Telegram has two official desktop clients XD
> 
> i will try again thanks
Did you solve this problem？
I also encountered a similar problem
