### ISSUE TITLE
[BUG] Excuse me, is this an issue with my proxy settings

### ISSUE THREAD

**Issue by TCchen-CS** [iyear/tdl#491]
Error: start:
    github.com/gotd/td/internal/mtproto.(*Conn).Run
        github.com/gotd/td@v0.96.1/internal/mtproto/conn.go:201
  - dial failed:
    github.com/gotd/td/internal/mtproto.(*Conn).connect
        github.com/gotd/td@v0.96.1/internal/mtproto/connect.go:21
  - context deadline exceeded

I set it as a global proxy and still cannot use it

**Comment by iyear** [comment]
You need to manually set https://docs.iyear.me/tdl/guide/global-config/#--proxy

**Comment by TCchen-CS** [comment]
tdl --proxy socks5://localhost:1080
tdl --proxy http://localhost:8080
tdl --proxy https://localhost:8081
I have implemented these three measures but still cannot change the current situation

**Comment by iyear** [comment]
You should add proxy flag to your real command.

Like: `tdl dl -u URL --proxy PROXY`

**Comment by TCchen-CS** [comment]
I modified the port number to allow the app to customize a proxy and connect to the internet. But after I made the changes, I couldn't use it properly

D:\telegram_download>tdl --proxy socks5:localhost:7890
Telegram Downloader, but more than a downloader

D:\telegram_download>tdl chat ls
Error: start:
    github.com/gotd/td/internal/mtproto.(*Conn).Run
        github.com/gotd/td@v0.96.1/internal/mtproto/conn.go:201
  - dial failed:
    github.com/gotd/td/internal/mtproto.(*Conn).connect
        github.com/gotd/td@v0.96.1/internal/mtproto/connect.go:21
  - context deadline exceeded

**Comment by iyear** [comment]
Run `tdl chat ls --proxy socks5:localhost:7890` instead of `tdl chat ls`

`--proxy` is a flag, not a command
