### ISSUE TITLE
report

### ISSUE THREAD

**Issue by fengguowudi** [iyear/tdl#50]
Get item failed: rpcDoRequest: retryUntilAck: retry limit reached after 10 attempts, skip...

callback: get file: get next chunk: rpcDoRequest: retryUntilAck: retry limit reached after 10 attempts

**Comment by iyear** [comment]
Please try to reduce the `part-size` or `threads`, too much concurrency triggers the server rate limit

**Comment by 2689380792** [comment]
> Get item failed: rpcDoRequest: retryUntilAck: retry limit reached after 10 attempts, skip...
> 
> callback: get file: get next chunk: rpcDoRequest: retryUntilAck: retry limit reached after 10 attempts

这是因为节点不好，非常不稳定，要换别的节点

只要节点质量好，稳定，就一直会下载下去
