### ISSUE TITLE
有安卓版本吗[Feat] 

### ISSUE THREAD

**Issue by yajiang1** [iyear/tdl#501]
Please describe your feature request

**Comment by Indranil012** [comment]
> Please describe your feature request
![Screenshot_20240406-215927](https://github.com/iyear/tdl/assets/48489074/a7128d9e-d0fd-4101-831d-6683df2eaf35)
Any guide how to install it?

**Comment by Indranil012** [comment]
Nvm termux official pkg repo already included this app

**Comment by yajiang1** [comment]
不会

**Comment by yajiang1** [comment]
不会

**Comment by indrastorms** [comment]
> Under termux, if there is an agent, hang up the agent. If there is no agent, change the source.
> 
> Run the following command. If you don’t know how, it is recommended to learn the basics of Linux first. pkg install git git clone [https://github.com/iyear/tdl/ ](https://github.com/iyear/tdl/) pkg install go cd tdl go build or directly go install github.com/iyear/tdl@latest After running for a while, tdl came out. Then run directly The rest is the same as linux operation To log in, just log in by phone or change the configuration file on the computer to termux.

I said termux already has this package and working as intended. So no need to build.

**Comment by xwxb** [comment]
> 下termux，有代理挂代理，没代理换源
> 
> 运行下列命令，不会的建议先去学linux基础 pkg install git git clone https://github.com/iyear/tdl/ pkg install go cd tdl go build或者直接go install github.com/iyear/tdl@latest 跑一会就出来tdl了 然后直接运行 剩下的就和linux操作一样了 登录的话直接电话登录或者把电脑上的配置文件换到termux就行了

搞定了感谢，没想到还能换配置文件，之前还苦恼没法收到验证码，二维码登录好像有问题。
顺便问问老哥有知道手机上下载tg文件的其他方案吗？用tdl只是为了后台下载，用常见的客户端，都是不前台就直接停止下载了
