### ISSUE TITLE
[Bug] Creates bogus files when export failed.

### ISSUE THREAD

**Issue by shamefulCake1** [iyear/tdl#506]
### Describe the bug

Even if a chat export fails (for example due to being unauthorized), the json or bolt/default files are created, with irrelevant content.

### To Reproduce

1. run `~/go/bin/tdl --storage type=file,path=/tmp/tp.json chat export chatname`
2. See the process fails with `not authorized. please login first`
3. observe /tmp/tp.json with some random strings

### Expected behavior

If export fails, no files should be created.

### Version

Version: dev
Commit: unknown
Date: unknown
go1.21.6 linux/amd64

Installed on 2024-02-20 with go install 

### Which OS are you running tdl on?

Linux

**Comment by iyear** [comment]
It is normal behavior. It has been explained in #507
