### ISSUE TITLE
[Bug] When specifying `--storage` all operations fail as ``- not authorized. please login first`

### ISSUE THREAD

**Issue by shamefulCake1** [iyear/tdl#507]
### Describe the bug

tdl installed with `go install github.com/iyear/tdl@latest`.

Running exports with --storage fails:

```
~/go/bin/tdl --storage type=file,path=/tmp/tp.file chat export <chatname>
Error: callback:
    github.com/gotd/td/telegram.(*Client).Run.func3
        /home/<username>/go/pkg/mod/github.com/gotd/td@v0.97.0/telegram/connect.go:151
  - not authorized. please login first
```

(<username> and <chatname> are redacted for privacy)

Meanwhile, not specifying `--storage` works.

```
~/go/bin/tdl  chat export <chatname>
WARN: Export only generates minimal JSON for tdl download, not for backup.
Occasional suspensions are due to Telegram rate limitations, please wait a moment.

Type: time | Input: [0 9223372036854775807]
<account>                                          ... done! [33 in 3.095s; 10/s]
```

But it is not clear where the export is saved.

### To Reproduce

See above.

### Expected behavior

`--storage` should not produce an error.

### Version

Version: dev
Commit: unknown
Date: unknown
go1.21.6 linux/amd64

installed with `go install github.com/iyear/tdl@latest`.

### Which OS are you running tdl on?

Linux

**Comment by iyear** [comment]
For each new storage, no sessions are stored by default. Therefore, you need to first run `~/go/bin/tdl --storage type=file,path=/tmp/tp.file login` before executing other commands.

Alternatively, choose `tdl migrate` to migrate existing data to the current storage.

**Comment by shamefulCake1** [comment]
Sorry, "storage" usually means where data go, so I expected the results of chat export to be stored in the storage.
