### ISSUE TITLE
New url format for dl `-u` flag

### ISSUE THREAD

**Issue by fengguowudi** [iyear/tdl#51]
The following formats are supported

`https://t.me/c/tdl/1-xxx`

That is, it is equivalent to
`https://t.me/c/tdl/1`
`https://t.me/c/tdl/2`
`https://t.me/c/tdl/3`
——————————
`https://t.me/c/tdl/xxx `

**Comment by iyear** [comment]
New version has released: https://github.com/iyear/tdl/releases/tag/v0.5.2
