### ISSUE TITLE
[Feat] A Better way to Download Multiple Files Following a Sequence

### ISSUE THREAD

**Issue by mohitjoshi155** [iyear/tdl#519]
### Proposal

a better way to download multiple files following a sequence
for eg https://t.me/c/1149259378/7561 to https://t.me/c/1149259378/7568

### Background

this way it can download files in this sequence without needing us to give tdl 7 urls seperately
it would greatly help

### Workarounds

right now have to give tdl multiple urls even if they follow a sequence one after another

**Comment by bolavefasfas** [comment]
I use a scipt and give a number from and to message 😂

**Comment by iyear** [comment]
Try https://docs.iyear.me/tdl/guide/tools/export-messages/#id-range and run `tdl dl -f export.json`

**Comment by mohitjoshi155** [comment]
> I use a scipt and give a number from and to message 😂
can you share your script please?
