### ISSUE TITLE
A silly little problem, I can't set up my tdl to use a proxy network🥲.[Bug] 

### ISSUE THREAD

**Issue by PoisonousHumanMineral** [iyear/tdl#533]
### Describe the bug

I set the powershell proxy but it didn't work. Then I set the proxy according to the method in the document but it didn't work.
![图片](https://github.com/iyear/tdl/assets/162766021/150b4471-1c33-42fe-8518-5ee34d75b276)

### To Reproduce

 tdl --proxy http://192.168.1.130:9980

### Expected behavior

Proxy set up successfully

### Version

Version: 0.16.1
Commit: bb2c69b
Date: 2024-03-01T13:21:31Z

go1.21.7 windows/amd64

### Which OS are you running tdl on?

Windows

**Comment by PoisonousHumanMineral** [comment]
I understand now. Should I add proxy parameters after downloading the command?😱

**Comment by pingping99** [comment]
You need to set proxy every time when you use a command,i have met the same problem like you,the guide doc didn't explain this properly

**Comment by PoisonousHumanMineral** [comment]
> 每次使用命令时都需要设置代理，我和你一样遇到过同样的问题，指南文档没有正确解释这一点

sad
