### ISSUE TITLE
[Bug] No responce for using Chat or Download cmd

### ISSUE THREAD

**Issue by hketernal** [iyear/tdl#539]
### Describe the bug

Hello there, I was using the tdl perfectly, but it was no responce few days before.
I can login to my account in tdl, but I cannot using CHAT LS and DOWNLOAD cmd,
It had the error like the following message
`Error: group:
    github.com/gotd/td/internal/mtproto.(*Conn).Run
        github.com/gotd/td@v0.97.0/internal/mtproto/conn.go:214
  - task userCallback:
    github.com/gotd/td/internal/tdsync.(*LogGroup).Go.func1
        github.com/gotd/td@v0.97.0/internal/tdsync/log_group.go:48
  - initConnection:
    github.com/gotd/td/telegram/internal/manager.(*Conn).init
        github.com/gotd/td@v0.97.0/telegram/internal/manager/conn.go:230
  - invoke:
    github.com/gotd/td/telegram/internal/manager.(*Conn).init.func1
        github.com/gotd/td@v0.97.0/telegram/internal/manager/conn.go:221
  - rpcDoRequest:
    github.com/gotd/td/internal/mtproto.(*Conn).Invoke
        github.com/gotd/td@v0.97.0/internal/mtproto/rpc.go:44
  - retryUntilAck:
    github.com/gotd/td/internal/rpc.(*Engine).Do
        github.com/gotd/td@v0.97.0/internal/rpc/engine.go:141
  - retry limit reached after 1 attempts`

What is the problem? Thank you for your help.

### To Reproduce

tdl dl -u URL
tdl chat ls

### Expected behavior

My chat lists should be shown but no reponse for more than 5 mins, it was working before.

### Version

Version: 0.16.0
Commit: 0e1ce1d
Date: 2024-02-15T02:51:19Z

go1.21.7 windows/amd64

### Which OS are you running tdl on?

Windows

**Comment by 808834** [comment]
I encounter the same problem. After I try to reinstall the telegram downloader and run the command "tdl chat ls", the problem remains unsolved.

**Comment by iyear** [comment]
Try set `--reconnect-timeout 0` flag

**Comment by 808834** [comment]
It doesnt work, the command reconnects over and over again without throwing any exception.

**Comment by gab-luz** [comment]
I second that. I can't download anything. It used to work.

**Comment by tungtrinh1402** [comment]
I often have this situation since using tdl. Could not find the cause.

**Comment by iyear** [comment]
Or has you set correct `--proxy` flag?

**Comment by caracoloco** [comment]
I have a pretty similar issue:

`tdl dl --skip-same -f tdl-export.json -d /directoy/to/download`

**OS:** Mac OS Big Sur

**tdl version details:**
Version: 0.16.2
Commit: 2ef95bc
Date: 2024-04-15T13:50:47Z
go1.21.9 darwin/amd6

Logs:

```
Error: group:
    github.com/gotd/td/mtproto.(*Conn).Run
        github.com/gotd/td@v0.99.2/mtproto/conn.go:214
  - task readLoop:
    github.com/gotd/td/tdsync.(*LogGroup).Go.func1
        github.com/gotd/td@v0.99.2/tdsync/log_group.go:48
  - read:
    github.com/gotd/td/mtproto.(*Conn).readLoop
        github.com/gotd/td@v0.99.2/mtproto/read.go:193
  - read:
    github.com/gotd/td/transport.(*connection).Recv
        github.com/gotd/td@v0.99.2/transport/connection.go:70
  - read intermediate:
    github.com/gotd/td/proto/codec.Intermediate.Read
        github.com/gotd/td@v0.99.2/proto/codec/intermediate.go:73
  - read length:
    github.com/gotd/td/proto/codec.readLen
        github.com/gotd/td@v0.99.2/proto/codec/codec.go:35
  - EOF
```

**Comment by iyear** [comment]
@caracoloco Try set --reconnect-timeout 0 flag

**Comment by 808834** [comment]
I worked it done. Here is my solution(My proxy is Clash): "tdl --proxy socks5://localhost:7890 chat ls"

**Comment by caracoloco** [comment]
> @caracoloco Try set --reconnect-timeout 0 flag

This works perfectlythis works perfectly. Is this a bug or should be the documentation added it?

**Comment by igs-qilincai** [comment]
> @caracoloco Try set --reconnect-timeout 0 flag

it's solution for me!!

**Comment by yuvii12347** [comment]
![Uploading Screenshot (51).png…]()

**Comment by yuvii12347** [comment]
![Screenshot (51)](https://github.com/user-attachments/assets/93f1a82c-f770-45a4-b068-455f8881dc61)
showing this...how to do it? im newbie i dont know how to use it any time i try to download something it gives blank nd do nothing
