### ISSUE TITLE
[Bug] can not set proxy properly

### ISSUE THREAD

**Issue by pingping99** [iyear/tdl#541]
### Describe the bug

can not set the global proxy,only respond when attached  the command : -- proxy http://localhost:port

### To Reproduce

use the command     tdl --proxy http://localhost:port

### Expected behavior

check if there is anything wrong,or some neccery steps needs to be done

### Version

Version: 0.16.1
Commit: bb2c69b
Date: 2024-03-01T13:21:31Z

go1.21.7 windows/amd64

### Which OS are you running tdl on?

Windows

**Comment by XMLHexagram** [comment]
In my view, you maybe misunderstanding the doc.

> Global config is some CLI flags that can be set in every command.

> If you want to add another account, just add -n YOUR_ACCOUNT_NAME option to every command:

According to the doc, 
Global configuration **does not mean** that the configuration will be persisted or only need to be set once in global settings, they will only take effect in the current command. 

You need to set them in each command.

**Comment by XMLHexagram** [comment]
@iyear, I make PR #557 add a hint in the global-config page. I believe add a hint will do effort to correct the misunderstanding.

**Comment by Louis24** [comment]
--proxy http://localhost:port/ in the end of cmd?
