### ISSUE TITLE
[Bug] 除登录外其他命令都无法使用，显示以下代码

### ISSUE THREAD

**Issue by Tiannyaaa** [iyear/tdl#542]
### Describe the bug

Error: start:
    github.com/gotd/td/mtproto.(*Conn).Run
        github.com/gotd/td@v0.98.0/mtproto/conn.go:201
  - dial failed:
    github.com/gotd/td/mtproto.(*Conn).connect
        github.com/gotd/td@v0.98.0/mtproto/connect.go:21
  - context deadline exceeded

### To Reproduce

tdl -n * chat ls
tdl -n * chat export -c *** -T id -i 1,200

### Expected behavior

除登录外其他命令都无法使用

### Version

0.16.1

### Which OS are you running tdl on?

Windows

**Comment by iyear** [comment]
https://docs.iyear.me/tdl/guide/global-config/#--proxy
