### ISSUE TITLE
Getting stuck using the chat command, and then prompting an error [Bug] 

### ISSUE THREAD

**Issue by callme-py-ya** [iyear/tdl#549]
### Describe the bug

When I log in, the command tdl -n XXX chat ls will get stuck. After a few minutes, I will be prompted with ERROR.
![4 ~_~IC)$X X4)(@SXPW5_Q](https://github.com/iyear/tdl/assets/81613540/732b4a30-ddfd-48ea-8b66-ac8c543c442e)

### To Reproduce

tdl lgoin -n XXX -d "XXXX"
tdl -n XXX chat ls

### Expected behavior

It should display the chat list, but after I execute the command, it reports an error message.

### Version

Version: 0.16.1
Commit: bb2c69b
Date: 2024-03-01T13:21:31Z

go1.21.7 windows/amd64

### Which OS are you running tdl on?

Windows

### Additional context

![image](https://github.com/iyear/tdl/assets/81613540/c82242b2-6acd-45f7-8266-8b2cb827b6d3)

**Comment by 808834** [comment]
I worked it done. Here is my solution(My proxy is Clash): "tdl --proxy socks5://localhost:7890 chat ls"
