### ISSUE TITLE
Help, I don't understand how to install it

### ISSUE THREAD

**Issue by axel845845** [iyear/tdl#55]
I have downloaded the .zip file but I don't know how to install it on windows, could you help me?

**Comment by iyear** [comment]
1. Download the latest Release
2. Unzip the package
3. Open the command line and cd to the tdl directory

**Comment by axel845845** [comment]
Does it work on windows 11?

**Comment by axel845845** [comment]
tdl is not recognized as a command

**Comment by iyear** [comment]
`.\tdl.exe xxx`

**Comment by axel845845** [comment]
Garbage, does not work

**Comment by iyear** [comment]
Plz paste your command or screenshot. "It doesn't work" How do I know why?

**Comment by axel845845** [comment]
![sodapdf-converted](https://user-images.githubusercontent.com/84351668/203447431-4022c628-6275-460c-8e61-dc6e3770e6ed.jpg)

**Comment by iyear** [comment]
Before input `Move-Item`, you should run powershell with admin mode.

**Comment by axel845845** [comment]
![capture_20221122190053635](https://user-images.githubusercontent.com/84351668/203450717-2da64ee2-e096-4cdb-9f27-7d389f42fbc2.jpg)

**Comment by iyear** [comment]
`Move-Item` is a command in `PowerShell`... or you can only try `move tdl.exe ....` in `cmd`

**Comment by axel845845** [comment]
Windows PowerShell
Copyright (C) Microsoft Corporation. Todos los derechos reservados.

Instale la versión más reciente de PowerShell para obtener nuevas características y mejoras. https://aka.ms/PSWindows

PS C:\WINDOWS\system32> cd C:\Users\brawl\Desktop\tdl-0.5.2
PS C:\Users\brawl\Desktop\tdl-0.5.2> Move-Item tdl.exe C:\Windows\System32
Move-Item : No se encuentra la ruta de acceso 'C:\Users\brawl\Desktop\tdl-0.5.2\tdl.exe' porque no existe.
En línea: 1 Carácter: 1
+ Move-Item tdl.exe C:\Windows\System32
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\brawl\Desktop\tdl-0.5.2\tdl.exe:String) [Move-Item], ItemNotFo
   undException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.MoveItemCommand

PS C:\Users\brawl\Desktop\tdl-0.5.2>

**Comment by axel845845** [comment]
![Sin título](https://user-images.githubusercontent.com/84351668/203451461-6a624698-7847-4948-9b50-da6fb718757d.png)

**Comment by iyear** [comment]
Is there a `tdl.exe` in your `tdl-0.5.2` directory?

**Comment by axel845845** [comment]
> Is there a in your directory?`tdl.exe``tdl-0.5.2`

No, :(

**Comment by iyear** [comment]
Download Windows x64 release, and unzip it. You will get a `tdl.exe` in directory.

https://github.com/iyear/tdl/releases/download/v0.5.2/tdl_Windows_64bit.zip

**Comment by axel845845** [comment]
Ready, and now?

**Comment by iyear** [comment]
And run `Move-Item ....`

**Comment by axel845845** [comment]
![Sin título](https://user-images.githubusercontent.com/84351668/203452306-9f47aa37-00a3-40e0-8b82-4055153c7adf.png)

**Comment by iyear** [comment]
you should modify `/path/to/Desktop-Telegram-Client` to your real path. It's just a placeholder.

**Comment by axel845845** [comment]
What is the route?

**Comment by iyear** [comment]
Where you install Telegram Desktop Client?(https://desktop.telegram.org/)

**Comment by axel845845** [comment]
Do I have to set the telegram installation path ?

**Comment by iyear** [comment]
Yes, it will import official client session, which can reduce risk of blocking.

**Comment by axel845845** [comment]
I already have the path, it is this---- C:\Users\brawl\AppData\Roaming\Telegram Desktop
Where should I change it?

**Comment by iyear** [comment]
`tdl login -n quickstart -d "C:\Users\brawl\AppData\Roaming\Telegram Desktop"`

**Comment by axel845845** [comment]
PS C:\Users\brawl\Desktop\tdl-0.5.2> tdl login -n quickstart -d "C:\Users\brawl\AppData\Roaming\Telegram Desktop"
Namespace: quickstart
WARN: If data exists in the namespace, data will be overwritten
Importing session from desktop client: C:\Users\brawl\AppData\Roaming\Telegram Desktop
You can get user id from @userinfobot

Select a user id:

1. 1203024729

Enter a number:
Do I have to enter my TG account phone number?

**Comment by iyear** [comment]
No, just enter `1`.

**Comment by axel845845** [comment]
![Sin título](https://user-images.githubusercontent.com/84351668/203453860-63561520-4214-44ef-b8b1-0d59be4edead.png)

**Comment by iyear** [comment]
Yes, that's ok.

**Comment by iyear** [comment]
then run "tdl dl -n quickstart ......" or any other command

**Comment by axel845845** [comment]
to download just add the group link ? something like this ?

**Comment by axel845845** [comment]
![Sin título](https://user-images.githubusercontent.com/84351668/203454270-820402eb-7b48-49c3-b422-3a0b94a0f3a3.png)
