### ISSUE TITLE
[Feat] Batch Download using .TXT file containing URLs

### ISSUE THREAD

**Issue by ArgX11** [iyear/tdl#555]
### Proposal

It would be great if you kindly implement the Batch Download option similar to [YT-DLP](https://github.com/yt-dlp/yt-dlp#:~:text=%2Da%2C%20%2D%2Dbatch%2Dfile%20FILE).

Suppose I have 5 Telegram URLs,
`https://t.me/tdl/1`
`https://t.me/tdl/2`
`https://t.me/tdl/3`
`https://t.me/tdl/4`
`https://t.me/tdl/5`

And I put them in a `URLs.txt` file then I should be able to download them using `Batch Download` command something like this,
`tdl dl --batch-download URLs.txt`

### Background

Suppose a channel has 10 messages and I want every second message from that channel like this,
`https://t.me/tdl/2`
`https://t.me/tdl/4`
`https://t.me/tdl/6`
`https://t.me/tdl/8`
`https://t.me/tdl/10`

Presently there is no way to select them using the `Chat Export` command

### Workarounds

Currently, I have to manually put each URL individually and download them which is a very tedious process.

**Comment by XMLHexagram** [comment]
Currently, you can use [Export Messages](https://docs.iyear.me/tdl/guide/tools/export-messages/#export-messages) and edit the `tdl-export.json` manually as a workaround.

Or you can try the bash command below:
```bash
while read -r line
do
  tdl dl "$line"
done < URLs.txt
```
as another workaround.

**Comment by XMLHexagram** [comment]
@ArgX11 , I am glad to help.

The easiest way is using [filter](https://docs.iyear.me/tdl/guide/tools/export-messages/#filter) to ignore file with `.mp4` file extension.

For instance, `tdl chat export -c $YOUR_CHAT -f "Media.Name not endsWith '.mp4'"`

**Comment by XMLHexagram** [comment]
@ArgX11, I believe this has already exceeded the scope of what `TDL` is responsible for.

Also I think editing json in `cmd` is a bad idea. Maybe you can give [jj](https://github.com/tidwall/jj) a try.

Or just write some scripts to process the `tdl-export.json`.

**Comment by bolavefasfas** [comment]
> ### Proposal
> It would be great if you kindly implement the Batch Download option similar to [YT-DLP](https://github.com/yt-dlp/yt-dlp#:~:text=%2Da%2C%20%2D%2Dbatch%2Dfile%20FILE).
> 
> Suppose I have 5 Telegram URLs, `https://t.me/tdl/1` `https://t.me/tdl/2` `https://t.me/tdl/3` `https://t.me/tdl/4` `https://t.me/tdl/5`
> 
> And I put them in a `URLs.txt` file then I should be able to download them using `Batch Download` command something like this, `tdl dl --batch-download URLs.txt`
> 
> ### Background
> Suppose a channel has 10 messages and I want every second message from that channel like this, `https://t.me/tdl/2` `https://t.me/tdl/4` `https://t.me/tdl/6` `https://t.me/tdl/8` `https://t.me/tdl/10`
> 
> Presently there is no way to select them using the `Chat Export` command
> 
> ### Workarounds
> Currently, I have to manually put each URL individually and download them which is a very tedious process.

tdl chat export -c CHAT-T id -i 1,5


This will only export he messages from 1-5 in the json 
and you can use that to download the selected range of messages

**Comment by bolavefasfas** [comment]
> > tdl chat export -c CHAT -T id -i 1,5
> 
> @bolavefasfas Did you happen to read my question carefully? If yes then solve this (without manually modifying the JSON file)
> 
> Suppose a channel has 10 messages and I want every second message from that channel like this,
> 
> `https://t.me/tdl/2` `https://t.me/tdl/4` `https://t.me/tdl/6` `https://t.me/tdl/8` `https://t.me/tdl/10`

use a bash script with loop

**Comment by phanirithvij** [comment]
I too think these features inside tdl are not that necessary, i wrote python/bash scripts to loop over the exported files and the -f filter combination to get the messages I need and dump them to a new json, then use tdl to perform up/down/fwd operations on the resulting new json.

**Comment by iyear** [comment]
This feature won't be supported for now. I aim to keep the input part of tdl as simple and stable as possible. Currently, it supports two methods: `-u` and `-f`. You can use any external tool to convert the file format to the target format.

**Comment by Vlavitz** [comment]
> i wrote python/bash scripts to loop over the exported files

@phanirithvij  Would you like to share such scripts? That would help me greatly, saving my time.

**Comment by phanirithvij** [comment]
@Vlavitz contact me via email. I don't know your use case.
