### ISSUE TITLE
help needed with login without desktop client

### ISSUE THREAD

**Issue by rohitsangwan01** [iyear/tdl#56]
Hey, am trying to login using this command :  ./tdl login -n quickstart 

and then it just stucked like this : 
![Screenshot 2022-11-20 at 4 06 24 PM](https://user-images.githubusercontent.com/59526499/202897421-db2b4918-7f9e-4e02-98e3-d49eab424304.png)

am not sure what next , or how am i suppose to login without desktop client installed on my laptop
Am using this on Mac M1

**Comment by iyear** [comment]
1. Check if you need to use a proxy (`proxy` flag)
2. Check if your system's local time is correct (`ntp` flag or calibrate system time)

In addition, I recommend importing the official client session, to help reduce the risk of blocking:)

**Comment by rohitsangwan01** [comment]
@iyear ok will try with client , Thank you
