### ISSUE TITLE
[Feat] add an upload option to chat to specify topics

### ISSUE THREAD

**Issue by tasi788** [iyear/tdl#561]
### Proposal

I hope to add an upload option to chat to specify topics.

### Background

Just like the download section has the -u option to specify the chat link, it would be better if you could also specify topics when uploading.

### Workarounds

Currently, my approach is to first upload to Saved Messages and then manually forward them to the specified location.

This is a bit cumbersome and time-consuming, and it would be more efficient if I could directly upload files to the specified location.

**Comment by XMLHexagram** [comment]
duplicate #500
fix in #559
