### ISSUE TITLE
[Bug] Error with protected and closed groups/channels

### ISSUE THREAD

**Issue by axel845845** [iyear/tdl#571]
### Describe the bug

When I try with protected channels and they show like this "this topic is closed" :

C:\Users>tdl>tdl chat export -c https://t.me/c/1836552391/110569
Error: callback:
    github.com/gotd/td/td/telegram.(*Client).Run.func3
        C:/Users/brawl/go/pkg/mod/github.com/gotd/td@v0.99.1/telegram/connect.go:151
  - failed to get peer: resolve: retry middleware skip: rpcDoRequest: rpc error code 400: USERNAME_INVALID

But when I try with protected channels only, it works perfectly.

### To Reproduce

C:\Users>tdl>tdl chat export -c https://t.me/c/1836552391/110569
Error: callback:
    github.com/gotd/td/td/telegram.(*Client).Run.func3
        C:/Users/brawl/go/pkg/mod/github.com/gotd/td@v0.99.1/telegram/connect.go:151
  - failed to get peer: resolve: retry middleware skip: rpcDoRequest: rpc error code 400: USERNAME_INVALID

### Expected behavior

tried it on a protected channel only and it worked(no closed): {"id":1390607473, "messages":[{"id":3611, "type": "message", "file": "5458846327330847636.mp4"},{"id":3610, "type": "message", "file": "5210688310039664288.jpg"},{"id":3608, "type": "message", "file": "5206357440655806834.mp4"},{"id":3608, "type": "message", "file": "5206357440655806834.mp4"}

### Version

Version 0.16.1
go1.22.2 windows 11 /amd64

### Which OS are you running tdl on?

Windows

**Comment by XMLHexagram** [comment]
Please read tdl doc [export#rom-topicreplies](https://docs.iyear.me/tdl/guide/tools/export-messages/#from-topicreplies) carefully.

You should use a command look like `tdl chat export -c CHAT --topic TOPIC_ID` to export messages from topic.

**Comment by axel845845** [comment]
> Please read tdl doc [export#from-topicreplies](https://docs.iyear.me/tdl/guide/tools/export-messages/#from-topicreplies) carefully.
> 
> You should use a command look like to export messages from topic.`tdl chat export -c CHAT --topic TOPIC_ID`

thanks but then, what would be the TOPIC ID? maybe 110281?

https://t.me/c/1873552396/99231/110281
