### ISSUE TITLE
[Feat] Supports Telegram bot conversations

### ISSUE THREAD

**Issue by huajideshutiao** [iyear/tdl#575]
### Proposal

I hope to use the Telegram bot to manage download tasks, including adding, deleting, pausing, and customizing download parameters

### Background

Using terminals may seem cumbersome.

### Workarounds

https://github.com/tangyoha/telegram_media_downloader
This project provides bot functionality. It would be even better if Docker could be supported.

**Comment by huajideshutiao** [comment]
Unlike [#124](https://github.com/iyear/tdl/issues/124), I just hope to manage through bots instead of downloading entirely using my bot account.

**Comment by 1368129224** [comment]
I made some attempts in this script to download the file by sending a message link to the bot, it uses tdl.
Maybe you can try it.
https://github.com/1368129224/tgbot-for-tdl

**Comment by huajideshutiao** [comment]
> I made some attempts in this script to download the file by sending a message link to the bot, it uses tdl. Maybe you can try it. https://github.com/1368129224/tgbot-for-tdl

Thank you!
