### ISSUE TITLE
Got error: decrypt keyEncrypted: msg_key mismatch

### ISSUE THREAD

**Issue by Unintendedz** [iyear/tdl#58]
I'm trying to login with existing official desktop client by using:
`.\tdl.exe login -n mytg -d D:/Portable/Telegram`

Then I got error:
```
F:\Downloads\tdl_Windows_64bit
❯ .\tdl.exe login -n mytg -d D:/Portable/Telegram
Namespace: mytg
WARN: If data exists in the namespace, data will be overwritten
Importing session from desktop client: D:/Portable/Telegram
```

Am I doing something wrong? any help would be appreciate!

**Comment by iyear** [comment]
The reason is that the client's local passcode is set, and tdl reads the session in the form of no passcode.

Temporary solution: remove the client's passcode, then run `tdl login ...`

I will fix this issue in the next version.
