### ISSUE TITLE
[Bug] Small problem with customizing Telegram installation path

### ISSUE THREAD

**Issue by PoisonousHumanMineral** [iyear/tdl#587]
### Describe the bug

I found a bug while using a custom Telegram installation path. Telegram's default installation path has a space in the folder name, but commands using a custom installation path don't seem to recognize the space. You need to fill in the spaces in the folder name with characters such as _ for normal use.

### To Reproduce

tdl login -d B:/Telegram Desktop
WARN: If data exists in the namespace, data will be overwritten
Error: CreateFile B:\Telegram: The system cannot find the file specified.

### Expected behavior

WARN: If data exists in the namespace, data will be overwritten
Importing session from desktop client: B:\Telegram Desktop

### Version

Version: 0.16.0
Commit: 0e1ce1d
Date: 2024-02-15T02:51:19Z

go1.21.7 windows/amd64

### Which OS are you running tdl on?

Windows

**Comment by iyear** [comment]
`tdl login -d "B:\Telegram Desktop"`
