### ISSUE TITLE
[Bug] can not download

### ISSUE THREAD

**Issue by Louis24** [iyear/tdl#592]
### Describe the bug

![image](https://github.com/iyear/tdl/assets/18719360/ad235ea9-93f4-4832-8aa2-e660aaf4796c)

### To Reproduce

i downloaded the tdl_Windows_64bit.zip unzip and in that folder cmd

```
tdl login
tdl dl -u https://t.me/telegram/193
```

### Expected behavior

downlad

### Version

Version: 0.17.0
Commit: 95120c0
Date: 2024-04-21T14:07:16Z

go1.21.9 windows/amd64

### Which OS are you running tdl on?

Windows

**Comment by XMLHexagram** [comment]
Seems caused by cannot correctly connect to telegram server.

Can you check you terminal whether can ping www.google.com or not？

**Comment by Louis24** [comment]
> Seems caused by cannot correctly connect to telegram server.
> 
> Can you check you terminal whether can ping [www.google.com](http://www.google.com) or not？

yes ofc, I use the tun mode

**Comment by zanzhz1101** [comment]
请仔细查阅文档[https://docs.iyear.me/tdl/zh/more/troubleshooting/](https://docs.iyear.me/tdl/zh/more/troubleshooting/)，如果有网络问题请使用`--proxy socks5://address`解决

**Comment by iyear** [comment]
https://docs.iyear.me/tdl/zh/more/troubleshooting/#q-%e8%be%93%e5%85%a5%e5%91%bd%e4%bb%a4%e5%90%8e%e4%b8%ba%e4%bb%80%e4%b9%88%e6%b2%a1%e6%9c%89%e5%93%8d%e5%ba%94%e6%97%a5%e5%bf%97%e4%b8%ad%e4%b8%ba%e4%bb%80%e4%b9%88%e5%87%ba%e7%8e%b0-msg_id-too-high
