### ISSUE TITLE
[Bug] can not setting proxy

### ISSUE THREAD

**Issue by Louis24** [iyear/tdl#593]
### Describe the bug

![image](https://github.com/iyear/tdl/assets/18719360/6b14f2ae-c9a5-411a-b82a-237dc0875ed6)

### To Reproduce

tdl --proxy https://127.0.0.1:7890

### Expected behavior

proxy

### Version

Version: 0.17.0
Commit: 95120c0
Date: 2024-04-21T14:07:16Z

go1.21.9 windows/amd64

### Which OS are you running tdl on?

Windows

**Comment by zanzhz1101** [comment]
the right download option is like to be"tdl dl -f "E:\tdl\1c.json" -t 8 -s 524288 -l 4 --rewrite-ext --skip-same -d  "E:\lc2"  --proxy socks5://abc:123@192.168.0.20:10999 --template "{{ .FileName }}""

**Comment by qazgp** [comment]
我也是，没看懂怎么设置代理

**Comment by qazgp** [comment]
好像明白了，我用的clash，设置7890端口的话会报错，设置成了1080，用http代理可以下载了

**Comment by iyear** [comment]
@Louis24 全局并不会让所有应用走代理，ping google能通是因为终端默认使用了 HTTP_PROXY 环境变量。如果需要从网卡层面让所用应用走代理，请开启TUN模式

**Comment by MarvinXu** [comment]
没法自动使用HTTP_PROXY 环境变量吗
