### ISSUE TITLE
[Bug] Download not Getting Started

### ISSUE THREAD

**Issue by KnownBlackHat** [iyear/tdl#598]
### Describe the bug

Command used: `./tdl download --debug -t 20 -u link1 -u link2`

![image](https://github.com/iyear/tdl/assets/65008967/692c5fd7-5d22-4478-9ceb-4049ae6ff57c)

My download is not getting started it stucks at 0B and only time increases

### To Reproduce

./tdl download --debug -t 20 -u link1 -u link2

### Expected behavior

I wanted that it should start downloading

### Version

Version: 0.16.1
Commit: bb2c69b
Date: 2024-03-01T13:21:31Z

go1.21.7 linux/amd64

### Which OS are you running tdl on?

Linux

**Comment by nkurnia1031** [comment]
having the same issue

To Reproduce
tdl dl -f tdl-export.json -d path_download --skip-same --takeout  --continue --reconnect-timeout 0

![image](https://github.com/iyear/tdl/assets/24490429/256cb516-aa61-439c-a942-8e62b9b5f457)

i try on 2 different machine and network but same account

try different link not working, just happend last night (2024-05-03)

stream and download form web telegram still working

**Comment by iyear** [comment]
https://docs.iyear.me/tdl/more/troubleshooting/#q-why-no-response-after-entering-the-command-and-why-there-is-msg_id-too-high-in-the-log
