### ISSUE TITLE
Download log messages will freeze after a while

### ISSUE THREAD

**Issue by Chiyukichan** [iyear/tdl#60]
System info:
Windows11 x64 Windows 终端 version: 1.15.2875.0 （PowerShell）管理员权限运行

Logs will stop after a while when doing batch downloads, but the download behavior continues. This causes me don't know when the download is finish.
And I found out that it can't download all the media files of the group, I do a batch download in a group with 20k+ files and only get 800+ media files, I have to try to download it by month and month.

I'm not sure if this is a bug or an isolated case, I'll keep trying and provide useful info. See attachment for details, it gets stuck in this place and no longer shows progress bar.

![QQ截图20221127173944](https://user-images.githubusercontent.com/32799910/204129668-ea18a31c-d77d-406d-adf4-dfd6a7959e58.png)

**Comment by iyear** [comment]
Thanks for the feedback. The conditions for reproduction and debugging are complex. I first need to spend some time debugging the upstream libraries to troubleshoot them.

**Comment by iyear** [comment]
I've submitted a PR to the upstream repo https://github.com/jedib0t/go-pretty/pull/246 to fix overall tracker disappearing. 

I will release a new fix version

**Comment by suujonH** [comment]
The bug seems to be still here.

**Comment by iyear** [comment]
Thanks for the feekback! New version has released. https://github.com/iyear/tdl/releases/tag/v0.5.5

**Comment by iyear** [comment]
I have released a new version that may solve this problem. Feel free to try it out.

**Comment by iyear** [comment]
The new version has been released, feel free to try it or reopen the issue.
