### ISSUE TITLE
[Bug] File name contains \n cannot be filtered during download

### ISSUE THREAD

**Issue by PAINCLOWN** [iyear/tdl#612]
### Describe the bug

File name contains \n cannot be filtered during download，
--template "{{ replace .FileName `\\n` `_` `/` `_` `\` `_` `:` `_` `*` `_` `?` `_` `<` `_` `>` `_` `|` `_` ` ` `_`  }}"
or 
--template "{{ replace .FileName `\n` `_` `/` `_` `\` `_` `:` `_` `*` `_` `?` `_` `<` `_` `>` `_` `|` `_` ` ` `_`  }}"
When I download using cmd, it causes the file name to contain a newline and the file cannot be created

![image](https://github.com/iyear/tdl/assets/29433774/53d8f121-5da6-4d3a-9d0e-2d0eff57c0b7)

![image](https://github.com/iyear/tdl/assets/29433774/bd6f5702-4de5-4d2a-873b-74aefa7ef517)
![image](https://github.com/iyear/tdl/assets/29433774/4dfc9501-e139-4b94-85ee-c180a677b6d2)

### To Reproduce

--template "{{ replace .FileName `\\n` `_` `/` `_` `\` `_` `:` `_` `*` `_` `?` `_` `<` `_` `>` `_` `|` `_` ` ` `_`  }}"
or 
--template "{{ replace .FileName `\n` `_` `/` `_` `\` `_` `:` `_` `*` `_` `?` `_` `<` `_` `>` `_` `|` `_` ` ` `_`  }}"

### Expected behavior

Unable to filter \n

### Version

Version: 0.17.0
Commit: 95120c0
Date: 2024-04-21T14:07:16Z

go1.21.9 windows/amd64

### Which OS are you running tdl on?

Windows

**Comment by iyear** [comment]
Try `--template '{{ replace .FileName "\n" "_" }}'`. Be careful of quotation.

**Comment by PAINCLOWN** [comment]
> 尝试一下`--template '{{ replace .FileName "\n" "_" }}'`。注意引用。

`PS D:\tg_down> tdl -n quickstart dl -f 1526240073.json -t 8 -s 524288 -l 4 --skip-same  --continue -i mp4,flv,f4v,webm,m4v,mov,3gp,3g2,rm,rmvb,mpg,mpeg,mpe,ts,mpg,mpeg,mpe,ts,vob,dat,mkv,lavf,cpk,dirac,ram,qt,fli,flc,mod --template '{{ replace .FileName "\n" "_" }}'
Error: callback:
    github.com/gotd/td/telegram.(*Client).Run.func3
        github.com/gotd/td@v0.102.0/telegram/connect.go:151
  - parse template:
    github.com/iyear/tdl/app/dl.newIter
        github.com/iyear/tdl/app/dl/iter.go:65
  - template: dl:1: unexpected "\\" in operand`

The above error occurred after using the template you provided
please check

**Comment by PAINCLOWN** [comment]
But I use "-f "Media.Name not contains  '\n' " " to filter out all conversations that contain"\n ", which works fine. I don't know if that helps solve the problem.

**Comment by PAINCLOWN** [comment]
PS D:\tg_down> tdl -n quickstart dl -f 1877648258.json -t 8 -s 524288 -l 4 --skip-same  --continue -i mp4,flv,f4v,webm,m4v,mov,3gp,3g2,rm,rmvb,mpg,mpeg,mpe,ts,mpg,mpeg,mpe,ts,vob,dat,mkv,lavf,cpk,dirac,ram,qt,fli,flc,mod --template "{{ replace .FileName '\n' '_' '/' '_'  ':' '_' '*' '_' '?' '_' '<' '_' '>' '_' '|' '_' ' ' '_'  }}"
Found unfinished download, continue from '70/1549'
All files will be downloaded to 'downloads' dir
Error: callback:
    github.com/gotd/td/telegram.(*Client).Run.func3
        github.com/gotd/td@v0.102.0/telegram/connect.go:151
  - iter:
    github.com/iyear/tdl/pkg/downloader.(*Downloader).Download
        github.com/iyear/tdl/pkg/downloader/downloader.go:59
  - execute template:
    github.com/iyear/tdl/app/dl.(*iter).process
        github.com/iyear/tdl/app/dl/iter.go:186
  - template: dl:1:21: executing "dl" at <'\n'>: expected string; found '\n'


PS D:\tg_down> tdl -n quickstart dl -f 1877648258.json -t 8 -s 524288 -l 4 --skip-same  --continue -i mp4,flv,f4v,webm,m4v,mov,3gp,3g2,rm,rmvb,mpg,mpeg,mpe,ts,mpg,mpeg,mpe,ts,vob,dat,mkv,lavf,cpk,dirac,ram,qt,fli,flc,mod --template "{{ replace .FileName '\' '_' '/' '_'  ':' '_' '*' '_' '?' '_' '<' '_' '>' '_' '|' '_' ' ' '_'  }}"
Error: callback:
    github.com/gotd/td/telegram.(*Client).Run.func3
        github.com/gotd/td@v0.102.0/telegram/connect.go:151
  - parse template:
    github.com/iyear/tdl/app/dl.newIter
        github.com/iyear/tdl/app/dl/iter.go:65
  - template: dl:1: malformed character constant: '\' '

**Comment by PAINCLOWN** [comment]
> Try `--template '{{ replace .FileName "\n" "_" }}'`. Be careful of quotation.

I noticed that the template uses the inverted single quote "`" instead of the single quote "'" and the double quote " " ”
