### ISSUE TITLE
[Feat] I can’t connect to the Internet when using the clash proxy. How should I set up the proxy? Does anyone have a detailed tutorial?

### ISSUE THREAD

**Issue by ligan2024** [iyear/tdl#614]
### Proposal

使用clash代理的时候连接不上网络，应该怎样设置代理呢，大佬有没有详细教程
![屏幕截图 2024-05-15 103013](https://github.com/iyear/tdl/assets/169865889/b1ec2ae7-70fd-4486-a1b3-8076b8850bdc)

### Background

使用clash代理的时候连接不上网络，应该怎样设置代理呢，大佬有没有详细教程

### Workarounds

使用clash代理的时候连接不上网络，应该怎样设置代理呢，大佬有没有详细教程

**Comment by ligan2024** [comment]
![屏幕截图 2024-05-15 104002](https://github.com/iyear/tdl/assets/169865889/333424c8-a82a-4be8-9bde-9e0fc0a86273)
z这个是我现在设置的

**Comment by ligan2024** [comment]
输入tdl --proxy http://localhost:8080会显示timeout
![Uploading 屏幕截图 2024-05-15 104519.png…]()

**Comment by ligan2024** [comment]
![Uploading 屏幕截图 2024-05-15 104519.png…]()

**Comment by iyear** [comment]
Remove the `--ntp` flag and use the `--proxy` flag to set the proxy server address.
