### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Romntic** [iyear/tdl#63]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1cc26d2]

goroutine 42 [running]:
github.com/iyear/tdl/pkg/downloader.(*Downloader).download(0xc00035a7c0, {0x23453d8, 0xc00035a800}, 0x0)
	github.com/iyear/tdl/pkg/downloader/downloader.go:98 +0x132
github.com/iyear/tdl/pkg/downloader.(*Downloader).Download.func1()
	github.com/iyear/tdl/pkg/downloader/downloader.go:64 +0x108
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.0.0-20220819030929-7fc1605a5dde/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20220819030929-7fc1605a5dde/errgroup/errgroup.go:72 +0xa5

**Comment by iyear** [comment]
Hello, what you input in cmd?

**Comment by Romntic** [comment]
tdl -n salemd dl -u https://t.me/c/ddd/31

**Comment by iyear** [comment]
`ddd` is a placeholder? I tested `-u https://t.me/c/1697797156/48` but can't reproduce.

**Comment by Romntic** [comment]
Before I can download from any group who make forward disable butt now I can't just before I write my problem half hour it's working 
But now working with group. Not disable 

Can u solve :)

**Comment by Romntic** [comment]
Now working
