### ISSUE TITLE
[Bug] Download Error

### ISSUE THREAD

**Issue by slayercjc** [iyear/tdl#631]
### Describe the bug

![Snipaste_2024-05-30_15-59-33](https://github.com/iyear/tdl/assets/14236188/f0e7cd0a-b190-44b7-b696-d8ae08b12f1d)

### To Reproduce

Download Error

### Expected behavior

Download Error

### Version

v0.17.1

### Which OS are you running tdl on?

Windows

**Comment by iyear** [comment]
https://github.com/iyear/tdl/issues/158#issuecomment-1551116053
