### ISSUE TITLE
[Bug] Unfriendly progress bar output

### ISSUE THREAD

**Issue by iyzyi** [iyear/tdl#632]
### Describe the bug

Please have a look at the attachment. 
I dont know it's a bug or my wrong use.

![Snipaste_2024-05-30_17-35-55](https://github.com/iyear/tdl/assets/49014178/8fffe2a2-4abc-4b5b-993e-4aee37d134e3)

### To Reproduce

just forward message from a channel.

### Expected behavior

maybe the CPU and memory info did not go back to the beginning of the line.

### Version

tdl version
Version: 0.17.0
Commit: 95120c0
Date: 2024-04-21T14:07:16Z

go1.21.9 windows/amd64

and linux.

### Which OS are you running tdl on?

Windows

**Comment by iyear** [comment]
What's your terminal? This occurs on some very old terminals.

**Comment by iyzyi** [comment]
@iyear 
cmd.exe (local) and xshell7 (connect to ubuntu) on win10

**Comment by iyear** [comment]
Can you try it on Windows Terminal?

**Comment by iyzyi** [comment]
> Can you try it on Windows Terminal?

same problem on Windows Terminal
![Snipaste_2024-06-05_10-46-50](https://github.com/iyear/tdl/assets/49014178/ed8382fc-ef7b-4bc8-80e5-5ef31764f5ce)

**Comment by leooooooooo** [comment]
> > Can you try it on Windows Terminal?
> 
> same problem on Windows Terminal ![Snipaste_2024-06-05_10-46-50](https://private-user-images.githubusercontent.com/49014178/336697917-ed8382fc-ef7b-4bc8-80e5-5ef31764f5ce.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NDg0NjksIm5iZiI6MTcxNzY0ODE2OSwicGF0aCI6Ii80OTAxNDE3OC8zMzY2OTc5MTctZWQ4MzgyZmMtZWY3Yi00YmM4LTgwZTUtNWVmMzE3NjRmNWNlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDA0MjkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4M2EwNWFjMzU4OGI1YmRlYTU2ZDU3MzA5Yjc1NTI0YjM0MmM5Mzk2OTY5ZGRmOWU2Y2UwYTcxZjQ4ZTU3YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pbDbTnaK34UuSRtiOKiwpLRUbsW0qum7DH5Apyo-8ko)

try wider terminal window
