### ISSUE TITLE
[Bug] Unable to upload files in version 0.17.1

### ISSUE THREAD

**Issue by Noricoo** [iyear/tdl#635]
### Describe the bug

Whether forwarding a message or uploading a local file directly, it can upload at a very fast speed at first, but after a few seconds, the upload rate is no longer shown on the server's network speed monitoring interface, and tdl will show that there is a network speed, but the rate is decreasing, while the size of the uploaded file will not increase, and the progress bar will not increase. All of the above happened in version 0.17.1, before using version 0.17.0 everything was fine.

### To Reproduce

![Snipaste_2024-05-31_07-55-50](https://github.com/iyear/tdl/assets/109935838/5d92217a-37c0-433d-8adb-4aa14b49bd3f)
tdl up -p /path/to/file.mp4
tdl forward --from /path/to/file/tdl-export.json --to ID--desc
Files cannot be uploaded by either method

### Expected behavior

1.fix this bug.
2.please release #565 in binary file asap.

extremely grateful!

### Version

Version: 0.17.1
Commit: 7f4e543
Date: 2024-05-29T14:50:17Z

go1.21.10 linux/amd64

### Which OS are you running tdl on?

Linux

**Comment by Noricoo** [comment]
![Uploading Snipaste_2024-06-01_07-33-33.jpg…]()

**Comment by Noricoo** [comment]
![Snipaste_2024-06-01_07-33-33](https://github.com/iyear/tdl/assets/109935838/21282510-a5b4-4f69-8276-6e0f06e643ba)
erro code

**Comment by Noricoo** [comment]
I don't know how to uninstall it, I reinstalled my system and installed version 0.17.0, using the same commands, I can forward messages from the restricted groups, but the speed suddenly stops during the uploading of the file, well I can continue to upload it after a few moments, but I remember that uploading didn't used to be this phenomenon!
![Snipaste_2024-06-01_13-24-06](https://github.com/iyear/tdl/assets/109935838/d21674fc-9c5b-4b53-b7a9-88cb74e43e7a)

**Comment by iyear** [comment]
I cannot reproduce it locally on v0.17.1. Downloading and uploading large files may trigger server-side throttling and bans, but it's a black box with no good way to bypass it.
