### ISSUE TITLE
[Bug] 当我运行程序大概一小时或者30分钟以上会出现这个报错

### ISSUE THREAD

**Issue by konglquan** [iyear/tdl#648]
### Describe the bug

[Bug] 当我运行程序大概一小时或者30分钟以上会出现这个报错

Error: group:
    github.com/gotd/td/mtproto.(*Conn).Run
        github.com/gotd/td@v0.102.0/mtproto/conn.go:214
  - task readLoop:
    github.com/gotd/td/tdsync.(*LogGroup).Go.func1
        github.com/gotd/td@v0.102.0/tdsync/log_group.go:48
  - read:
    github.com/gotd/td/mtproto.(*Conn).readLoop
        github.com/gotd/td@v0.102.0/mtproto/read.go:193
  - read:
    github.com/gotd/td/transport.(*connection).Recv
        github.com/gotd/td@v0.102.0/transport/connection.go:70
  - read intermediate:
    github.com/gotd/td/proto/codec.Intermediate.Read
        github.com/gotd/td@v0.102.0/proto/codec/intermediate.go:73
  - read length:
    github.com/gotd/td/proto/codec.readLen
        github.com/gotd/td@v0.102.0/proto/codec/codec.go:35
  - EOF

### To Reproduce

.

### Expected behavior

.

### Version

latest

### Which OS are you running tdl on?

Windows

**Comment by iyear** [comment]
https://github.com/iyear/tdl/issues/158#issuecomment-1551116053
