### ISSUE TITLE
[Bug] Cannot download properly when prompted with a restricted download

### ISSUE THREAD

**Issue by Amoiete-Spectrum-Helix** [iyear/tdl#657]
### Describe the bug

In the client, this is manifested by automatically stopping every 50M download for a few seconds.
But when using tdl download, it will not continue to download when it reaches 50M.

### To Reproduce

tdl dl -f tdl-export.json -d "xxx -t 8 -l 4 --proxy xxx

### Expected behavior

When the download is restricted, it will stop automatically and continue to download normally.

### Version

0.17.2

### Which OS are you running tdl on?

Windows

**Comment by nauq520** [comment]
我也有同样的错误，下载到接近50m就会暂停，重试过多次，问题依旧
![1111111111](https://github.com/iyear/tdl/assets/146209139/3ae01a1d-55a4-48b1-a95e-a67da87c89fe)

**Comment by iyear** [comment]
@Amoiete-Spectrum-Helix What's the error reported by tdl?

**Comment by nauq520** [comment]
> @Amoiete-Spectrum-Helixtdl报告的错误是什么？
就是一直卡着没动静，等了很久。重新尝试了多次，还是每次都下载到50m这样就不继续下载了

**Comment by thanhlouis** [comment]
metoo, some link will stuck forever
![image](https://github.com/iyear/tdl/assets/46671319/acf9c27f-6199-4dee-82a4-9d010a962ce4)

**Comment by Amoiete-Spectrum-Helix** [comment]
> @Amoiete-Spectrum-Helix What's the error reported by tdl?

I have to use it if I want to download properly:
tdl dl -f tdl-export.json -d xxx-t 1 -l 1 --proxy xxx --reconnect-timeout 0s
It's a new restriction？

**Comment by iyear** [comment]
@Amoiete-Spectrum-Helix Yes. Add `--reconnect-timeout 0` if your network is poor. The `stuck` means tdl is trying to reconnect to Telegram server.

**Comment by Parantric** [comment]
> ### Describe the bug
> In the client, this is manifested by automatically stopping every 50M download for a few seconds. But when using tdl download, it will not continue to download when it reaches 50M.
> 
> ### To Reproduce
> tdl dl -f tdl-export.json -d "xxx -t 8 -l 4 --proxy xxx
> 
> ### Expected behavior
> When the download is restricted, it will stop automatically and continue to download normally.
> 
> ### Version
> 0.17.2
> 
> ### Which OS are you running tdl on?
> Windows
> 
> ### Additional context
> _No response_

There is indeed such a problem. When the `-t` `-l` parameters are not set properly (of course I don't know what is reasonable😭), the download progress will be stuck at a certain point, and it will not help even if you try many times. After many attempts, the smaller the `-t` and `-l` are set, the more this problem can be avoided.

**Comment by hcqqdctwzsz** [comment]
> @Amoiete-Spectrum-Helix是的。`--reconnect-timeout 0`如果您的网络较差，请添加。这`stuck`意味着 tdl 正在尝试重新连接到 Telegram 服务器。

![捕获](https://github.com/iyear/tdl/assets/32481082/936d5a89-effc-41cf-a5f7-c03f11ace164)

Still unavailable。
