### ISSUE TITLE
How can I query the tags contained in a message? Is there such a filter?

### ISSUE THREAD

**Issue by Parantric** [iyear/tdl#661]
How can I query the tags contained in a message? Is there such a filter?
For example：List channels that VisibleName contains “Telegram”
`**tdl chat ls -f "Type contains 'channel' && VisibleName contains 'Telegram'"**`

**Comment by iyear** [comment]
Use `tdl chat export -c CHAT -f 'Message contains "#TAG"'` to filter out the target messages. Then use `tdl dl -f tdl-export.json` for batch downloading.
