### ISSUE TITLE
[Feat] Please complete title/希望增添过滤为视频时长，有些视频长度太大，并不需要下，只需要下载短视频

### ISSUE THREAD

**Issue by 13299118606** [iyear/tdl#662]
### Proposal

希望增添过滤为视频时长，有些视频长度太大，并不需要下，只需要下载短视频

### Background

希望增添过滤为视频时长，有些视频长度太大，并不需要下，只需要下载短视频

### Workarounds

希望增添过滤为视频时长，有些视频长度太大，并不需要下，只需要下载短视频

**Comment by onlyzyz** [comment]
我目前的做法是先导出raw消息的json文件（这个raw里面包含了Duration时长字段）
然后用jq+命令行提示符精简这个json文件（jq ".messages |= map(if .raw.Media.Document.Attributes[0].Duration < 60 then {id: .id, type: .type, file: .file} elif .raw.Media.Document.Attributes[0].Duration > 60 then empty else . end) | {id: .id, messages: .messages}" input.json > output.json）
最用用精简后的json来下载
