### ISSUE TITLE
[Bug] My Telegram chats don't open when I download a file from the command line

### ISSUE THREAD

**Issue by JetC10** [iyear/tdl#665]
### Describe the bug

I was following the documentation to login and when using the example command: `tdl dl -u https://t.me/telegram/193` and checking the original message it does not let me open the official Telegram chat and no other.

It doesn't let me see any chat, clicking on any chat flashes the desktop client.

### To Reproduce

1. I used `tdl login -p YOUR_PASSCODE`.
2. Downloaded any file `tdl dl -u https://t.me/telegram/193`
3. I opened Telegram Desktop and opened any chat

### Expected behavior

You should let me see the chats, review them.

### Version

Version: 0.17.2
Commit: 291d7f5
Date: 2024-06-19T17:16:23Z

go1.21.11 windows/amd64

### Which OS are you running tdl on?

Windows

### Additional context

Telegram Desktop Version 5.1.7 x64

Note: I don't know if it is important, but for text strings I have used single quotes ('')

**Comment by iyear** [comment]
https://docs.iyear.me/tdl/more/troubleshooting/#q-desktop-client-stop-working-after-using-tdl
