### ISSUE TITLE
[Bug] 转发时，本来是一组的消息会被拆开成两组发送

### ISSUE THREAD

**Issue by konglquan** [iyear/tdl#671]
### Describe the bug

tdl -n xiaoke-ayu forward  --from https://t.me/c/xxx/132130 --from https://t.me/c/xxx/132131 --from https://t.me/c/xxx/132133 --from https://t.me/c/xxx/132135 --from https://t.me/c/xxx/132137 --from https://t.me/c/xxx/132138 --from https://t.me/c/xxx/132140 --from https://t.me/c/xxx/132142 --from https://t.me/c/xxx/132143 --from https://t.me/c/xxx/132145 --edit  'xxxxx'  --to xxx--proxy socks5://localhost:7898  --mode clone 

黑色星期（六...(xxx):132130 -> 六楼后座-全...~ ... done! [1 in 616ms; 1/s]
黑色星期（六...(xxx):132142 -> 六楼后座-全...~ ... done! [1 in 650ms; 1/s]

这条命令会把本来是一组的消息拆成两组发送，我确定这些id是同一组的

### To Reproduce

tdl -n  forward

### Expected behavior

tdl -n  forward

### Version

Version: 0.17.2
Commit: 291d7f5
Date: 2024-06-19T17:16:23Z

go1.21.11 linux/amd64

### Which OS are you running tdl on?

Linux

**Comment by iyear** [comment]
If the forwarded message contains a "grouped message," please only pass one of the messages. tdl will automatically search for the messages in the same group and merge them for sending.

For example: 132130, 132131, 132132, 132133 are part of the same message group. You only need to pass one of them (like 132131).
