### ISSUE TITLE
Bug?) Telegram rate limitations

### ISSUE THREAD

**Issue by ParkJaeSeong** [iyear/tdl#672]
### Describe the bug

Thank you for making such a great program.

I am using a macbook m1 sonoma 14.5 latest version. 

I've tried to extract the chat contents of a channel using the chat export command

I am not getting any message output with a warning message about speed. 

Is there any way I can work around this?

### To Reproduce

```
> tdl chat export @awake --with-content --all -T time -i 1717203578,1720313978 -o json/awake.json
WARN: Export only generates minimal JSON for tdl download, not for backup.
Occasional suspensions are due to Telegram rate limitations, please wait a moment.

Type: time | Input: [1717203578 1720313978]
jaeseongpark-5424845959           ... done! [0 in 578ms; 0/s]

❯ cat json/awake_rea.json
{"id":5424845959,"messages":[]}%                                                                            
```

### Expected behavior

There are no chat messages.

### Version

```
❯ tdl version
Version: 0.17.2
Commit: Homebrew
Date: 2024-06-19T17:16:23Z

go1.22.4 darwin/arm64
```

### Which OS are you running tdl on?

macOS

**Comment by iyear** [comment]
It's the correct execution. Please ensure that there are indeed messages within the time range of 1717203578 to 1720313978. I do not have that group, so I cannot reproduce it.

**Comment by ParkJaeSeong** [comment]
I gave the command without the -c option and didn't get anything. I added the -c option and saw that it downloaded fine.  

Thanks again for creating such a useful programme. It has been a great help to me.
