### ISSUE TITLE
Can real-time monitoring of media messages from a certain group and downloading be achieved 

### ISSUE THREAD

**Issue by pwnhub1024** [iyear/tdl#673]
### Describe the bug

Given that the media messages of the source group have a 60 second time limit and will be automatically destroyed upon expiration, can the media messages be forwarded or downloaded in real time?

### To Reproduce

need help

### Expected behavior

need heep

### Version

lasted

### Which OS are you running tdl on?

Windows

**Comment by iyear** [comment]
Understood. But it's not a functionality that the CLI can handle. Please look forward to the development process in the future.
