### ISSUE TITLE
[Bug] Blocking when using uploads

### ISSUE THREAD

**Issue by jxcone100** [iyear/tdl#674]
### Describe the bug

Twice I've just started using the upload function and my account was blocked before I could even upload it

### To Reproduce

How can I minimize the risk of blocking when uploading

### Expected behavior

Normal upload

### Version

Version: 0.14.1 Commit: 3021de5 Date: 2024-01-05T16:27:43Z go1.19.13 windows/amd64

### Which OS are you running tdl on?

Windows

**Comment by iyear** [comment]
What's your command?

**Comment by DrakeFlorence** [comment]
> What's your command?

我充了会员的老号在上传90张图片之后被光速封号了，换了一个号上传26张图之后也光速被封了。

指令如下：
`tdl login`
`tdl upload --chat "my channel link" --path "my folder" --photo`

**Comment by iyear** [comment]
https://docs.iyear.me/tdl/more/troubleshooting/#best-practices

Telegram's risk control is completely a black box, so minimize large data transmission asap.
