### ISSUE TITLE
下载出错

### ISSUE THREAD

**Issue by henji20** [iyear/tdl#675]
### Describe the bug

Error: group:
    github.com/gotd/td/mtproto.(*Conn).Run
        github.com/gotd/td@v0.105.0/mtproto/conn.go:214
  - task readLoop:
    github.com/gotd/td/tdsync.(*LogGroup).Go.func1
        github.com/gotd/td@v0.105.0/tdsync/log_group.go:48
  - read:
    github.com/gotd/td/mtproto.(*Conn).readLoop
        github.com/gotd/td@v0.105.0/mtproto/read.go:193
  - read:
    github.com/gotd/td/transport.(*connection).Recv
        github.com/gotd/td@v0.105.0/transport/connection.go:70
  - read intermediate:
    github.com/gotd/td/proto/codec.Intermediate.Read
        github.com/gotd/td@v0.105.0/proto/codec/intermediate.go:73
  - read length:
    github.com/gotd/td/proto/codec.readLen
        github.com/gotd/td@v0.105.0/proto/codec/codec.go:35

### To Reproduce

Error: group:
    github.com/gotd/td/mtproto.(*Conn).Run
        github.com/gotd/td@v0.105.0/mtproto/conn.go:214
  - task readLoop:
    github.com/gotd/td/tdsync.(*LogGroup).Go.func1
        github.com/gotd/td@v0.105.0/tdsync/log_group.go:48
  - read:
    github.com/gotd/td/mtproto.(*Conn).readLoop
        github.com/gotd/td@v0.105.0/mtproto/read.go:193
  - read:
    github.com/gotd/td/transport.(*connection).Recv
        github.com/gotd/td@v0.105.0/transport/connection.go:70
  - read intermediate:
    github.com/gotd/td/proto/codec.Intermediate.Read
        github.com/gotd/td@v0.105.0/proto/codec/intermediate.go:73
  - read length:
    github.com/gotd/td/proto/codec.readLen
        github.com/gotd/td@v0.105.0/proto/codec/codec.go:35

### Expected behavior

不知道说明原因

### Version

17

### Which OS are you running tdl on?

Windows

**Comment by henji20** [comment]
请问一下这个是说明报错

**Comment by iyear** [comment]
https://docs.iyear.me/tdl/guide/global-config/#--proxy

**Comment by 5536086** [comment]
> https://docs.iyear.me/tdl/guide/global-config/#--proxy

我也遇到了相同错误，下载过程中概率出现，国外机器，不存在过墙问题

**Comment by henji20** [comment]
请问一下，我是用路由器科学上网的。还需要设置代理吗？
protocol://username:password@host:port这个命令里面的用户名和密码填哪一个？ host还有后面的端口怎么设置

**Comment by LDNKS** [comment]
完全一样的问题，基本上是在单个文件下载超过5分钟就会遇到

**Comment by babyNEKO** [comment]
我也遇到了，运行了一会儿，就出现报错
网络也没什么问题
![屏幕截图 2024-08-02 215050](https://github.com/user-attachments/assets/554af419-200b-4264-9ca5-1ef2a6a1c0ff)

**Comment by dream10201** [comment]
同样的问题，就这个文件下到一定程度就报错，前面下了几百个没问题。国外机器，不存在墙的问题。看了下，就这个文件比较大
`
All files will be downloaded to '/root/download' dir
567.mp4~ ... 94.8% [################################..] [3.25 GB in 7m20.617s; ~ETA: 28s; 7.55 MB/s]
[################################################################################################################################################..........] [7m21s; 7.55 MB/s]
Error: group:
    github.com/gotd/td/mtproto.(*Conn).Run
        github.com/gotd/td@v0.105.0/mtproto/conn.go:214
  - task readLoop:
    github.com/gotd/td/tdsync.(*LogGroup).Go.func1
        github.com/gotd/td@v0.105.0/tdsync/log_group.go:48
  - read:
    github.com/gotd/td/mtproto.(*Conn).readLoop
        github.com/gotd/td@v0.105.0/mtproto/read.go:193
  - read:
    github.com/gotd/td/transport.(*connection).Recv
        github.com/gotd/td@v0.105.0/transport/connection.go:70
  - read intermediate:
    github.com/gotd/td/proto/codec.Intermediate.Read
        github.com/gotd/td@v0.105.0/proto/codec/intermediate.go:73
  - read length:
    github.com/gotd/td/proto/codec.readLen
        github.com/gotd/td@v0.105.0/proto/codec/codec.go:35
  - EOF
root@rn:~# tdl dl -l 1 -f /opt/na.json -d /root/download --skip-same --continue -i mp4,mkv,MP4,MKV
Found unfinished download, continue from '74/92'
All files will be downloaded to '/root/download' dir
567.mp4~ ... 83.4% [############################......] [2.86 GB in 7m18.812s; ~ETA: 1m30s; 6.68 MB/s]
[###############################################################################################################################...........................] [7m19s; 6.68 MB/s]
Error: group:
    github.com/gotd/td/mtproto.(*Conn).Run
        github.com/gotd/td@v0.105.0/mtproto/conn.go:214
  - task readLoop:
    github.com/gotd/td/tdsync.(*LogGroup).Go.func1
        github.com/gotd/td@v0.105.0/tdsync/log_group.go:48
  - read:
    github.com/gotd/td/mtproto.(*Conn).readLoop
        github.com/gotd/td@v0.105.0/mtproto/read.go:193
  - read:
    github.com/gotd/td/transport.(*connection).Recv
        github.com/gotd/td@v0.105.0/transport/connection.go:70
  - read intermediate:
    github.com/gotd/td/proto/codec.Intermediate.Read
        github.com/gotd/td@v0.105.0/proto/codec/intermediate.go:73
  - read length:
    github.com/gotd/td/proto/codec.readLen
        github.com/gotd/td@v0.105.0/proto/codec/codec.go:35
  - EOF

`

**Comment by iyear** [comment]
If it is a network issue, please ensure you use the `--proxy` flag. 
If the network is unstable, use the `--reconnect-timeout 0` flag.
