### ISSUE TITLE
[Bug] Unable to log in and download

### ISSUE THREAD

**Issue by nikkoozz** [iyear/tdl#677]
### Describe the bug

之前用过 没有任何问题，最近报错无法使用
用了代理，环境变量里设置 TDL_PROXY  =  socks5://localhost:10808     TDL_NS =  admin
以下分别是**登录**和**下载**的报错情况：

### To Reproduce

 tdl login -d "D:\soft\Telegram Desktop"
Error: decrypt keyEncrypted:
    github.com/gotd/td/session/tdesktop.readKeyData
        github.com/gotd/td@v0.105.0/session/tdesktop/key_data.go:33
  - msg_key mismatch:
    github.com/gotd/td/session/tdesktop.decryptLocal
        github.com/gotd/td@v0.105.0/session/tdesktop/local_key.go:67

tdl dl -u https://t.me/xxx/1 -d "D:\Downloads"
Error: create client:
    github.com/iyear/tdl/cmd.tRun
        github.com/iyear/tdl/cmd/root.go:159
  - create network clock:
    github.com/iyear/tdl/core/tclient.New
        github.com/iyear/tdl/core@v0.0.0-00010101000000-000000000000/tclient/tclient.go:47
  - read udp 192.168.0.106:54775->108.59.2.24:123: i/o timeout

### Expected behavior

正常使用

### Version

0.17.3

### Which OS are you running tdl on?

Windows

**Comment by nikkoozz** [comment]
电脑登录tg后，再用tdl下载报错：
Error: callback:
    github.com/gotd/td/telegram.(*Client).Run.func3
        github.com/gotd/td@v0.105.0/telegram/connect.go:151
  - not authorized. please login first

**Comment by Xavier8216** [comment]
same problem here

**Comment by Xavier8216** [comment]
> 电脑登录tg后，再用tdl下载报错： Error: callback: github.com/gotd/td/telegram.(*Client).Run.func3 github.com/gotd/td@v0.105.0/telegram/connect.go:151
> 
> * not authorized. please login first

same problem here

**Comment by celiae** [comment]
再次运行报此错，尝试了切换tun模式就又行了

**Comment by shaoyangx** [comment]
> 电脑登录tg后，再用tdl下载报错： Error: callback: github.com/gotd/td/telegram.(*Client).Run.func3 github.com/gotd/td@v0.105.0/telegram/connect.go:151
> 
> * not authorized. please login first

我也是同样的报错，即使从新登陆在下载也不行。

**Comment by iyear** [comment]
`not authorized. please login first` Perform the login operation again.

**Comment by nikkoozz** [comment]
I found the reason, it was caused by setting the lock screen password for the desktop client, I hope the author can optimize it in the future, thanks!

**Comment by iyear** [comment]
@nikkoozz If you set the desktop client passcode, you should set flags: `tdl login -p YOUR_PASSCODE`
