### ISSUE TITLE
[Bug] failed execute any command after login

### ISSUE THREAD

**Issue by Hurpods** [iyear/tdl#679]
### Describe the bug

when i use `tdl chat ls` .it just stuck and shows nothing,just like this:![image](https://github.com/user-attachments/assets/a39cd260-d162-4ce3-9567-a97ded87dd2a)
I have already set my proxy with TDL_PROXY:
![image](https://github.com/user-attachments/assets/4d84a2b1-ee7c-488b-84a3-b6ddeec8e180)
My proxy works fine that i could use telegram or other website normaly and i conrim that the port is correct AND i could use tdl normaly several days ago

### To Reproduce

1. tdl login
2. tdl chat ls

### Expected behavior

it should list all my chat

### Version

Version: 0.17.3
Commit: 6c382b8
Date: 2024-07-07T10:59:56Z

go1.21.11 windows/amd64

### Which OS are you running tdl on?

Windows

### Additional context

here is the full log betweenI execute `tdl login` and `ctrl + C`. I just hide my namespace as *
[latest.log](https://github.com/user-attachments/files/16227728/latest.log)

**Comment by qwsxmkoi** [comment]
I usually have the same problem, and usually it's solved when I get a brand new VM system

**Comment by lpker** [comment]
I encountered the same issue, and I found that it was related to the system time on my TDL computer. You can try changing your computer’s region and updating it to the current time for that region. After I did this, I was able to get the program’s output correctly.

**Comment by iyear** [comment]
https://docs.iyear.me/tdl/more/troubleshooting/#q-why-no-response-after-entering-the-command-and-why-there-is-msg_id-too-high-in-the-log
