### ISSUE TITLE
Wrong title and name

### ISSUE THREAD

**Issue by ayush-out** [iyear/tdl#683]
### Describe the bug

Hey there,
this tool is very good 

but there is one issue which is invalid file name
whatever file that are being downloaded are given a random name which makes it difficult to track the files

I just want the file to get downloaded in their name itself.

Thanks for the tool btw.

### To Reproduce

Download any file

### Expected behavior

Random jibberish name 

### Version

Version: 0.17.3
Commit: 6c382b8
Date: 2024-07-07T10:59:56Z

go1.21.11 linux/amd64
 

### Which OS are you running tdl on?

Linux

**Comment by iyear** [comment]
Follow the https://docs.iyear.me/tdl/guide/download/#name-template to use custom file name you want
