### ISSUE TITLE
[Feat] Is it possible to compile a version of serv00?

### ISSUE THREAD

**Issue by huomqh** [iyear/tdl#697]
### Proposal

编译SERV00版本的话，可以配合alist的加密功能，把telegram的小电影传到网盘里

### Background

把telegram的小电影传到网盘里

### Workarounds

把telegram的小电影传到网盘里

**Comment by iyear** [comment]
It looks like `serv00` needs to use the FreeBSD binary file. The official release does not provide that version.

Duplicate of https://github.com/iyear/tdl/issues/389
