### ISSUE TITLE
fastest settings [help wanted]

### ISSUE THREAD

**Issue by Hiradpi** [iyear/tdl#698]
hello ,
sorry to ask this in the issues but what are the fastest arguments for downloading multiple large files ?

**Comment by RaheesAhmed** [comment]
For fastest downloads of multiple large files with tdl, use these arguments: "-j 8" to enable 8 simultaneous connections, "--chunk-size 20M" for larger 20MB chunks, and "--premium" if you have Telegram Premium. These settings maximize your bandwidth usage and speed up downloads. Adjust the number after "-j" based on your internet speed - higher for faster connections, lower for slower ones. Remember, actual speed also depends on Telegram's servers and your internet connection, so you might need to fine-tune these settings for best results.

**Comment by Hiradpi** [comment]
Im not sure if im missing something here but there is no flag "-j"

**Comment by Hiradpi** [comment]
my internet is very good (1gbps) and i have 1gb free ram

**Comment by Hiradpi** [comment]
maybe add something that uses multiple telegram accounts and proxies to avoid telegram's limitations ?

**Comment by iyear** [comment]
`--pool 0 --reconnect-timeout 0 -t 16(or higher) -l 4(or higher)`

Note that the final download speed will still be limited by the Telegram servers.
