### ISSUE TITLE
[Feat] Manual naming for downloaded files

### ISSUE THREAD

**Issue by liponex** [iyear/tdl#699]
### Proposal

When downloading using the `-u url` key list, it would be nice to specify the filename as well.
This can be done as a new key, such as `-u url --filename "filename"` or without `-u url "filename"`.

### Background

When I manually download the necessary files, I have to manually rename each file after downloading. Templates do not solve this problem.

### Workarounds

No😥

**Comment by iyear** [comment]
https://docs.iyear.me/tdl/guide/download/#name-template
