### ISSUE TITLE
Add --template to environment variables

### ISSUE THREAD

**Issue by art435** [iyear/tdl#70]
To make things simpler I would like to use tdl whiteout writing the template syntax every time in command line. But currently is not possible because `--template` can be use only as a a flag. Please add this to environment variables too.

**Comment by iyear** [comment]
Accepted

**Comment by art435** [comment]
Thank you! I appreciate your effort for creating this helpful program.

**Comment by iyear** [comment]
I have released a new version that may solve this problem. Feel free to try it out.

https://github.com/iyear/tdl/releases/tag/v0.6.0-beta
