### ISSUE TITLE
[Bug] Chat Export is throwing error 400: USERNAME_NOT_OCCUPIED

### ISSUE THREAD

**Issue by sachinkmr** [iyear/tdl#700]
### Describe the bug

Running the command `tdl chat export -c CHAT` to get chat JSON is throwing following error: 

Error: callback:
    github.com/gotd/td/telegram.(*Client).Run.func3
        github.com/gotd/td@v0.105.0/telegram/connect.go:151
  - failed to get peer: resolve: retry middleware skip: rpcDoRequest: rpc error code 400: USERNAME_NOT_OCCUPIED
  -

### To Reproduce

Run the command `tdl chat export -c CHAT`

### Expected behavior

should generate json file having chats related data

### Version

Version: 0.17.3
Commit: 6c382b8
Date: 2024-07-07T10:59:56Z

go1.21.11 linux/amd64

### Which OS are you running tdl on?

Linux

**Comment by iyear** [comment]
You should replace the `CHAT` in command with specific real chat value.

`CHAT` can be:
- `@iyear`
- `iyear`
- `123456789` (ID)
- `https://t.me/iyear`
- `+1 123456789` (Phone)
