### ISSUE TITLE
[Bug] The error has occurred. Export only generates minimal JSON for tdl download, not for backup.”

### ISSUE THREAD

**Issue by hhtnFxQVwQntBLkULKjy** [iyear/tdl#703]
### Describe the bug

WARN: Export only generates minimal JSON for tdl download, not for backup.
Occasional suspensions are due to Telegram rate limitations, please wait a moment.

Type: last | Input: [4]
Error: callback:
    github.com/gotd/td/telegram.(*Client).Run.func3
        github.com/gotd/td@v0.105.0/telegram/connect.go:151
  - open D:\anzhuang\tdl_Windows_64bit: is a directory

### To Reproduce

tdl chat export -c 00000000 -T last -i 4 -o D:\aqaqaqa\tdl_Windows_64bit

### Expected behavior

Correct Download

### Version

Version: 0.17.3
Commit: 6c382b8
Date: 2024-07-07T10:59:56Z

go1.21.11 windows

### Which OS are you running tdl on?

Windows

### Additional context

The content of the channel to be downloaded is a private channel and cannot forward the content of the channel, which has been successfully downloaded previously

**Comment by iyear** [comment]
`-o D:\aqaqaqa\tdl_Windows_64bit` -> `-o D:\aqaqaqa\tdl_Windows_64bit\export.json`

You should specify a file instead of a dir.
