### ISSUE TITLE
[Bug] Does not continue due to incorrect file name

### ISSUE THREAD

**Issue by dkaslsdfds** [iyear/tdl#704]
### Describe the bug
```
{"id":12345,"type":"message","file":"UserID:     11111111\nName:      qwerty.mkv"}
``` 
```
 - open downloads\9999999999_12345_UserID______11111111
Name_______qwerty.mkv.tmp: The filename, directory name, or volume label syntax is incorrect.
``` 

### To Reproduce

tdl dl -f asd.json --skip-same

### Expected behavior

skip or rename

### Version

Version: 0.17.3
Commit: 6c382b8
Date: 2024-07-07T10:59:56Z

go1.21.11 windows/amd64

### Which OS are you running tdl on?

Windows

**Comment by iyear** [comment]
Use https://docs.iyear.me/tdl/guide/download/#name-template to customize your "safe" file name.

**Comment by iyear** [comment]
v0.18.1 supports using the `filenamify` helper function in the downloader template to get safe file names.
