### ISSUE TITLE
[Feat] Please complete title/login timeout and How login tdl using .session file

### ISSUE THREAD

**Issue by wenrouyue** [iyear/tdl#706]
### Proposal

Run the tdl login -T code -n test1 command to login to the system for about 20 or 30 times.
There will be an error
start: create auth key: write SetClientDHParamsRequest: write: write intermediate: write tcp 194.36.209.147:33846->149.154.167.50:443: i/o timeout

![image](https://github.com/user-attachments/assets/73b37e18-b617-4778-89a9-01d97d6a104f)

Is this the official limit?

And How login tdl using .session file

### Background

login timeout and How login tdl using .session file

### Workarounds

login timeout and How login tdl using .session file

**Comment by iyear** [comment]
`194.36.209.147` is your local IP. You should use `--proxy` flag to pass GFW. https://docs.iyear.me/tdl/guide/global-config/#--proxy
