### ISSUE TITLE
[Bug] Error during Forward (Clone mode)

### ISSUE THREAD

**Issue by xd003** [iyear/tdl#715]
### Describe the bug

TDL randomly crashes after forwarding a bunch of files with the following error
```
Error: group:
    github.com/gotd/td/mtproto.(*Conn).Run
        github.com/gotd/td@v0.102.0/mtproto/conn.go:214
  - task readLoop:
    github.com/gotd/td/tdsync.(*LogGroup).Go.func1
        github.com/gotd/td@v0.102.0/tdsync/log_group.go:48
  - read:
    github.com/gotd/td/mtproto.(*Conn).readLoop
        github.com/gotd/td@v0.102.0/mtproto/read.go:193
  - read:
    github.com/gotd/td/transport.(*connection).Recv
        github.com/gotd/td@v0.102.0/transport/connection.go:70
  - read intermediate:
    github.com/gotd/td/proto/codec.Intermediate.Read
        github.com/gotd/td@v0.102.0/proto/codec/intermediate.go:73
  - read length:
    github.com/gotd/td/proto/codec.readLen
        github.com/gotd/td@v0.102.0/proto/codec/codec.go:35
  - EOF
  ```

### To Reproduce

1) tdl chat export -c CHAT --all
2) tdl forward --from tdl-export.json --to CHAT --desc

### Expected behavior

It should complete the fowarding process without any errors

### Version

❯ tdl version
Version: 0.17.1
Commit: 7f4e543
Date: 2024-05-29T14:50:17Z

go1.21.10 linux/arm64

### Which OS are you running tdl on?

Linux

**Comment by strongcore** [comment]
Hi , I am also facing the same issue as above user xd003.

**Comment by iyear** [comment]
https://github.com/iyear/tdl/issues/158#issuecomment-1551140735
