### ISSUE TITLE
[Bug]  Submodule `core` is not properly tagged

### ISSUE THREAD

**Issue by HappyHacker123** [iyear/tdl#716]
### Describe the bug

I found that module `github.com/iyear/tdl/core` is a submodule of   `tdl`.

However, it seems that submodule  `github.com/iyear/tdl/core` is not tagged. According to [Go Modules standard](https://go.dev/wiki/Modules#what-are-multi-module-repositories) , submodule should be tagged like relative-path-to-root/vX.X.X.
At now, when trying to import package `github.com/iyear/tdl/core`, downstream project would have to depend on pseudo-version of it and cannot get a valid tag version.
```
require github.com/iyear/tdl/core v0.0.0-20240823091726-3a4242ab89c9 
```

### To Reproduce

1.  run `go get github.com/iyear/tdl/core v0.17.3`
2. see error

### Expected behavior

To address this, i think it's better to tag submodules properly according to Go standard, for example, releasing a tag `core/v0.17.3``, so that other project can use tag version to import this module in go.mod.

### Version

Version: 0.17.3

### Which OS are you running tdl on?

macOS

**Comment by HappyHacker123** [comment]
@iyear  Could you please take a look at this issue :)? The problem can be solved simply by releasing  a tag for `core`.

**Comment by iyear** [comment]
Sorry, I've been busy preparing for interviews.

`core/v0.17.4` has been released. I'm considering adding submodule tags to pipeline.
