### ISSUE TITLE
[Feat] the message may be deleted

### ISSUE THREAD

**Issue by profumato4** [iyear/tdl#717]
### Proposal

So sometime i have an error that say the message x may be deleted and to solve this i have to remove the message with the id in my json file i suggest u to skip automaticlly the file when it's marked as deletes i hope u'll understand what i mean my english is very bad 

### Background

So sometime i have an error that say the message x may be deleted and to solve this i have to remove the message with the id in my json file i suggest u to skip automaticlly the file when it's marked as deletes i hope u'll understand what i mean my english is very bad 

### Workarounds

So sometime i have an error that say the message x may be deleted and to solve this i have to remove the message with the id in my json file i suggest u to skip automaticlly the file when it's marked as deletes i hope u'll understand what i mean my english is very bad

**Comment by iyear** [comment]
This is just an error message, and it won't affect any download progress

**Comment by matru** [comment]
Had this happen few days ago to me, 2 or 3 times, on a different occasion. Unfortunately this is not just a warning, it quits the process, and as importantly, when it does happen it does not remember the last message position, it just asks you if you want to continue completely a new (or from a previously saved position, say I cancel a transfer on my own before the error happens):

`Error: callback:
    github.com/gotd/td/telegram.(*Client).Run.func3
        github.com/gotd/td@v0.110.1/telegram/connect.go:151
  - iter:
    github.com/iyear/tdl/core/downloader.(*Downloader).Download
        github.com/iyear/tdl/core@v0.18.5/downloader/downloader.go:61
  - resolve message:
    github.com/iyear/tdl/app/dl.(*iter).process
        github.com/iyear/tdl/app/dl/iter.go:164
  - the message channel_id/message_id may be deleted:
    github.com/iyear/tdl/core/util/tutil.GetSingleMessage
        github.com/iyear/tdl/core@v0.18.5/util/tutil/tutil.go:190
`

**Comment by YongTsao** [comment]
Ran into the same issue — you'll need to manually remove the corresponding entry, or the download can't proceed.

**Comment by zebrapurring** [comment]
Recently ran into the same issue, @iyear can we make the error a warning and continue the download instead of stopping? Otherwise downloading messages in batch is basically impossible.

**Comment by Mdgmarcel** [comment]
I recently ran into the same issue. In the command line tdl prints the callback and stops the downloading process.
