### ISSUE TITLE
Bug - tdl appends double extensions to files downloaded

### ISSUE THREAD

**Issue by art435** [iyear/tdl#72]
I download some files, but they appear with double extensions, like `filename.rtf.rtf`, but the original file is named correctly `filename.rtf`

**Comment by iyear** [comment]
This is a strategy adopted by tdl, the MIME (which can be customized) and the suffix name may not match when Telegram uploads it. This causes you may not be able to open the file after download.

How do you think it's better?

**Comment by art435** [comment]
If the program checks for MIME, then should do this: If MIME and extension match, keep the extension and do not append. If MIME and extension doesn't match, use the correct MIME extension and replace the old one.

Where are these settings?

**Comment by iyear** [comment]
I will provide an option to solve this problem.

Option `--rewrite-ext`, a boolean flag that is turned off by default (as much as possible without actively hacking into the user's files and causing trouble)

What do you think?

**Comment by art435** [comment]
Thanks!

**Comment by iyear** [comment]
I have released a new version that may solve this problem. Feel free to try it out.

https://github.com/iyear/tdl/releases/tag/v0.6.0-beta
