### ISSUE TITLE
clarification for the takeout option

### ISSUE THREAD

**Issue by Hiradpi** [iyear/tdl#723]
### Proposal

please consider updating the [document](https://docs.iyear.me/tdl) and explain what the --takeout (takeout session) really does and why it does not work 
as said in  the issue #247 there has been problems with this option 
<3 

### Background

when using the option takeout session download does not start and tdl crashesh and only can be exited by killing the prosses

### Workarounds

removing the option or fixing it

**Comment by iyear** [comment]
Please try v0.17.5, and I fixed it.
