### ISSUE TITLE
[Bug] An error occurred using the download from json file

### ISSUE THREAD

**Issue by f6w271** [iyear/tdl#729]
### Describe the bug

[################################################################.] [5h19m0s; 821.36 KB/s]
Error: group:
    github.com/gotd/td/mtproto.(*Conn).Run
        github.com/gotd/td@v0.105.0/mtproto/conn.go:214
  - task readLoop:
    github.com/gotd/td/tdsync.(*LogGroup).Go.func1
        github.com/gotd/td@v0.105.0/tdsync/log_group.go:48
  - read:
    github.com/gotd/td/mtproto.(*Conn).readLoop
        github.com/gotd/td@v0.105.0/mtproto/read.go:193
  - read:
    github.com/gotd/td/transport.(*connection).Recv
        github.com/gotd/td@v0.105.0/transport/connection.go:70
  - read intermediate:
    github.com/gotd/td/proto/codec.Intermediate.Read
        github.com/gotd/td@v0.105.0/proto/codec/intermediate.go:73
  - read length:
    github.com/gotd/td/proto/codec.readLen
        github.com/gotd/td@v0.105.0/proto/codec/codec.go:35
  - EOF

### To Reproduce

1、tdl dl -f .\【国内】工作.json .\【国内】工作\
[【国内】工作.json](https://github.com/user-attachments/files/17051647/default.json)
[【国内】工作.json](https://github.com/user-attachments/files/17051647/default.json)
[【国内】工作.json](https://github.com/user-attachments/files/17051647/default.json)

### Expected behavior

Correct download

### Version

v0.17.4 

### Which OS are you running tdl on?

Windows

### Additional context

![屏幕截图 2024-09-19 081635](https://github.com/user-attachments/assets/d6452bb0-e866-44b2-940a-92f4b7000059)
![屏幕截图 2024-09-19 081635](https://github.com/user-attachments/assets/d6452bb0-e866-44b2-940a-92f4b7000059)
![屏幕截图 2024-09-19 081635](https://github.com/user-attachments/assets/d6452bb0-e866-44b2-940a-92f4b7000059)

**Comment by iyear** [comment]
https://github.com/iyear/tdl/issues/158#issuecomment-1551116053
