### ISSUE TITLE
Add option to set custom download path

### ISSUE THREAD

**Issue by art435** [iyear/tdl#73]
Now the default is folder `downloads` located in the root directory of the program. Please make possible to use other locations too.

**Comment by iyear** [comment]
Accepted.

Previously, the focus was on developing features and not investing too much in customization options.

**Comment by art435** [comment]
Thanks!

**Comment by iyear** [comment]
I have released a new version that may solve this problem. Feel free to try it out.

https://github.com/iyear/tdl/releases/tag/v0.6.0-beta
