### ISSUE TITLE
login Error: Incorrect function.

### ISSUE THREAD

**Issue by devil233-ui** [iyear/tdl#737]
### Describe the bug

it always occurs when i enter the order
`tdl login -d /path/to/TelegramDesktop`

### To Reproduce

1.keep the tg client active
2.try to login the tdl
3.it just go on and i cant do anything

### Expected behavior

login successflly

### Version

> Version: 0.17.4
Commit: c63abd1
Date: 2024-09-08T15:56:41Z
go1.21.13 windows/amd64

### Which OS are you running tdl on?

Windows

### Additional context

![image](https://github.com/user-attachments/assets/17709688-a0a5-4483-b7bd-57ecb0910a04)

**Comment by iyear** [comment]
https://github.com/AlecAivazis/survey fails on Windows Git bash(mingw64), so try to change terminal.

Ref: https://github.com/AlecAivazis/survey/issues/148

**Comment by devil233-ui** [comment]
> https://github.com/AlecAivazis/survey fails on Windows Git bash(mingw64), so try to change terminal.
> 
> Ref: [AlecAivazis/survey#148](https://github.com/AlecAivazis/survey/issues/148)

感谢，顺便测了下ps也不是很稳定。（也许可以在教程里提一嘴？）

另外，我登上去后也卡#542 的代理问题了
下面两种命令我都试过了，实在不知道哪里有问题
![image](https://github.com/user-attachments/assets/f7c93430-3433-47b6-846b-51f9197ff485)
`tdl -n devil --proxy http://localhost:10809`
`tdl -n devil --proxy socks5://localhost:10808`
