### ISSUE TITLE
Add filters for files when downloading

### ISSUE THREAD

**Issue by art435** [iyear/tdl#74]
Now the programs downloads all files. I would like an option to choose the type of files. Maybe Telegram types (videos, audios, documents), and some additional filters (whitelists/blacklists) based on file extensions. For example, I would like to be able to download only flac type and avoid mp3.

Edited, because I see that there are filters for uploading.

**Comment by iyear** [comment]
Accepted.

**Comment by art435** [comment]
Thank you!

**Comment by iyear** [comment]
I have released a new version that may solve this problem. Feel free to try it out.

https://github.com/iyear/tdl/releases/tag/v0.6.0-beta
