### ISSUE TITLE
[Bug] Cannot download files which need more time than 6mins. 

### ISSUE THREAD

**Issue by Lilacist** [iyear/tdl#743]
### Describe the bug

If the file need more than 6mins to download it will crash.
![捕获](https://github.com/user-attachments/assets/38b78a07-7f22-445c-943d-7f3a87e05192)

### To Reproduce

my command is 'tdl download -f 1145140000.json -i mp4,mov,mkv,MP4,MOV,MKV --proxy http://localhost:7890 --debug'
About 6 minutes later, it will crash.
![捕获](https://github.com/user-attachments/assets/2d030933-7e40-4174-bec0-c724e56a45d1)

### Expected behavior

download normally.

### Version

Version: 0.17.5
Commit: ec66ab1
Date: 2024-10-03T04:38:23Z

go1.21.13 windows/amd64

### Which OS are you running tdl on?

Windows

**Comment by Lilacist** [comment]
It seems that Telegram added new FLOOD_PREMIUM_WAIT error, but, it's just for notification, and should not stop uploading/downloading. Maybe tdl treat it like an exception threw by download progress.

**Comment by iyear** [comment]
Try flag `--reconnect-timeout 0`
