### ISSUE TITLE
Detect duplicates when uploading/downloading

### ISSUE THREAD

**Issue by art435** [iyear/tdl#75]
When downloading/uploading, the program should check for files with identical names (they are most likely duplicates), and to be sure calculate their md5 hashes, If detect duplicates erase the duplicates and keep only one file.

But files could have different names and still same content, so the program should check for their sizes too, when identical calculate md5 hash to be sure, If duplicates, delete them and keep only one file.

Now the program downloads all files including duplicates and these take a lot o space.

**Comment by iyear** [comment]
It makes sense to skip identical files, but it is a difficult operation to calculate whether the files are identical or not. Telegram does not provide a hash of the entire file.

**Comment by art435** [comment]
If Telegram doesn't provide the file hashes, I think it provides 2 other parameters, the filenames and file sizes. There are 2 case scenarios.
1. The files have identical names. Probably duplicates.
2.  The files have identical sizes, most probably duplicates (but false positive increases in the case of small files). 

The solutions. The program should keep a list with the filenames and their sizes.
1. Fast one. If new files requested have identical names or identical sizes with files already downloaded, the program should not download them again. Advantage: speed. Disadvantage: some files could wrongly be considered duplicates and missed.
2. Safe one. If new files have identical names or identical sizes, the program should dump them in a new folder named Duplicates. The users could check their hashes after. Advantage: safety. Disadvantage: more space used, more time to complete, more bandwidth utilized.
3. Relatively fast and safe. When requested files have same name and sizes with files already downloaded, the program should download them anyway, put them in a different folder, then should calculate hashes and delete duplicates. Advantage: safety, less space used overall. Disadvantage: more time to complete, more bandwidth used.

Probably 2 and 3 are the optimal solutions for users to choose from. The tradeoff is between speed and safety, and users should decide what is best for them. I think these 2 should be implemented. What do you think?

**Comment by iyear** [comment]
Thank you very much for the solution options. I also think 2 is a good choice, but I tend to put it in the same directory and just mark the file name with "maybe duplicate".

**Comment by art435** [comment]
I was thinking about different folder because is easier to delete after. What do you think about solution number 3? In that, the program should handle the duplicate checking and deleting, so will take less time too. It has the advantage that it takes less space because the files are deleted in real time and not after. 

For example, I recently download a whole channel, about 500 GB, from which about 300 GB were duplicates. If users have limited space, solution number 2 will not be optimal for them, but the number 3 will work because it will take less space.

**Comment by iyear** [comment]
I have released a new version that may solve this problem. Feel free to try it out.

https://github.com/iyear/tdl/releases/tag/v0.6.0-beta

**Comment by art435** [comment]
The new version prevents some duplicates to be downloaded, which is good. Thanks again. But there are some with different names and same content that still pass. How to deal with those?

 You said  `Telegram does not provide a hash of the entire file`. At least it provides the hash for partial file? Can this be used with size to detect further duplicates? If sizes and partial hashes match, is probably a duplicate.

**Comment by iyear** [comment]
Normal user behavior is either to move downloaded files elsewhere or to leave it untouched. tdl cannot anticipate all user behaviors. After renaming the file and then not wanting tdl to re-download it, I don't quite understand the purpose of this action.

`skip-same` works before the download and not after, so it cannot be compared based on hash.

**Comment by art435** [comment]
I'll try to explain more clear. Files in chat
Name.pdf
Name1.pdf
Name.pdf
 
All have the same content, same size, 2 have also the same name. One of those is not downloaded (same name+same size=duplicate). One with different name, but same size and content still passed. So maybe add a new logic, if same size and different name = duplicate?

**Comment by iyear** [comment]
For the default configuration, the download filename contains the msg id, perhaps as a temporary solution. Showing the last msg id is still a problem for multiple sources. I have no idea how to better display them.

I will file a new issue to track the exporting issue.

**Comment by iyear** [comment]
Does this mean that if you need to find duplicate files, tdl needs to compare the hash of all files in the download directory one by one. This seems too onerous.

**Comment by art435** [comment]
Let's forget about comparing by hash, it is too complicated. Keep `--skip-same` as it is. Add a new option `--skip-size`, which also prevents downloading files that have the same size (but different names) with the ones already downloaded.

If the files are big, same sizes mostly mean duplicates. If the files are smaller and in big number, the same size could wrongly identify them as duplicates. Users should be aware of this limitation.
