### ISSUE TITLE
[Bug] Please complete title/请完善标题Unable to download from groups.

### ISSUE THREAD

**Issue by shoval6** [iyear/tdl#760]
### Describe the bug

I tried to download from several groups I have (not private) , but I always got an error message.
When I'm trying to download from telegram official group as described in docs , everything is good.
(tdl dl -u https://t.me/telegram/193)

### To Reproduce

1. run tdl dl -u https://t.me/ESLDCBGV
2. get error message : 
![ללא שם](https://github.com/user-attachments/assets/b0c1c645-17ae-40b9-834e-6298025cf4d8)

### Expected behavior

download content from a group

### Version

tdl 0.17.5

### Which OS are you running tdl on?

Windows Server 2022 Standard

**Comment by iyear** [comment]
Please pass the correct message link: https://t.me/CHAT/MESSAGE_ID
