### ISSUE TITLE
[Bug] Private Channel Downloading Not Working

### ISSUE THREAD

**Issue by cheese529** [iyear/tdl#772]
### Describe the bug

So i've been trying to download this entire private group for an hour now but it's not working, I made sure to login correctly, I am in the group and I can view the videos as well but running the command gives me this error. 
![image](https://github.com/user-attachments/assets/9a73d8ad-42dc-44c2-88c1-e1cbe3cc4706)

### To Reproduce

1. Run tdl.exe dl -u https://t.me/privategroup --desc

### Expected behavior

It should download all the contents of the private channel, along with json in the correct order. 

### Version

Version: 0.17.6
Commit: fde9716
Date: 2024-10-25T06:38:43Z

go1.21.13 windows/amd64

### Which OS are you running tdl on?

Windows

### Additional context

Please let me know how to fix this, i'm not very good with tech, for more information on how I setup it was, I just downloaded the prebuilt binary, extracted it to a folder and went cmd inside that folder to run the program, then I logged in and ran the command to try and download.

**Comment by iyear** [comment]
I see a message indicating that the message does not exist. Please check if the message in your link exists.
