### ISSUE TITLE
download for second problem

### ISSUE THREAD

**Issue by profumato4** [iyear/tdl#777]
### Describe the bug

i have 1gb on download when i download in steam i download at least 100 200 or 300  mb  or more for second but on tdl i have max 10mb or less 

### To Reproduce

.

### Expected behavior

.

### Version

Version: 0.17.3
Commit: 6c382b8
Date: 2024-07-07T10:59:56Z

go1.21.11 windows/amd64

### Which OS are you running tdl on?

Windows

### Additional context

.

**Comment by iyear** [comment]
1. Upgrade your tdl
2. Try `-t 16 --pool 0` flags

**Comment by profumato4** [comment]
the problem persists
