### ISSUE TITLE
[Bug] Cannot forward media to specific topic of a group

### ISSUE THREAD

**Issue by lzhan0121** [iyear/tdl#784]
### Describe the bug

When forwarding content to a group with Topic Mode enabled, even if you enter a link to a specific topic, the forwarded message will be sent directly to the "General" topic instead of the specific topic to which the link corresponds.

### To Reproduce

1. Copy the link of one topic of a group.
2. Use tdl to forward the media.

### Expected behavior

It should forward the media to the specific topic instead of the "General" topic.

### Version

Version: v0.17.7

### Which OS are you running tdl on?

Linux

**Comment by iyear** [comment]
What's the command?

**Comment by iyear** [comment]
`--to https://t.me/c/2311460644/28041` is not supported. 
If you want to forward to a specific topic, try `--to '{ Peer: "2311460644", Thread: 28041 }'` 

Refer to https://docs.iyear.me/tdl/guide/forward/#message-routing for details.
