### ISSUE TITLE
add requested url when get error FLOOD_WAIT

### ISSUE THREAD

**Issue by dodyac** [iyear/tdl#79]
Can you add what url has been requested in the FLOOD_WAIT error log? because when I use multi download, there are several files that have finished downloading, and sometimes I get the error, so it takes more effort to find the url that has failed to download.
Thanks

**Comment by iyear** [comment]
`FLOOD_WAIT` will be handled internally by tdl as auto-wait and should not be thrown. Are there any screenshots of this please?

**Comment by dodyac** [comment]
![image](https://user-images.githubusercontent.com/37199748/210035390-9714c19c-6692-4a3c-9792-2f3bb5a145f0.png)

**Comment by iyear** [comment]
v0.6.0 added flood wait middleware to solve this problem.
