### ISSUE TITLE
[Bug] Inexplicable error message during download process

### ISSUE THREAD

**Issue by diguoemo** [iyear/tdl#794]
### Describe the bug

下载过程中莫名其妙报错
还好可以用continune命令恢复 不过来了好多次才下好

嘘🤫(*****):1165 -> downloads\21213181~ ... 49.3% [#####.......] [344.00 MB in 8m29.575s; ~ETA: 8m50s; 691.27 KB/s]
嘘🤫(*****):1175 -> downloads\21213181~ ... 46.4% [#####.......] [346.00 MB in 8m26.599s; ~ETA: 9m55s; 699.38 KB/s]
嘘🤫(*****):1176 -> downloads\21213181~ ... 74.6% [########....] [345.50 MB in 8m25.455s; ~ETA: 2m58s; 699.95 KB/s]
[####################################.............................] [8m30s; 2.04 MB/s]
Error: group:
    github.com/gotd/td/mtproto.(*Conn).Run
        github.com/gotd/td@v0.110.1/mtproto/conn.go:214
  - task readLoop:
    github.com/gotd/td/tdsync.(*LogGroup).Go.func1
        github.com/gotd/td@v0.110.1/tdsync/log_group.go:48
  - read:
    github.com/gotd/td/mtproto.(*Conn).readLoop
        github.com/gotd/td@v0.110.1/mtproto/read.go:193
  - read:
    github.com/gotd/td/transport.(*connection).Recv
        github.com/gotd/td@v0.110.1/transport/connection.go:70
  - read intermediate:
    github.com/gotd/td/proto/codec.Intermediate.Read
        github.com/gotd/td@v0.110.1/proto/codec/intermediate.go:73
  - read length:
    github.com/gotd/td/proto/codec.readLen
        github.com/gotd/td@v0.110.1/proto/codec/codec.go:35
  - EOF

### To Reproduce

tdl dl -f c:\tdl\output.json -t 8 -l 4 --continue
有时候下一晚上都没事 有时候10分钟内连续报错

### Expected behavior

Error: group:
    github.com/gotd/td/mtproto.(*Conn).Run
        github.com/gotd/td@v0.110.1/mtproto/conn.go:214
  - task readLoop:
    github.com/gotd/td/tdsync.(*LogGroup).Go.func1
        github.com/gotd/td@v0.110.1/tdsync/log_group.go:48
  - read:
    github.com/gotd/td/mtproto.(*Conn).readLoop
        github.com/gotd/td@v0.110.1/mtproto/read.go:193
  - read:
    github.com/gotd/td/transport.(*connection).Recv
        github.com/gotd/td@v0.110.1/transport/connection.go:70
  - read intermediate:
    github.com/gotd/td/proto/codec.Intermediate.Read
        github.com/gotd/td@v0.110.1/proto/codec/intermediate.go:73
  - read length:
    github.com/gotd/td/proto/codec.readLen
        github.com/gotd/td@v0.110.1/proto/codec/codec.go:35
  - EOF

### Version

Version: 0.17.7
Commit: ace2402
Date: 2024-11-01T06:40:56Z

go1.21.13 windows/amd64

### Which OS are you running tdl on?

Windows

**Comment by iyear** [comment]
https://github.com/iyear/tdl/issues/158#issuecomment-1551116053
