### ISSUE TITLE
[Bug] thumb file doesn't work any more

### ISSUE THREAD

**Issue by rsyqvthv** [iyear/tdl#799]
### Describe the bug

filename.thumb doesn't work after updating of tdl, 
the last working version is 0.174

would you please fix this, thanks.

### To Reproduce

generate a png with same of video, but extension changed to "thumb"
then fire the upload command,
video upload successful, 
but missing the custom thumbnail, 
it auto pickup the first frame as thumb, which normally black in my case.

### Expected behavior

as version 0.174 or before, 
the thumbnail for uploaded video should shows with the videoname.thumb

### Version

v0.17.7

### Which OS are you running tdl on?

Windows

**Comment by iyear** [comment]
Sometimes PNG thumbnails can't be correctly recognized by the Telegram server (the recognition logic seems to be a black box). Try converting the image to JPG format to see if it works.

The related code has not been modified in these versions, so it is unlikely to be a code issue.
