### ISSUE TITLE
Sometimes. it's stuck when Preparing DC pool

### ISSUE THREAD

**Issue by dodyac** [iyear/tdl#80]
![image](https://user-images.githubusercontent.com/37199748/210030621-f60017fe-057f-4a6c-a6b4-e1008be4b190.png)

sometimes, it's stuck when preparing dc pool, i already wait for 1 hour, and it's still stuck

**Comment by iyear** [comment]
Try using the `--proxy` or `--ntp` flag, as described in the README

**Comment by dodyac** [comment]
sometimes, it's still stuck
![image](https://user-images.githubusercontent.com/37199748/210038760-70f61fa5-22d2-4c5f-a837-5fb8997d3c49.png)
can you add such as request timeout?

**Comment by iyear** [comment]
This is usually a network problem, so just stop the program when the wait time is too long.
