### ISSUE TITLE
[Feat] Better Filter documentation

### ISSUE THREAD

**Issue by pgotsis** [iyear/tdl#806]
### Proposal

I am checking the "-f -" option for the chat export command, to find the available fields for filters. For version 0.17.7, I get the following list:

```
Mentioned: bool # Whether we were mentioned in this message
Silent: bool # Whether this is a silent message (no notification triggered)
FromScheduled: bool # Whether this is a scheduled message
Pinned: bool # Whether this message is pinned
ID: int # ID of the message
FromID: int64 # ID of the sender of the message
Date: int # Date of the message
Message: string # The message
Media.Name: string # File name
Media.Size: int64 # File size. Unit: Byte
Media.DC: int # DC ID
Views: int # View count
Forwards: int # Forward count
```

It seems that a lot is missing. First of all, in your documentation page (https://docs.iyear.me/tdl/guide/tools/list-chats/) you are demonstrating the use of "Type", "VisibleName" and "Topics" which are not in this list. Secondly, I am trying to configure a filter to download after a specific Message ID like this, ID>1234, and I get an error.

What can be done to fix this?

### Background

Better filter documentation to control export file contents.

### Workarounds

I do not know of any current workarounds apart from parsing the json file of the export before feeding to the dl command.

**Comment by iyear** [comment]
1. Distinguish between `chat ls` and `chat export`. The former is used to list chats, while the latter is used to export messages from a chat.
2. Export messages with ID > 1234 using `tdl chat export -c CHAT -T id -i 1234,9999999`.

**Comment by leoshane13** [comment]
I also have the question about the available fields, in the help cmd line, it says 

> -f, --filter string     filter messages by expression, defaults to match all messages. Specify '-' to see available fields (default "true")

But after I try

>tdl chat export --filter -

The cmd line will be stucked there without any response, is there any idea about this?Thanks

**Comment by MissingTwins** [comment]
I think the ID filter is for secondary usage.
`tdl.exe chat export -c CHATID --with-content -T last -i 10 -f "ID>1335402"`
