### ISSUE TITLE
已删除的帐号可以下载吗

### ISSUE THREAD

**Issue by aiastia** [iyear/tdl#808]
想备份一下已删除的帐号聊天文件

**Comment by iyear** [comment]
不行，已删除账号session全部无法登录

**Comment by aiastia** [comment]
> 不行，已删除账号session全部无法登录

不是说已删除的账号  而是是说和 已删除 已销户的用户的聊天内容

**Comment by iyear** [comment]
> > 不行，已删除账号session全部无法登录
> 
> 不是说已删除的账号 而是是说和 已删除 已销户的用户的聊天内容

那是可以的

**Comment by aiastia** [comment]
> > > 不行，已删除账号session全部无法登录
> > 
> > 
> > 不是说已删除的账号 而是是说和 已删除 已销户的用户的聊天内容
> 
> 那是可以的

和正常帐号流程一样吗 导出然后json 在下载吗

**Comment by aiastia** [comment]
另外想问下 如何保留文件格式名 而不是文件名。比如 .mp3 这种 很多时候碰见奇怪文件名 win 无法保存文件导致报错

**Comment by iyear** [comment]
请先阅读文档：https://docs.iyear.me/tdl/guide/download/#name-template
