### ISSUE TITLE
How to dl all media from private group?

### ISSUE THREAD

**Issue by DeadNumbers** [iyear/tdl#81]
subj

**Comment by iyear** [comment]
1. Export JSON (https://github.com/iyear/tdl/blob/master/docs/desktop_export.md)
2. Use `tdl dl -f`

**Comment by DeadNumbers** [comment]
> 1. Export JSON (https://github.com/iyear/tdl/blob/master/docs/desktop_export.md)
> 
>     2. Use `tdl dl -f`

and if the owner of the room has banned the export and sharing of media?

**Comment by iyear** [comment]
It mentions https://github.com/iyear/tdl/blob/master/docs/desktop_export.md#tdl-especially-for-protected-chats

**Comment by DeadNumbers** [comment]
@iyear thanks.

**Comment by Louis24** [comment]
![image](https://github.com/iyear/tdl/assets/18719360/15044fcd-239b-4c18-a6be-9808ba3c8381)

**Comment by iyear** [comment]
@Louis24 https://docs.iyear.me/tdl/guide/download/#from-json refer to the tabs
