### ISSUE TITLE
Video dowloads without extension

### ISSUE THREAD

**Issue by DeadNumbers** [iyear/tdl#82]
<img width="663" alt="Снимок экрана 2022-12-31 в 11 14 22" src="https://user-images.githubusercontent.com/9416005/210130188-bc4b16c9-7941-41b7-9574-c96f04462c5e.png">

**Comment by iyear** [comment]
The file itself does not have an extension on the server, so it is not available after download. You can pass in the `rewrite-ext` flag to let tdl help you rewrite the correct extension.
