### ISSUE TITLE
[Bug] Please complete title/请完善标题

### ISSUE THREAD

**Issue by deep0d0** [iyear/tdl#836]
### Describe the bug

I just installed on a new machine, and nothing is happening at all. Terminal is just empty.

![photo_2024-12-21 22 34 04](https://github.com/user-attachments/assets/f371d773-c4dc-46fa-8dcf-e78bdf105065)

Telegram is installed from the website. Windows 11 latest

### To Reproduce

1) Install Telegram
2) Install TDL
3) Login to Telegram, then TDL
4) Nothing happens

### Expected behavior

It should do something?

### Version

Version: 0.18.3
Commit: 3cac28d
Date: 2024-11-29T08:24:07Z
go1.21.13 windows/amd64

### Which OS are you running tdl on?

Windows

### Additional context

Works fine on a Mac and other windows computer, just not this one for some reason

**Comment by s0ldi3r4** [comment]
same here, the app is down

**Comment by iyear** [comment]
Check your flags: https://docs.iyear.me/tdl/more/troubleshooting/#q-why-no-response-after-entering-the-command-and-why-there-is-msg_id-too-high-in-the-log

**Comment by deep0d0** [comment]
Wow, didn’t even realize that time was bad!
