### ISSUE TITLE
[Feat] Provide the option to upload to other chats too, not only to Saved Messages

### ISSUE THREAD

**Issue by art435** [iyear/tdl#85]
Expand the functionality of the program by adding an option to upload to other chats, like `tdl up -p /path/to/dir -c chat_id`

**Comment by iyear** [comment]
Allowing only pass to `saved messages` can effectively reduce the risk of blocking. The same effect can be achieved by forwarding `saved messages` to other chats.

**Comment by art435** [comment]
I uploaded thousands of files to a private channel without any issues. Ironically, I was banned after forwarding far less with a new account. I wrote to Telegram and the ban was lift. After researching a bit, my conclusion is that banning occur when doing heavy stuff with new accounts or with accounts registered with virtual numbers. Can also be possible when doing many API calls in a short period of time.

Sure, I can upload to Saved Messages and forward from there, but is time-consuming and actually increases the number of API calls.

**Comment by iyear** [comment]
Accepted
