### ISSUE TITLE
Download part and then block

### ISSUE THREAD

**Issue by WangJiu-czy** [iyear/tdl#91]
Some logins succeeded, but they could not be downloaded through json files.
Trying again failed to log in
![image](https://user-images.githubusercontent.com/59927567/212526847-b47808ba-1731-496d-bb34-056412663a3d.png)

**Comment by WangJiu-czy** [comment]
Sorry, it turns out that there is a space in my path, causing the program to recognize two parameters

**Comment by WangJiu-czy** [comment]
![image](https://user-images.githubusercontent.com/59927567/212527651-846c3e38-b265-4e1e-8c77-406331fe9da7.png)
> The downloaded image has an extra tmp suffix and is not renamed
![image](https://user-images.githubusercontent.com/59927567/212527668-3149f9ad-8067-4522-a439-6f85084d5261.png)

**Comment by iyear** [comment]
It looks like you have a network problem, a picture download is usually within 1s.

**Comment by iyear** [comment]
The new version has been released, feel free to try it. It may solve this problem.
