### ISSUE TITLE
[BUG] Error: open key_data: file "key_data" not found

### ISSUE THREAD

**Issue by Tinkerbells** [iyear/tdl#92]
Getting an error when using tdl login username -d "/usr/bin/Telegram" command on Linux (Arch). Telegram is official desktop bin. 
![image](https://user-images.githubusercontent.com/55500372/213235812-6a4373f7-2917-4ca9-bcf0-829226946c11.png)

**Comment by iyear** [comment]
Is there a `tdata` directory in Telegram's root directory? If it doesn't exist, try looking globally for the `tdata` directory and pointing `-d` to that directory.

**Comment by iyear** [comment]
The new version has been released, feel free to try it or reopen the issue.

**Comment by aaarghhh** [comment]
If it can be helpful, in Ubuntu I found these directories in different clients.
```
./snap/telegram-desktop/[version]/.local/share/TelegramDesktop/tdata
./.local/share/KotatogramDesktop/tdata
./.local/share/64Gram/tdata
```

I would ask if you can introduce an auth mechanism like Telethon. 
I mean, it also accepts a base 64string for a session parameter https://docs.telethon.dev/en/stable/modules/sessions.html#telethon.sessions.string.StringSession. It could be very useful.

**Comment by iyear** [comment]
@aaarghhh Thank you very much for the possible data paths!

About base64string, I have a question, what is the standard for it? Telethon output?

**Comment by iyear** [comment]
Well, thank you for suggestions.
