### ISSUE TITLE
[Feat] When mass downloading many files, use a Takeout  session

### ISSUE THREAD

**Issue by art435** [iyear/tdl#96]
This is a feature of Telegram API [account.initTakeoutSession](https://core.telegram.org/method/account.initTakeoutSession). It doesn't say much, but the [Telethon ](https://docs.telethon.dev/en/stable/modules/client.html#telethon.client.account.AccountMethods.takeout)implementation gives more details.

> Returns a [TelegramClient] which calls methods behind a takeout session.
> 
> It does so by creating a proxy object over the current client through which making requests will use [InvokeWithTakeoutRequest] to wrap them. In other words, returns the current client modified so that requests are done as a takeout:
> 
> Some of the calls made through the takeout session will have lower flood limits. This is useful if you want to export the data from conversations or mass-download media, since the rate limits will be lower.

I think this is useful when downloading numerous files from a channel using the exported json, because this method have lower rate limits, it better protects the account and probably download will be interrupted less often because floodwait will occur less. Probably the official client uses this method when exporting chat history.

**Comment by iyear** [comment]
Great idea! I've implemented this roughly so far (briefly browsed `telethon` and `tdesktop`). But it looks like this is a black box and more practice is needed to see how much it can actually do.

**Comment by art435** [comment]
I hope this feature will lower those flodwaits. [Pyrogram ](https://docs.pyrogram.org/api/client) has it too:

> takeout (bool, optional) – Pass True to let the client use a takeout session instead of a normal one, implies no_updates=True. Useful for exporting Telegram data. Methods invoked inside a takeout session (such as get_chat_history, download_media, …) are less prone to throw FloodWait exceptions.

**Comment by iyear** [comment]
The new version has been released, feel free to try it or reopen the issue.
