### ISSUE TITLE
Upload problem

### ISSUE THREAD

**Issue by facmasterII** [iyear/tdl#97]
Hello bro i have a issue when use for upload. automatically aborted

![image](https://user-images.githubusercontent.com/91332853/215947981-561852db-3f09-494c-98a1-87104f7137e3.png)

**Comment by iyear** [comment]
Trying to reduce threads? An excessive number of concurrent connections can lead to a forced shutdown by the Telegram server.

**Comment by facmasterII** [comment]
> Trying to reduce threads? An excessive number of concurrent connections can lead to a forced shutdown by the Telegram server.

Yes i use 1, 2, 4, 8, 16, 30, 100 thread and all get the error (upload aborted)

**Comment by suntong** [comment]
Make sure to use `-t 1 -l 1` when reporting such problem.

**Comment by iyear** [comment]
Upgrade to latest version and set `--reconnect-timeout 0` flag
